import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import {
  getBarLength,
  getBeatLength,
  getBeatsPerMeasure,
  getBpm,
  getPickupLength,
  millisecondsPerMeasureOf,
  timingsOf,
} from '../src/audio/timing.js'
import { parse } from '../src/parser/parser.js'

/**
 * **THE NINE NUMERIC `AbcTune` ACCESSORS, AGAINST ABCJS'S OWN ANSWERS ON 293 TUNES.**
 *
 * `getBeatLength`, `getBarLength`, `getBeatsPerMeasure`, `getBpm`, `getPickupLength`,
 * `millisecondsPerMeasure` (twice — the tune's rate and a host override) and, after
 * `setTiming(0, 0)`, `getTotalTime` and `getTotalBeats`.
 *
 * **THESE HAD NO GATE.** abcjs's own suite touches a handful of them inside
 * `timing.test.js` and nothing else, so a wrong `getBeatLength` would have surfaced only
 * as a wrong clock somewhere downstream — which is exactly how `%%vocalfont` and the
 * tempo notehead survived for weeks. The oracle is `tests/corpus-accessors/golden.json`,
 * generated by RUNNING abcjs 6.7.0 over both corpora; see the README beside it.
 *
 * `getMeter` and `getMeterFraction` are deliberately not here: they return abcjs's own
 * meter OBJECT, which is a projection question rather than a number, and they are gated
 * with the rest of the tune-object shape.
 */
const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, 'corpus-accessors', 'golden.json'), 'utf-8'),
) as Record<string, Record<string, number | null>>

const SIBLING = join(import.meta.dirname, '..', '..', 'abcMusicKit', 'Tools', 'abcjs-debug', 'fixtures')
const IN_REPO = join(import.meta.dirname, 'corpus-abcjs', 'fixtures')

/**
 * `S7-voices` is EXCLUDED and the reason is not ours — its fixture was edited in the
 * sibling repo on 2026-08-12 and its goldens were never regenerated
 * (`CHECKPOINT-2026-08-12.md` §5).
 */
const STALE = ['sib/S7-voices']

interface Row {
  readonly slug: string
  readonly want: Record<string, number | null>
  readonly got: Record<string, number | undefined>
}

const rows = (): Row[] => {
  const out: Row[] = []
  const cache = new Map<string, ReturnType<typeof parse>>()
  for (const [key, want] of Object.entries(GOLDEN)) {
    if (STALE.some((s) => key.startsWith(s))) continue
    const [corpus, rest] = [key.slice(0, key.indexOf('/')), key.slice(key.indexOf('/') + 1)]
    const at = rest.lastIndexOf('-tune')
    const file = rest.slice(0, at)
    const index = Number(rest.slice(at + '-tune'.length))
    const dir = corpus === 'sib' ? SIBLING : IN_REPO
    let parsed = cache.get(`${corpus}/${file}`)
    if (parsed === undefined) {
      parsed = parse(readFileSync(join(dir, `${file}.abc`), 'utf-8'), { mode: 'abcjs-strict' })
      cache.set(`${corpus}/${file}`, parsed)
    }
    const score = parsed.ok ? parsed.scores[index] : undefined
    if (score === undefined) continue
    const totals = timingsOf(score, {})
    out.push({
      slug: key,
      want,
      got: {
        beatLength: getBeatLength(score),
        barLength: getBarLength(score),
        beatsPerMeasure: getBeatsPerMeasure(score),
        bpm: getBpm(score),
        pickupLength: getPickupLength(score),
        msPerMeasure: millisecondsPerMeasureOf(score),
        msPerMeasure120: millisecondsPerMeasureOf(score, 120),
        totalTime: totals.totalTime,
        totalBeats: totals.totalBeats,
      },
    })
  }
  return out
}

/** Slugs that are EXACT on all nine and must stay so. Grows, never shrinks. */
const PASSING: readonly string[] = []

describe("abcjs's numeric tune accessors", () => {
  const table = rows()

  it('has a row for every tune abcjs answered for', () => {
    expect(table.length).toBeGreaterThan(250)
  })

  for (const key of ['beatLength', 'barLength', 'beatsPerMeasure', 'bpm', 'pickupLength'] as const) {
    it(`${key} matches abcjs`, () => {
      const off = table
        .filter((r) => r.got[key] !== r.want[key])
        .map((r) => `${r.slug}: abcjs ${String(r.want[key])}, ours ${String(r.got[key])}`)
      expect(off.slice(0, 20)).toEqual([])
    })
  }

  for (const key of ['msPerMeasure', 'msPerMeasure120', 'totalTime', 'totalBeats'] as const) {
    it(`${key} matches abcjs`, () => {
      const off = table
        .filter((r) => r.got[key] !== r.want[key])
        .map((r) => `${r.slug}: abcjs ${String(r.want[key])}, ours ${String(r.got[key])}`)
      expect(off.slice(0, 20)).toEqual([])
    })
  }

  it('every ratcheted slug is exact on all nine', () => {
    const broken = table
      .filter((r) => PASSING.includes(r.slug))
      .filter((r) => Object.keys(r.want).some((k) => r.got[k] !== r.want[k]))
      .map((r) => r.slug)
    expect(broken).toEqual([])
  })
})
