import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { createRequire } from "node:module";

import { describe, expect, it } from "vitest";

import { renderAbc, startAnimation, stopAnimation } from "../src/compat/index.js";

/**
 * **jsdom COMES FROM THE SIBLING REPO'S `node_modules`, NOT FROM OURS.** The harvesters
 * already reach it that way (`createRequire` off `abcjs-debug/package.json`) and this gate
 * needs the same DOM the oracle was recorded in — real `querySelector` matching over the
 * rendered SVG, which no hand-rolled stub can stand in for. abcts itself gains no
 * dependency, which is the point: the compat layer needs a DOM from its HOST, never from
 * the package.
 */
const sibling = createRequire(
  join(
    import.meta.dirname,
    "..",
    "..",
    "abcMusicKit",
    "Tools",
    "abcjs-debug",
    "package.json",
  ),
);
interface DomDocument {
  getElementById(id: string): DomElement | null;
}
interface DomElement {
  querySelector(selector: string): { style: Record<string, string> } | null;
  querySelectorAll(selector: string): ArrayLike<unknown>;
}
const { JSDOM } = sibling("jsdom") as {
  JSDOM: new (html: string) => { window: { document: DomDocument } };
};

/**
 * **`startAnimation` — THE CURSOR AS IT IS ACTUALLY DRAWN.**
 *
 * The oracle is `tests/corpus-animation/golden.json`, generated by RUNNING abcjs 6.7.0 into
 * a jsdom page with its clock replaced (`scripts/harvest-abcjs-animation.mjs`). It records
 * what a host can SEE: the cursor `<div>`'s `left`/`top`/`width`/`height` and how many
 * elements the run has hidden, on every frame where either changed.
 *
 * **THE TIMER IS MODULE-PRIVATE IN abcjs, SO `requestAnimationFrame` IS WHAT DRIVES IT** —
 * stubbed to CAPTURE the callback rather than to schedule it, then called with a fixed 16ms
 * sequence. Ours is driven identically, through the same public entry point.
 *
 * ⚠️ **AND THE FIRST FRAME CANNOT BE 0**: `doTiming` opens with
 * `if (self.lastTimestamp === timestamp) return` and `lastTimestamp` starts at 0, so a
 * drive from zero returns before registering the next frame and nothing ever animates. A
 * browser's own timestamp is never 0 either. The first harvest logged one frame per case
 * and an empty cursor, which is exactly what that looks like.
 */
type Frame = [number, (string | undefined)[] | null, number];

const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-animation", "golden.json"), "utf-8"),
) as Record<string, Frame[]>;

const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

const SHAPES: Record<string, Record<string, boolean>> = {
  cursor: { showCursor: true },
  "hide-finished": { showCursor: true, hideFinishedMeasures: true },
  "hide-current": { showCursor: true, hideCurrentMeasure: true },
};

const drive = (key: string): Frame[] => {
  const [file = "", label = ""] = key.split("#");
  const abc = readFileSync(join(IN_REPO, `${file}.abc`), "utf-8");
  const dom = new JSDOM(
    '<!DOCTYPE html><html><body><div id="paper"></div></body></html>',
  );
  const g = globalThis as Record<string, unknown>;
  const saved = {
    document: g["document"],
    window: g["window"],
    requestAnimationFrame: g["requestAnimationFrame"],
    setTimeout: g["setTimeout"],
    clearTimeout: g["clearTimeout"],
    performance: g["performance"],
  };
  let clock = 0;
  let framed: ((t: number) => void) | null = null;
  g["document"] = dom.window.document;
  g["window"] = dom.window;
  g["requestAnimationFrame"] = (fn: (t: number) => void) => {
    framed = fn;
    return 0;
  };
  g["setTimeout"] = () => 0;
  g["clearTimeout"] = () => {};
  g["performance"] = { now: () => clock };
  const log: Frame[] = [];
  try {
    const paper = dom.window.document.getElementById("paper");
    if (paper === null) return [];
    const tune = renderAbc("paper", abc, { add_classes: true })[0];
    if (tune === undefined) return [];
    stopAnimation();
    startAnimation(paper as never, tune, SHAPES[label] ?? {});
    const hidden = (): number =>
      paper.querySelectorAll('[style*="display: none"]').length;
    for (let t = 16; t <= 20000; t += 16) {
      clock = t;
      const fn = framed;
      framed = null;
      if (!fn) break;
      (fn as (time: number) => void)(t);
      const c = paper.querySelector(".abcjs-cursor") as { style: Record<string, string> } | null;
      log.push([
        t,
        c ? [c.style.left, c.style.top, c.style.width, c.style.height] : null,
        hidden(),
      ]);
    }
  } finally {
    for (const [k, v] of Object.entries(saved)) g[k] = v;
  }
  return log.filter(
    (row, i) =>
      i === 0 ||
      JSON.stringify(row.slice(1)) !== JSON.stringify(log[i - 1]?.slice(1)),
  );
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const rows = (): Row[] => {
  const out: Row[] = [];
  for (const [key, want] of Object.entries(GOLDEN)) {
    const got = drive(key);
    let agree = 0;
    let first = "";
    for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
      if (JSON.stringify(want[i]) === JSON.stringify(got[i])) agree += 1;
      else if (first === "")
        first = `frame ${i}: abcjs ${JSON.stringify(want[i])} ours ${JSON.stringify(got[i])}`;
    }
    out.push({ slug: key, agree, total: want.length, first });
  }
  return out;
};

describe("startAnimation — the cursor as it is drawn", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table.filter((r) => r.agree < r.total);
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-animation-ranked.txt",
      `${[
        `${off.length} of ${table.length} cases differ; ${agree} of ${total} frames agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(64)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(40);
  });

  it("every case moves the cursor the same way", () => {
    const broken = table
      .filter((r) => r.agree < r.total)
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken.slice(0, 10)).toEqual([]);
  });
});
