/**
 * THE ABCJS TEST-SUITE CORPUS — 174 tunes abcjs's own maintainers chose to test.
 *
 * ── WHY THIS EXISTS ─────────────────────────────────────────────────────────
 * The 41-fixture corpus is the gate everything else runs against, and it is OUR idea of
 * what is worth exercising. abcjs's `tests/` is ITS authors' idea, and the two are not
 * the same coverage — nothing in the 41 uses `%%stretchlast`, `%%maxStaves`, a zero-length
 * note, or a voice overlay that crosses a barline, and abcjs tests all four.
 *
 * The tunes are harvested by `scripts/harvest-abcjs-tests.mjs` and their goldens
 * generated by running abcjs itself (`scripts/harvest-abcjs-goldens.mjs`). Its 272 `it()`
 * cases are NOT ported: they assert against abcjs's internal `visualObj` tree, which
 * `abcts/compat` does not reproduce. The inputs transfer; the assertions do not.
 *
 * ── WHAT IS ASSERTED, AND WHY NOT 174 CEILINGS ──────────────────────────────
 * Three things, in the order they matter:
 *
 *  1. NOTHING THROWS. 174 tunes from someone else's test suite is the best fuzz corpus in
 *     the repo, and this is the assertion that has to stay flat at 100%.
 *  2. NOTEHEAD COUNTS, per fixture, against a named list of the ones that do not match.
 *     Those names are the CONTENT gaps and each is a bug with a cause recorded below. A
 *     new name failing means a regression; an old one passing means the list is stale and
 *     must be shortened — the same ratchet the pixel gate uses.
 *  3. GEOMETRY IN AGGREGATE — how many fixtures land within a threshold, not a ceiling
 *     each. 174 individual numbers would be noise nobody reads and a merge conflict every
 *     time; the counts move only when something real changes, and they only go up.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { renderAbc } from '../src/compat/index.js'
import { parse } from '../src/parser/parser.js'
import { absolutePixels, byClass } from './pixel-geometry.js'

const base = join(dirname(fileURLToPath(import.meta.url)), 'corpus-abcjs')
const fixturesDir = join(base, 'fixtures')
const goldenDir = join(base, 'golden')

/**
 * Fixtures whose notehead count does not match abcjs's, and WHY.
 *
 * Every one is a real gap found by this corpus and by nothing else in the repo.
 */
const CONTENT_GAPS: Readonly<Record<string, string>> = {
  // `(f3 {a})y` — the grace attaches to the `y` SPACER that follows it, and `Rest` has
  // no `graceNotes` field, so the parser drops it. The model says so deliberately: "a
  // rest does carry decorations — but not ties, slurs, grace notes or lyrics, none of
  // which apply to silence". abcjs disagrees for a spacer, which is a layout device
  // rather than silence, and draws the grace with its own stem, flag and ledger.
  // A MODEL DECISION, not a mechanical fix — see the checkpoint.
  'abcjs-visual-tablature-10-f3-a-y': 'a grace note before a `y` spacer is dropped at parse',
  // `%% example / T: wed / %%example / X:1` — a `T:` standing before any `X:`. abcjs
  // keeps the leading block as part of the first tune; we split it off as a tune of its
  // own, so the book has two where abcjs has one.
  'abcjs-parse-book_parser-04-wed': 'a header block before the first X: splits the book',
}

/**
 * How many fixtures land within each threshold, on all four axes at once.
 *
 * A RATCHET, like the pixel gate's ceilings: these may only go up, and a run that
 * improves one has to record it. They are counts rather than per-fixture numbers because
 * 174 ceilings is a table nobody reads — see the header.
 */
const WITHIN: Readonly<Record<string, number>> = {
  // 72 / 83 / 91 / 116 at the start of this arc's second session. What moved them, all
  // read out of abcjs's algorithm and none of it exercised by the 41 fixtures except the
  // last: `clef=none` and `clef=perc` read as a C clef on the middle line; `%%text` /
  // `%%begintext` reserving nothing; `V:… merge` unimplemented; a clef name matched as a
  // whole word rather than by prefix, so `bass,,` was no clef at all; an empty implicit
  // voice `1` taking a staff on every system of a tune whose lines all begin `[V:…]`; and
  // the two line-assignment rules — a trailing `\` continuing the line, and a `[V:x]`
  // switch opening one only when x already has music.
  //
  // 2026-08-03c: a mid-tune `[K:]` reserving the SAME declared box the opening signature
  // does (a natural's fudge is 0 and it is the tall glyph); the `A:` and header-`P:` rows
  // of the top-text block, which abcjs draws and we did not; every `%%<type>font` parsed
  // and its size threaded through the block; and a mid-tune `T:` no longer counted as a
  // top-block subtitle, which it never was — abcjs takes only LEADING subtitle lines.
  // A ZERO-DURATION NOTE SPACES AS A QUARTER — abcjs rewrites `duration` to 0.25 before
  // anything reads it, head, stem and advance alike.
  // THE VOICE-OVERLAP RULE — a note in a non-top voice touching the top voice's is
  // displaced right of it, and its element widens by that head. `visual-layout-04` 90.1 -> 1.7.
  // An `&` overlay's PAD is the measure's own duration, not the meter's.
  // A CHORD SYMBOL'S TYPOGRAPHY: `Bb` is `B♭` and `C#` is `C♯`, and `♯` is a full em
  // where `#` is 0.556. `visual-transpose-output-01` 106.8 -> 0.25.
  // MID-TUNE NON-MUSIC LINES: a `%%text`, `%%center`, `%%sep` or `T:` between two music
  // lines is a LINE of its own, and its height is ADDITIVE to the staff separation.
  // ONE ending lane, spent ONCE: `anchorAboveStaff`'s ink call had the volta's share of
  // it and not the tuplet's, so the two disagreed about what the lane already held.
  // THE FIRST TOKEN OF A `K:` IS THE KEY ONLY WHEN IT PARSES AS ONE, uppercase A..G,
  // `HP`, `Hp` or `none` — so `K:none` keeps its treble clef, `K:C none` loses it, `K:cm`
  // is C major with nothing printed, and `K: bass` is the bass clef. Plus `clef=perc`,
  // which DRAWS and takes 26px of prefix where we drew and reserved nothing.
  // A MID-TUNE CLEF: `K:C clef=bass` and `[K: bass]` change the clef from there on, print
  // where they stand, and are reprinted at the head of every system after.
  // `[` BEFORE A DIGIT OR A QUOTE IS AN INVISIBLE BARLINE — how `[1 …` writes a repeat
  // ending with no bar before it. Lexed as a chord, `visual-layout-09` stacked seven
  // noteheads on one x.
  // A BAR THAT STARTS AN ENDING gets `minspacing += textWidth + 10`, measured in
  // `repeatfont` — 28.5 against a plain bar's 10 for a `|1`.
  // GRACE NOTES ARE EMITTED AFTER THEIR MAIN HEAD, which is abcjs's document order. The
  // gate pairs the i-th notehead, so playing order read as a position error on every
  // graced fixture — and ragtime's dy 58.1, filed for weeks as unchaseable, was this.
  // `%%musicspace` — the gap before the FIRST staff group, in points times 4/3.
  // EXPLICIT KEY ACCIDENTALS — `K: C ^/f _/B _A ^D` prints them in the signature.
  // A MID-TUNE `K: octave=` is GLOBAL, and a voice with no `octave=` of its own follows it.
  // `hasVocals` IS PER SYSTEM AND MONOTONIC — a tune whose lyrics arrive on its second
  // system engraves the FIRST with dynamics BELOW.
  // A DECORATION WRITTEN BEFORE A BARLINE ATTACHES TO THE BARLINE, at a fixed pitch 12.
  // THE MODE MAY BE ITS OWN TOKEN — `K:F# dor` and `K:D Dorian` are read across the space.
  // A MID-TUNE `[M:4/4]` PRINTS WHERE IT STANDS — a restated one prints nothing.
  // A `Q:` AFTER THE FIRST prints where it stands, on its own voice's staff.
  // TEXT IS MEASURED WITH `dump-svg.js`'s `calcWidth` — five ASCII tables picked by SIZE
  // alone and a flat 8 for every character outside them. `visual-tablature-17` was 499px
  // out on that one rule.
  // `%%jazzchords` SETS THE MODIFIER AND THE BASS AS NESTED TSPANS, and the generator
  // counts each as a whole LINE of height — `"x/C"` measures three lines and its chord
  // lane reserves 38.4px more. 38.37 -> 0.07 on that one rule.
  // EVERY DECLARED BOX IS THE PUBLISHED `h`, NOT THE DERIVED INK BOX. The G clef declares
  // 57.057px against an ink box of 57.09 and a sharp declares 20.15 against 20.19 — 0.03
  // and 0.04px, a fiftieth of a staff space each, and between them the SYSTEMIC `oy` that
  // sat under every fixture in this corpus. Eleven fixtures came off the table on it.
  // AN ENDING LANE OVER A CHORD LANE COSTS A FLAT 2 PITCH, margin included, instead of
  // `endingHeightAbove + margin` (`set-upper-and-lower-elements.js:33-38`). A different
  // BRANCH, not a scaling: 2 against a volta's 6 is 15.5px, which a ladder of five control
  // tunes put on `"D7"…|1…` and on nothing simpler.
  // A CHORD'S LANE IS ITS MEASURED HEIGHT — the golden's size table with `size + 2` for
  // anything unlisted, a whole LINE per nested tspan, and `padding * 4` when the font is
  // BOXED. `visual-tablature-17`'s five boxed `%%gchordfont` sizes were a ratio before.
  // A TUPLET'S BRACKET IS INK THE CHORD LANE SITS ON, since `layoutVoice` calls
  // `adjustRange` on every `TripletElem` before any lane is added.
  // AN ANNOTATION'S PLACEMENT DECIDES ITS RESERVE, and only two of the five take a lane:
  // `RelativeElement`'s `case "text"` gives `chordHeightAbove` when the pitch is UNDEFINED
  // (`relative-element.js:68-75`), which `above` and `below` are and `left`, `right` and
  // `@x,y` are not. A LEFT one takes `width + 7` of room before the note and a RIGHT one 4
  // either side (`add-chord.js:50-71`); an `@` takes none at all and reserves a POINT at
  // `minpitch + (y + 3 * STEP) / STEP`.
  // TWO CHORD SYMBOLS ON ONE NOTE STACK — `"D""G"d` is one name `D\nG` and each LINE is
  // its own centred mark, so it opens a second chord LANE and 18.52px of staff.
  // A REST CARRIES ITS CHORD SYMBOL AND ANNOTATIONS. abcjs runs `addChord` over every
  // abselem regardless of type, so `"Eb7"z` prints the chord and reserves the whole chord
  // lane. Ours dropped both at parse — the mark was LOST, not just mispositioned.
  // AN ANNOTATION IS LEFT-JUSTIFIED AT ITS ELEMENT where a chord symbol is CENTRED on it:
  // `getChordDim`'s `offset = type === "chord" ? realWidth / 2 : 0`, and the golden says
  // the same in one attribute — `text-anchor="start"` against `"middle"`. Centring ours
  // reached further left and opened chord LANES abcjs does not.
  // AN ADDITIVE METER IS DRAWN TERM BY TERM — `M:2+3/8` is the string `2+3` over `8`, one
  // glyph per character (`create-time-signature.js:17-27`), not the sum `5`. 17.08px.
  // `%%barnumbers` / `%%measurenb` / `%%setbarnb` — and a bar number is GEOMETRY before it
  // is text. `addMeasureNumber` puts it at pitch `vert + height / STEP` with `vert` 11 on a
  // barline and adds it with `addFixed`, so it enters the staff's ink and beats the clef's
  // 13.72 — 10.5px on a plain treble tune. Only the FIRST voice advances the counter, an
  // empty measure does not, and an invisible barline is not a boundary for counting.
  // LEADING WHITESPACE IS NOT PART OF A DIRECTIVE'S NAME — `%% barnumbers 1`.
  // A `K:` CLEF CHANGE ON ITS OWN LINE PRINTS TWICE — once at the END of the line still
  // open when the field was parsed, and again in the next system's prefix. Suppressing our
  // inline draw was half the rule; drawing it after the previous line's last barline is the
  // other half. `visual-selection-03`'s seven systems each sat 11.63px high without it.
  // EVERY FONT SITE READS ITS OWN `%%<type>font`, and four of them are geometry:
  // `measurefont` (the bar number), `annotationfont` (which abcjs picks over `gchordfont`
  // for an annotation), `partsfont` (the `P:` lane) and `voicefont` (the left edge, plus
  // the trailing "A" abcjs measures in the SAME font rather than as a constant).
  // A ROW ADVANCES BY WHICHEVER FIELD MOVES IT: the rhythm is given `noMove` whenever a
  // composer or origin is present, so `composerfont` alone sets that row and not the taller
  // of the two. And a BOXED font's `padding * 4` is in every MEASURED height —
  // `getTextSize.calc` adds it, so a mid-tune `%%text` and `T:` carry it too.
  // …AND THE BOX IS ON THE WIDTH TOO, which is a chord's `realWidth`: how far a centred
  // mark reaches either side of its note and where `placeInLane` puts its right edge.
  // `visual-tablature-17` boxes five `%%gchordfont` sizes and was 33.9px of dx out on it.
  '0.05': 135,
  '1': 143,
  '5': 157,
  '25': 172,
}

const names = readdirSync(fixturesDir)
  .filter((f) => f.endsWith('.abc'))
  .map((f) => f.replace(/\.abc$/, ''))
  .sort()

const goldens = readdirSync(goldenDir)

/** abcjs writes one SVG per tune, `<name>.svg` alone or `<name>-tuneN.svg` for a book. */
const goldensFor = (name: string): string[] =>
  existsSync(join(goldenDir, `${name}.svg`))
    ? [`${name}.svg`]
    : goldens.filter((g) => g.startsWith(`${name}-tune`)).sort()

interface Measured {
  ourHeads: number
  goldenHeads: number
  dy: number
  dx: number
  oy: number
  ox: number
}

function measure(name: string): Measured {
  const abc = readFileSync(join(fixturesDir, `${name}.abc`), 'utf-8')
  const files = goldensFor(name)
  const ours = renderAbc('paper', abc, {})
  if (ours.length !== files.length) {
    return { ourHeads: -ours.length, goldenHeads: -files.length, dy: 0, dx: 0, oy: 0, ox: 0 }
  }
  let goldenHeads = 0
  let ourHeads = 0
  let dy = 0
  let dx = 0
  let sumY = 0
  let sumX = 0
  let paired = 0
  files.forEach((file, i) => {
    const g = byClass(absolutePixels(readFileSync(join(goldenDir, file), 'utf-8')), 'notehead')
    const o = byClass(absolutePixels(ours[i]?.svg ?? ''), 'notehead')
    goldenHeads += g.length
    ourHeads += o.length
    const n = Math.min(g.length, o.length)
    const deltas = (axis: 'x' | 'y'): number[] =>
      g.slice(0, n).map((head, k) => (o[k]?.[axis] ?? 0) - head[axis])
    const spread = (v: number[]): number => (v.length === 0 ? 0 : Math.max(...v) - Math.min(...v))
    dy = Math.max(dy, spread(deltas('y')))
    dx = Math.max(dx, spread(deltas('x')))
    sumY += deltas('y').reduce((a, b) => a + b, 0)
    sumX += deltas('x').reduce((a, b) => a + b, 0)
    paired += n
  })
  return {
    ourHeads,
    goldenHeads,
    dy,
    dx,
    oy: paired === 0 ? 0 : sumY / paired,
    ox: paired === 0 ? 0 : sumX / paired,
  }
}

describe('abcjs test-suite corpus', () => {
  it('the harvest and its goldens are in step', () => {
    expect(names.length).toBeGreaterThan(150)
    // A fixture without a golden would be silently unmeasured, which is the shape of
    // every gate bug this repo has recorded.
    expect(names.filter((n) => goldensFor(n).length === 0)).toEqual([])
  })

  describe('nothing throws', () => {
    for (const name of names) {
      it(`${name}`, () => {
        const abc = readFileSync(join(fixturesDir, `${name}.abc`), 'utf-8')
        const result = parse(abc)
        expect(result.ok).toBe(true)
        const rendered = renderAbc('paper', abc, {})
        expect(rendered.length).toBeGreaterThan(0)
        for (const tune of rendered) expect(tune.svg).toContain('<svg')
      })
    }
  })

  it('notehead counts match abcjs, except where a gap is recorded', () => {
    const mismatched: string[] = []
    for (const name of names) {
      const { ourHeads, goldenHeads } = measure(name)
      if (ourHeads !== goldenHeads) mismatched.push(name)
    }
    // Both directions: a new mismatch is a regression, and a fixed one means the list
    // above is stale. Neither is allowed to pass quietly.
    expect(mismatched.sort()).toEqual(Object.keys(CONTENT_GAPS).sort())
  })

  it('geometry does not regress', () => {
    const scores = names
      .filter((n) => CONTENT_GAPS[n] === undefined)
      .map((n) => {
        const m = measure(n)
        return Math.max(m.dy, m.dx, Math.abs(m.oy), Math.abs(m.ox))
      })
    const summary: Record<string, number> = {}
    for (const key of Object.keys(WITHIN)) {
      summary[key] = scores.filter((s) => s < Number.parseFloat(key)).length
    }
    // A ratchet: only up. An improvement must be RECORDED, or the number drifts away
    // from reality and stops meaning anything.
    expect(summary).toEqual(WITHIN)
  })
})
