/**
 * THE ABCJS TEST-SUITE CORPUS — 174 tunes abcjs's own maintainers chose to test.
 *
 * ── WHY THIS EXISTS ─────────────────────────────────────────────────────────
 * The 41-fixture corpus is the gate everything else runs against, and it is OUR idea of
 * what is worth exercising. abcjs's `tests/` is ITS authors' idea, and the two are not
 * the same coverage — nothing in the 41 uses `%%stretchlast`, `%%maxStaves`, a zero-length
 * note, or a voice overlay that crosses a barline, and abcjs tests all four.
 *
 * The tunes are harvested by `scripts/harvest-abcjs-tests.mjs` and their goldens
 * generated by running abcjs itself (`scripts/harvest-abcjs-goldens.mjs`). Its 272 `it()`
 * cases are NOT ported: they assert against abcjs's internal `visualObj` tree, which
 * `abcts/compat` does not reproduce. The inputs transfer; the assertions do not.
 *
 * ── WHAT IS ASSERTED, AND WHY NOT 174 CEILINGS ──────────────────────────────
 * Three things, in the order they matter:
 *
 *  1. NOTHING THROWS. 174 tunes from someone else's test suite is the best fuzz corpus in
 *     the repo, and this is the assertion that has to stay flat at 100%.
 *  2. NOTEHEAD COUNTS, per fixture, against a named list of the ones that do not match.
 *     Those names are the CONTENT gaps and each is a bug with a cause recorded below. A
 *     new name failing means a regression; an old one passing means the list is stale and
 *     must be shortened — the same ratchet the pixel gate uses.
 *  3. GEOMETRY IN AGGREGATE — how many fixtures land within a threshold, not a ceiling
 *     each. 174 individual numbers would be noise nobody reads and a merge conflict every
 *     time; the counts move only when something real changes, and they only go up.
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { renderAbc } from "../src/compat/index.js";
import { renderAll } from "./render-all.js";
import { parse } from "../src/parser/parser.js";
import { absolutePixels, byClass } from "./pixel-geometry.js";

const base = join(dirname(fileURLToPath(import.meta.url)), "corpus-abcjs");
const fixturesDir = join(base, "fixtures");
const goldenDir = join(base, "golden");

/**
 * Fixtures whose notehead count does not match abcjs's, and WHY.
 *
 * Every one is a real gap found by this corpus and by nothing else in the repo.
 */
const CONTENT_GAPS: Readonly<Record<string, string>> = {
  // CLOSED 2026-08-05: `(f3 {a})y`. This entry used to read "a MODEL DECISION, not a
  // mechanical fix", on the grounds that a rest carries "not ties, slurs, grace notes or
  // lyrics, none of which apply to silence". Three of those four are right. abcjs settles
  // the fourth in one line: `createNote` closes its rest/note branch and THEN calls
  // `addGraceNotes` (`abstract-engraver.js:834`), so a rest and a spacer engrave their
  // graces exactly as a note does. There was no decision to make — only a line to read.
  // CLOSED 2026-08-07: `%% example / T: wed / %%example / X:1`. This entry described the
  // symptom and guessed the cause — "abcjs keeps the leading block as part of the first
  // tune" — and abcjs does the opposite. `bookParser` splits on `"\nX:"` and, when that
  // gives more than one piece and the first does not itself start with `X:`, SHIFTS IT
  // OFF, keeping only its `%%` lines to prepend to every tune
  // (`abc_parse_book.js:12-33`, its own comment: "assume the top of the file is
  // intertune"). Everything else in it is DISCARDED, `T:` included. We already had the
  // `%%`-only half; what we lacked was that the test is "no `X:` yet", not "empty" —
  // `isEmpty` also wants no `T:` and no music, so a leading block with a title became a
  // tune of its own.
  //
  // THE LIST IS EMPTY, AND IT IS THE FIRST TIME. Every fixture of the harvested corpus
  // now agrees with abcjs on note content as well as on all four geometric axes.
};

/**
 * How many fixtures land within each threshold, on all four axes at once.
 *
 * A RATCHET, like the pixel gate's ceilings: these may only go up, and a run that
 * improves one has to record it. They are counts rather than per-fixture numbers because
 * 174 ceilings is a table nobody reads — see the header.
 */
const WITHIN: Readonly<Record<string, number>> = {
  // 72 / 83 / 91 / 116 at the start of this arc's second session. What moved them, all
  // read out of abcjs's algorithm and none of it exercised by the 41 fixtures except the
  // last: `clef=none` and `clef=perc` read as a C clef on the middle line; `%%text` /
  // `%%begintext` reserving nothing; `V:… merge` unimplemented; a clef name matched as a
  // whole word rather than by prefix, so `bass,,` was no clef at all; an empty implicit
  // voice `1` taking a staff on every system of a tune whose lines all begin `[V:…]`; and
  // the two line-assignment rules — a trailing `\` continuing the line, and a `[V:x]`
  // switch opening one only when x already has music.
  //
  // 2026-08-03c: a mid-tune `[K:]` reserving the SAME declared box the opening signature
  // does (a natural's fudge is 0 and it is the tall glyph); the `A:` and header-`P:` rows
  // of the top-text block, which abcjs draws and we did not; every `%%<type>font` parsed
  // and its size threaded through the block; and a mid-tune `T:` no longer counted as a
  // top-block subtitle, which it never was — abcjs takes only LEADING subtitle lines.
  // A ZERO-DURATION NOTE SPACES AS A QUARTER — abcjs rewrites `duration` to 0.25 before
  // anything reads it, head, stem and advance alike.
  // THE VOICE-OVERLAP RULE — a note in a non-top voice touching the top voice's is
  // displaced right of it, and its element widens by that head. `visual-layout-04` 90.1 -> 1.7.
  // An `&` overlay's PAD is the measure's own duration, not the meter's.
  // A CHORD SYMBOL'S TYPOGRAPHY: `Bb` is `B♭` and `C#` is `C♯`, and `♯` is a full em
  // where `#` is 0.556. `visual-transpose-output-01` 106.8 -> 0.25.
  // MID-TUNE NON-MUSIC LINES: a `%%text`, `%%center`, `%%sep` or `T:` between two music
  // lines is a LINE of its own, and its height is ADDITIVE to the staff separation.
  // ONE ending lane, spent ONCE: `anchorAboveStaff`'s ink call had the volta's share of
  // it and not the tuplet's, so the two disagreed about what the lane already held.
  // THE FIRST TOKEN OF A `K:` IS THE KEY ONLY WHEN IT PARSES AS ONE, uppercase A..G,
  // `HP`, `Hp` or `none` — so `K:none` keeps its treble clef, `K:C none` loses it, `K:cm`
  // is C major with nothing printed, and `K: bass` is the bass clef. Plus `clef=perc`,
  // which DRAWS and takes 26px of prefix where we drew and reserved nothing.
  // A MID-TUNE CLEF: `K:C clef=bass` and `[K: bass]` change the clef from there on, print
  // where they stand, and are reprinted at the head of every system after.
  // `[` BEFORE A DIGIT OR A QUOTE IS AN INVISIBLE BARLINE — how `[1 …` writes a repeat
  // ending with no bar before it. Lexed as a chord, `visual-layout-09` stacked seven
  // noteheads on one x.
  // A BAR THAT STARTS AN ENDING gets `minspacing += textWidth + 10`, measured in
  // `repeatfont` — 28.5 against a plain bar's 10 for a `|1`.
  // GRACE NOTES ARE EMITTED AFTER THEIR MAIN HEAD, which is abcjs's document order. The
  // gate pairs the i-th notehead, so playing order read as a position error on every
  // graced fixture — and ragtime's dy 58.1, filed for weeks as unchaseable, was this.
  // `%%musicspace` — the gap before the FIRST staff group, in points times 4/3.
  // EXPLICIT KEY ACCIDENTALS — `K: C ^/f _/B _A ^D` prints them in the signature.
  // A MID-TUNE `K: octave=` is GLOBAL, and a voice with no `octave=` of its own follows it.
  // `hasVocals` IS PER SYSTEM AND MONOTONIC — a tune whose lyrics arrive on its second
  // system engraves the FIRST with dynamics BELOW.
  // A DECORATION WRITTEN BEFORE A BARLINE ATTACHES TO THE BARLINE, at a fixed pitch 12.
  // THE MODE MAY BE ITS OWN TOKEN — `K:F# dor` and `K:D Dorian` are read across the space.
  // A MID-TUNE `[M:4/4]` PRINTS WHERE IT STANDS — a restated one prints nothing.
  // A `Q:` AFTER THE FIRST prints where it stands, on its own voice's staff.
  // TEXT IS MEASURED WITH `dump-svg.js`'s `calcWidth` — five ASCII tables picked by SIZE
  // alone and a flat 8 for every character outside them. `visual-tablature-17` was 499px
  // out on that one rule.
  // `%%jazzchords` SETS THE MODIFIER AND THE BASS AS NESTED TSPANS, and the generator
  // counts each as a whole LINE of height — `"x/C"` measures three lines and its chord
  // lane reserves 38.4px more. 38.37 -> 0.07 on that one rule.
  // EVERY DECLARED BOX IS THE PUBLISHED `h`, NOT THE DERIVED INK BOX. The G clef declares
  // 57.057px against an ink box of 57.09 and a sharp declares 20.15 against 20.19 — 0.03
  // and 0.04px, a fiftieth of a staff space each, and between them the SYSTEMIC `oy` that
  // sat under every fixture in this corpus. Eleven fixtures came off the table on it.
  // AN ENDING LANE OVER A CHORD LANE COSTS A FLAT 2 PITCH, margin included, instead of
  // `endingHeightAbove + margin` (`set-upper-and-lower-elements.js:33-38`). A different
  // BRANCH, not a scaling: 2 against a volta's 6 is 15.5px, which a ladder of five control
  // tunes put on `"D7"…|1…` and on nothing simpler.
  // A CHORD'S LANE IS ITS MEASURED HEIGHT — the golden's size table with `size + 2` for
  // anything unlisted, a whole LINE per nested tspan, and `padding * 4` when the font is
  // BOXED. `visual-tablature-17`'s five boxed `%%gchordfont` sizes were a ratio before.
  // A TUPLET'S BRACKET IS INK THE CHORD LANE SITS ON, since `layoutVoice` calls
  // `adjustRange` on every `TripletElem` before any lane is added.
  // AN ANNOTATION'S PLACEMENT DECIDES ITS RESERVE, and only two of the five take a lane:
  // `RelativeElement`'s `case "text"` gives `chordHeightAbove` when the pitch is UNDEFINED
  // (`relative-element.js:68-75`), which `above` and `below` are and `left`, `right` and
  // `@x,y` are not. A LEFT one takes `width + 7` of room before the note and a RIGHT one 4
  // either side (`add-chord.js:50-71`); an `@` takes none at all and reserves a POINT at
  // `minpitch + (y + 3 * STEP) / STEP`.
  // TWO CHORD SYMBOLS ON ONE NOTE STACK — `"D""G"d` is one name `D\nG` and each LINE is
  // its own centred mark, so it opens a second chord LANE and 18.52px of staff.
  // A REST CARRIES ITS CHORD SYMBOL AND ANNOTATIONS. abcjs runs `addChord` over every
  // abselem regardless of type, so `"Eb7"z` prints the chord and reserves the whole chord
  // lane. Ours dropped both at parse — the mark was LOST, not just mispositioned.
  // AN ANNOTATION IS LEFT-JUSTIFIED AT ITS ELEMENT where a chord symbol is CENTRED on it:
  // `getChordDim`'s `offset = type === "chord" ? realWidth / 2 : 0`, and the golden says
  // the same in one attribute — `text-anchor="start"` against `"middle"`. Centring ours
  // reached further left and opened chord LANES abcjs does not.
  // AN ADDITIVE METER IS DRAWN TERM BY TERM — `M:2+3/8` is the string `2+3` over `8`, one
  // glyph per character (`create-time-signature.js:17-27`), not the sum `5`. 17.08px.
  // `%%barnumbers` / `%%measurenb` / `%%setbarnb` — and a bar number is GEOMETRY before it
  // is text. `addMeasureNumber` puts it at pitch `vert + height / STEP` with `vert` 11 on a
  // barline and adds it with `addFixed`, so it enters the staff's ink and beats the clef's
  // 13.72 — 10.5px on a plain treble tune. Only the FIRST voice advances the counter, an
  // empty measure does not, and an invisible barline is not a boundary for counting.
  // LEADING WHITESPACE IS NOT PART OF A DIRECTIVE'S NAME — `%% barnumbers 1`.
  // A `K:` CLEF CHANGE ON ITS OWN LINE PRINTS TWICE — once at the END of the line still
  // open when the field was parsed, and again in the next system's prefix. Suppressing our
  // inline draw was half the rule; drawing it after the previous line's last barline is the
  // other half. `visual-selection-03`'s seven systems each sat 11.63px high without it.
  // EVERY FONT SITE READS ITS OWN `%%<type>font`, and four of them are geometry:
  // `measurefont` (the bar number), `annotationfont` (which abcjs picks over `gchordfont`
  // for an annotation), `partsfont` (the `P:` lane) and `voicefont` (the left edge, plus
  // the trailing "A" abcjs measures in the SAME font rather than as a constant).
  // A ROW ADVANCES BY WHICHEVER FIELD MOVES IT: the rhythm is given `noMove` whenever a
  // composer or origin is present, so `composerfont` alone sets that row and not the taller
  // of the two. And a BOXED font's `padding * 4` is in every MEASURED height —
  // `getTextSize.calc` adds it, so a mid-tune `%%text` and `T:` carry it too.
  // …AND THE BOX IS ON THE WIDTH TOO, which is a chord's `realWidth`: how far a centred
  // mark reaches either side of its note and where `placeInLane` puts its right edge.
  // `visual-tablature-17` boxes five `%%gchordfont` sizes and was 33.9px of dx out on it.
  // AN ARPEGGIO IS A STACK reaching twice its own width back from the note, past the
  // accidentals; a FINGERING DIGIT is a TEXT decoration, not a glyph; and ABCJS NEVER
  // APPLIES A GLYPH'S SCALE AT DRAW TIME — `printSymbol` takes `scalex`/`scaley` and
  // passes neither on, under its own "what happened to scalex, and scaley?" comment. So a
  // grace notehead draws FULL SIZE while its position is computed from the scaled width.
  // A GRACE NOTE ADDS 10 TO `roomtaken` and an accidental on it 7 more, and everything
  // placed AFTER the graces starts from that total — the arpeggio and a LEFT annotation
  // both. `roomtaken += addGraceNotes(…, roomtaken)` also counts the accidental room
  // TWICE, which is an abcjs bug and is reproduced.
  // `V:… stem=up` IS THE SAME AS `stems=up` — abcjs's switch takes both spellings
  // (`abc_parse_key_voice.js:717-718`) and we matched only the plural, which left a
  // percussion voice stemming by pitch and its staff 11.63px short.
  // AN INVERTED FERMATA HANGS UNDER THE NOTE whatever the tune says: abcjs's switch passes
  // the literal `'below'` where every other ornament passes `positioning` through
  // (`decoration.js:261-264`), and there is a `yPos.below` cursor for exactly that.
  // A BEAM'S DIRECTION IS THE MEAN OF ITS NOTES' AVERAGE PITCHES against the middle line,
  // not whichever EXTREME lies further from it (`beam-element.js:54-66,89-98`). The two
  // agree on a compact run and part the moment one note is an outlier — `"E"e"F"F"F#"^F"G"G`
  // averages 4.75 and beams UP where its extremes are symmetric and beamed DOWN. 16.52px.
  // A PERCUSSION VOICE PRINTS NO ACCIDENTALS — `createNote` passes
  // `printAccidentals: !voice.isPercussion` (`abstract-engraver.js:723`), so `^c'` on a
  // `clef=perc` staff draws its head and nothing else. Ours drew one and reserved its
  // declared box: 7.18px of staff above a high note.
  // `%%percmap <abc-note> <drum-sound> <note-head>` gives a written pitch its own HEAD on a
  // percussion staff, looked up through `pitchesToPerc`'s sixteen-entry table.
  // `abselem.extraw` IS A RUNNING MIN WITH A SUBTRACTION BETWEEN THE STEPS, not a sum:
  // `addExtra` mins the accidental's dx into it and `extraw -= extraLeft` follows, PER
  // PITCH — so a deeper column on the next pitch resets the min and throws the previous
  // subtraction away. `[_d^f=b]` ends at `deepest - nat/2`, and summing cost 7.50px.
  // EMISSION PRECISION IS A PARITY TERM. Our coordinates are a nested chain — system
  // translate, staff translate, element offset, viewBox — each quantised, with the errors
  // ADDING, where abcjs writes one absolute pixel per element. A thousandth of a staff
  // space put a notehead up to 5.1e-3px out; a hundred-thousandth reaches 1.5e-4, which is
  // the floor. And a glyph SCALE is a ratio, not a coordinate: rounding `1 / 7.75` to
  // `0.129` was a relative error over the whole outline.
  // A STEM IS NOT ANCHORED TO THE FONT, and a BEAMED one is a different object entirely.
  // abcjs hangs the quad off the notehead's declared EDGE — `heads[0].w` with `linewidth
  // ±1` — where we took Bravura's `stemUpSE`/`stemDownNW` anchors, 0.169px out going up and
  // 0.494 going down. Then `createStems` throws that stem away for anything beamed and
  // builds its own: `±0.6` thick, `±1/5` of a pitch inside the head rather than `±1/3`, and
  // honouring the head's displacement where the unbeamed one ignores it. The beam's ENDS
  // are a third construction — `calcXPos` insets the start by 0.6 going up and extends the
  // end by 0.6 coming down — and `getBarYAt` interpolates every stem's endpoint along the
  // line they define, so a purely horizontal error there is a vertical one on every slant.
  // A FLAG is a fourth: `headx + w - 0.6`, not the stem it hangs beside, and its `x` feeds
  // the element's ROD, so riding it on the stem moved noteheads.
  // A GRACE GROUP OF MORE THAN ONE IS BEAMED, AND A BEAMED GRACE RESERVES NOTHING. The
  // three facts, each measured off a ladder of control tunes before any of it was written:
  // the stem runs from the head's PITCH twice over (`+1/3 * gracescale` and
  // `+7 * gracescale`) rather than a length up from its own base; the head reserves its
  // DECLARED box times the grace scale, centred on the pitch; and a beamed group's stems
  // and beam are built in `createStems` during LAYOUT, after `staff.top` has been taken, so
  // they push `abselem.top` and never reach the staff. abcjs's top line is identical for
  // `CD`, `{efg}CD` and `{ef}ag` — the G clef's 13.72 pitch sets it — while `{c''}CD` moves
  // it 44.5px and `{c''d''}CD` only 34.5. TWO GRACES RESERVING LESS THAN ONE is the tell,
  // and it is a PHASE difference, not a size one.
  // Plus `graceoffsets`, which is a BACKWARD walk: an accidental widens the gap before its
  // own grace, so `{e^fg}` is 7px wider than running forward at a flat 10 per note.
  // AND A REST CARRIES ITS GRACES, by the line that gives it a chord symbol: `createNote`
  // closes its rest/note branch and THEN calls `addGraceNotes`. `(f3 {a})y` was a whole
  // notehead short — the last CONTENT gap but one — and the `25` bucket moved with it,
  // which no geometric fix had managed.
  // `%%setfont-N` AND `$N`, AND A ROW THAT CHANGES FONT MID-LINE ADVANCES BY A DIFFERENT
  // RULE. `addTextIf` moves a plain row by `Math.round(size.height * 1.1)`; `richText`
  // moves a phrase row by `largestY`, the tallest phrase's RAW height, with no 1.1 and no
  // rounding — so a title row is 33 against 29.91 and a composer row 23 against 21.06.
  // A phrase's own font is measured at its RAW size too: `getTextSize.calc` applies the
  // `pt -> px` 4/3 only when handed a font by NAME, never when handed a font OBJECT, which
  // is what a `%%setfont` is.
  // AND `\n` IS A LINE BREAK INSIDE A QUOTED CHORD — `substInChord`, not the accent
  // machinery, which leaves an unknown escape's backslash alone. `"C$1m$7\ntwo"` was one
  // line reading `C$1m$7ntwo`: one chord lane where abcjs takes two, and a mark four
  // characters too wide. All four of `visual-misc-06`'s axes were that one chord.
  // A GRACE CARRIES ITS ACCIDENTAL — the ROOM was reserved and the GLYPH never drawn, a
  // gap no gate could see because the notehead count is right either way and an accidental
  // is not a notehead. It is also what the element reaches LEFT by: `extraw` is a running
  // MIN over every `addExtra` child and `addCentered` mins a chord symbol's own
  // `-width / 2` into the same number, so on `"Bb"{^C}B,4` the sharp's -16.95 beats the
  // chord's -13.34. That is why it only ever showed where BOTH were present — four rungs
  // of five were green — and why the ranked table's `[%%sep, %%text]` directives column
  // named the wrong thing entirely.
  // `%%vocalfont` IS REALIZED, AND STRICT REALIZES IT TOO — the mode-split row saying
  // "abcjs parses it and never draws it" was reasoned from the source and its own SVG
  // denies it: the same tune draws its lyric at `font-size="17"` with no directive, `13`
  // under `%%vocalfont Helvetica 10.0` and `27` under `20.0`. Its granularity is the music
  // LINE, because `%%vocalfont` is a CHANGING font that reaches the drawing through the
  // STAFF (`params.vocalfont` -> `getTextSize.updateFonts(abcstaff)`), which is why Gonzato's
  // fixture — all of its music BEFORE all of its directives — draws every syllable at the
  // default however many `%%vocalfont` lines follow.
  // The lane and the baseline both follow the font: the baseline sits one FONT SIZE below
  // the lane top, and `17` was standing in for it because 17 is BOTH `spacing.vocal` and
  // the default vocalfont's drawn size. And `box` is not legal on `vocalfont` at all —
  // `fontTypeCanHaveBox` lists eleven types and that is not one of them.
  //
  // FOUR FIXTURES MOVED, NET −5.28px: `visual-selection-01` and `svg-per-line-01` 6.65 ->
  // 4.01 each, `visual-options-01-fonts` 1.43 -> 2.01, and `visual-multi-voice-02` 0.00 ->
  // 0.05 — the last a pure 0.05px OFFSET sitting exactly on the bucket boundary, which is
  // why `0.05` goes DOWN by one here while `5` goes up by two. Recorded rather than
  // rounded away; both residuals are named and neither is masked.
  // A QUARTER TONE IN A KEY SIGNATURE HAS A FUDGE OF ITS OWN. `createKeySignature`
  // switches on five accidentals and ours knew three: `quartersharp` is -2.5 and
  // `quarterflat` -1.2 (`create-key-signature.js:17-23`). Missing, they fell to the `?? 0`
  // default, and 2.5 pitch of phantom staff is `synth-flattener-32`'s entire 5.74px — its
  // other three axes were already at zero, and `K: C _A ^D` with plain accidentals was
  // exact beside it.
  //
  // `5` now equals `25`: ONE fixture in 174 is outside five pixels, and it is the tune-count
  // mismatch that has no geometry to measure.
  // A LYRIC'S BASELINE FLOORED AT THE DEFAULT SIZE. `Math.max(default, …sizes)` reads as
  // "the largest font on this part" and is a FLOOR: a `%%vocalfont` SMALLER than the
  // default drew at its own size and measured its baseline at 17. `visual-selection-01`'s
  // last 4.01px, and three more fixtures with it.
  // …AND THE CHORD LANE HAD THE SAME CLAMP, TWICE. `chordSize` and `chordBlock` both read
  // `Math.max(default, …)`, which is a floor: `%%gchordfont Arial 10 box` resolves to 13px
  // and had its lane measured at the 12pt default's 16. Three pixels, and
  // `visual-tablature-17`'s whole `oy` — while the same fixture's 20, 40, 80 and 130 were
  // already exact, which is what a floor looks like and an arithmetic error does not.
  // `M:C` AND `M:C|` ARE ONE GLYPH, not the digits they stand for. `createTimeSignature`
  // branches on `elem.type` and draws `timesig.common` / `timesig.cut` at pitch 6
  // (`create-time-signature.js:35-40`); we drew `4/4` and `2/2`. It is a PREFIX width, so
  // every note on every line moved with it — `M:C` measured 1.24px narrow and `M:C|` 2.27,
  // uniform on both, which is `ox` with no `dx` and the signature of a prefix rather than a
  // spacing rule. The same meters written as digits were exact throughout, which is what
  // said the arithmetic was fine and the GLYPH was missing.
  // AN AUGMENTATION DOT HAS ITS OWN ARITHMETIC, and it is stated from the head's ORIGIN:
  // `notehead.w + dotshiftx - 2 + 5 * dot` (`create-note-head.js:50-53`). So the first dot
  // sits `w + 3` out and each further one 5px past it, where ours used a 0.35-space gap and
  // a 0.45-space step — 2.71 and 3.49px against 3 and 5. And the ROD is the LAST dot's
  // right edge plus one dot's width, not the count times the step: getting that wrong put
  // 1.5px of phantom rod on every dotted note and cost `happy-birthday` 1.8px of spread
  // before it was caught.
  //
  // 2026-08-06, and it moved SEVEN fixtures at once — the largest single step of the arc.
  // abcjs performs EIGHT layouts and throws away the spacing it solves from the eighth
  // (`layout/layout.js:68-75`): the loop simply ends, so it renders at the spacing that
  // produced its last layout rather than at the one it just computed. Instrumented, its
  // own trace never converges at all — eight passes taking 964.55px down to 696.24
  // against a 685 target, with 12.053 discarded and 12.454 standing. We ran the same
  // eight passes and then rendered with the ninth value, one refinement further in, which
  // made every line slightly NARROWER than abcjs's. `visual-layout-04`, `mouse-click-01`,
  // `tablature-15`, `selection-01`, `svg-per-line-01`, `transpose-05` and `wrap-01` all
  // went exact on it.
  //
  // …and the same day, `Z24`. A MULTI-MEASURE REST ADVANCES THE BAR COUNTER BY ITS WHOLE
  // COUNT — `currBarNumber += core.rest.text - 1` (`abc_parse_music.js:512`), the minus
  // one being the barline that closes the rest's own measure. Ours counted `Z24` as one
  // measure, so `%%barnumbers 5` printed a number where abcjs prints none and the reserve
  // for it pushed the whole staff down 1.68px. Instrumented: abcjs reaches `curr=47` at
  // the first barline where we reached 24.
  //
  // **`1: 173` IS EVERY MEASURABLE FIXTURE** — the 174th is the leading-header tune-count
  // mismatch, which has no geometry to compare.
  //
  // A CHORD SYMBOL WRITTEN BEFORE A BARLINE BELONGS TO THE BARLINE, exactly as a
  // decoration does and by the two lines after it: `if (el.chord !== undefined) bar.chord
  // = el.chord`, then `el = {}` (`abc_parse_music.js:288-289, 305`). `createBarLine` ends
  // by running the same `addChord` a note gets at `noteheadWidth = 0`
  // (`abstract-engraver.js:1047-1049`), so the mark is CENTRED on the bar and
  // `addCentered` gives it `w = chordWidth / 2` against a bare barline's 1 — abcjs
  // measures `"D"|` at 5.781. `"D"|` is how a downbeat chord change is normally written,
  // and carrying it to the next note put our mark 15.8px right of abcjs's and every
  // notehead on the line 0.93px out. `transpose-output-03` went exact; `-04` kept only
  // its `oy`.
  //
  // …AND A NOTE'S GRACE STEMS ARE PART OF THE `abselem.top` A DECORATION STACKS ON.
  // `createDecoration` is handed `abselem.top` (`abstract-engraver.js:842`) with
  // `addGraceNotes` already run four lines above it, so an UNBEAMED grace's stem and flag
  // set that top: `{c}+1+B` probes at 11.2, the grace's flag exactly, against the main
  // head's 7.04. A BEAMED group is the exception by the same phase argument that keeps it
  // out of the staff extent — `createStems` builds those during layout. It bites only
  // through `decorationMinTop`'s clamp of 12, which is why one tune of a transposed pair
  // showed it and the other could not: 11.2 clamps to 12 and 12.2 does not. 0.775px under
  // every notehead on `transpose-output-04`, and both of that pair are now exact.
  //
  // A REST'S CHORD SYMBOL IS CENTRED ON THE ELEMENT, NOT ON THE REST GLYPH. `createNote`
  // declares `symbolWidth = 0` and assigns it only in the NOTE arm
  // (`abstract-engraver.js:784, 827`), so the `noteheadWidth` reaching `addChord` on a rest
  // is a flat zero and `addCentered` gets `dx = 0` where a note gets half a head. abcjs's
  // own SVG centres `"Eb7"z`'s chord at 109.84 — the rest's x — and probes the element at
  // `w = 17.789`, exactly half the chord. 0.53px under every notehead after it.
  //
  // FOUR OF ABCJS'S NOTEHEADS WERE NEVER IN OUR COPY OF ITS GLYPH TABLE, and a name it
  // does not hold falls through to Bravura in strict — the defect class the Bravura
  // ruling closes. Not abcjs's absence but our GENERATOR's: abcjs closes its table
  // literal and then adds `noteheads.slash.whole`, `.slash.quarter`, `.harmonic.quarter`
  // and `.triangle.quarter` by assignment under "Custom characters that weren't generated
  // from the font", and the generator sliced to the literal's `};`. Those four are every
  // STYLED head — exactly what `%%percmap` and `V:… style=` reach.
  //
  // …AND A NOTEHEAD RESERVES ITS DECLARED BOX CENTRED ON THE PITCH, `pitch ± thickness/2`
  // from `symbolHeightInPitches` (`create-note-head.js:34`), not the glyph's INK box,
  // which is what the scan falls back to when no reserve is set. The round heads hid it —
  // `noteheads.quarter` inks [-4.08, +4.05] against a declared ±4.047 — and the styled
  // ones do not: the triangle inks [-5, +4] against ±4.5, half a pixel of reserve too
  // tall on one side and too short on the other.
  //
  // Together they took four fixtures off the table at once: both `percmap` ones,
  // `visual-wrap-04` and `visual-multi-voice-02`. Only two entries are left with any
  // geometry, and neither is above 0.18px.
  //
  // A BEAMED NOTE HAS NO STEM YET WHEN ITS DECORATIONS ARE PLACED, and abcjs guesses the
  // one it will get: `var bottom = nostem && dir !== 'up' ? Math.min(-3, abselem.bottom -
  // 6) : abselem.bottom` (`abstract-engraver.js:841`). A flat 6-pitch drop with a FLOOR at
  // pitch -3 — neither figure the stem's real end, and no matching term on the ABOVE side,
  // which takes `abselem.top` raw. Ours read the real beamed stem on both sides, which is
  // 0.175px of staff wherever a `!invertedfermata!` hangs off that cursor.
  //
  // A REST MOVES OFF THE MIDDLE LINE WHEN IT SHARES A STAFF, and reserves its DECLARED box
  // like a notehead. `if (isMultiVoice) { if (stemdir === 'down') restpitch = 3; if
  // (stemdir === 'up') restpitch = 11 }` from a default 7 (`abstract-engraver.js:544-551`),
  // and `restpitch` is one variable: `createNoteHead(abselem, c, { verticalPos: restpitch
  // })` both draws the glyph and centres the `pitch ± thickness / 2` box on it. Ours drew
  // every rest on the default line and reserved the glyph's INK box — `rests.quarter` inks
  // 11.88px up and 9.6 down around a declared ±10.72, so it read 3.066 pitch above its
  // anchor against abcjs's 2.766.
  //
  // A LEADING CHUNK BEFORE THE FIRST `X:` IS NOT A TUNE. `bookParser` splits on `"\nX:"`
  // and shifts the first piece off when it does not start with `X:`, keeping only its
  // `%%` lines (`abc_parse_book.js:12-33`). That was the last CONTENT gap, and closing it
  // made the 174th fixture measurable for the first time.
  //
  // **178 OF 178, ON EVERY THRESHOLD.** The whole harvested corpus agrees with abcjs on
  // note content and on all four geometric axes to within 0.05px. The ranked table is
  // EMPTY — it prints no rows at all — so it can no longer name anything, and the gates
  // that remain are regression nets rather than instruments. See
  // `Docs/CHECKPOINT-2026-08-06b.md` for what that means for finding the next defect.
  //
  // **THE LAST THREE ARE OURS, NOT abcjs's** — `abcts-vskip.abc`, `abcts-keywarn.abc` and
  // `abcts-visualtranspose.abc`, CONTROLS written on
  // 2026-08-15 for a directive that appears in abcjs's own tests and in NEITHER corpus.
  // Its goldens come from running abcjs 6.7.0 like every other row here, so it is measured
  // the same way; only its INPUT was chosen by us. That is the pattern this branch has
  // used for every feature no fixture exercised.
  //
  // …and `abcts-slur-shapes.abc`, `abcts-model-gaps.abc` and `abcts-ledger-gaps.abc` are
  // three more of them — and the `abcts-ledger-gaps` pair plus `-3` are three FIXTURES of
  // the same kind: every tune is a shape a `ponytail:` had named and declared unwritten by
  // either corpus. Three of the first six were real defects, five of the second eight, and
  // five of the third eight, and NONE of the fourth six — which is the other honest
  // outcome of the pattern: six more entries are measurements now rather than predictions.
  // All twenty-eight tunes are byte-exact.
  //
  // …and `abcts-decorations.abc` is the same pattern applied to abcjs's DECORATION tables:
  // all 96 names rendered through both engines, three of them wrong. Its six tunes are
  // byte-exact, which is the one row that takes each count from 185 to 186.
  //
  // …and `abcts-last-bar.abc` is the 187th — `checkLastBarX`, which that enumeration's own
  // control found before any modifier did, and `abcts-voice-modifiers.abc` the 188th —
  // the three defects the modifiers themselves found. `abcts-midi.abc` is the 189th — 56
  // tunes, one per `%%MIDI` sub-command, none of which moves a note, and
  // `abcts-voice-style.abc` the 190th, `abcts-key-modifiers.abc` the 191st and
  // `abcts-start-char.abc` — abcjs's own test tune — the 192nd.
  //
  // …and SIXTEEN more of abcjs's OWN test inputs, the ones its harvester never took: four
  // `tie-slur` files and twelve tunes counted out of `multi-voice`, `parsing`, `misc`,
  // `decorations` and `directives` by comparing each file's `var abc` declarations against
  // the fixtures already here. Every one byte-exact on arrival.
  // …and three more from `tests/synth/`, which that sweep did not cover.
  // …and `abcts-tempo-rung.abc`, the tempo ULP's own fixture.
  // …and `abcjs-visual-parsing-x10` joins them: the key signature's own width was `dx`
  // less the trailing gap where abcjs takes the last child's BUILT right edge.
  // …and `abcts-positioning.abc`, the five `positionChoices` directives, whose eight tunes
  // are exact on all four axes on arrival — see `tests/positioning.test.ts`.
  // …and `abcts-voice-scale.abc`, `V:… scale=`/`cue=`, whose twelve are too — ONCE THE
  // PAIRING ABOVE WAS NUMERIC. It is the first fixture here with more than ten tunes that
  // renders them differently, and it read dy 42.6 against goldens it was byte-identical to.
  // …and `abcts-pitch-style.abc`, the per-PITCH `!style=…!`, whose eight are exact on all
  // four axes ON ARRIVAL — the three defects it named are byte-level and move no notehead
  // centre at all: an up-stem's x, a ledger's width and the ORDER two curves go out in.
  // …and `abcts-rests-and-bars.abc`, a sweep of shapes neither corpus writes. FOUR of its
  // eight are open rows, each with abcjs's own numbers in the fixture's own note.
  // …and `abcts-endings.abc`, what `letter_to_bar` reads past a barline — all eight
  // byte-exact. ⚠️ Its last row was written up TWICE as "our lexer calls that `[` a
  // barline", and the lexer does no such thing: it matches abcjs exactly (a bare `[` is a
  // bar only before `|`, `1`-`9` or `"`). Reading the rule beside the code would have said
  // so; the row was three defects of its own, and none of them was the lexer.
  // …and `abcts-grace-tie.abc`, the `-` INSIDE a grace group — exact on all four axes
  // once the ACCIACCATURA SLASH declared its own box, which is one of the three defects
  // its tie-free controls named.
  // …and `abcts-clef-midmeasure.abc`, an inline `[K: … clef=]` written INSIDE a measure.
  // Three defects: `layoutMeasure` was handed the already-advanced clef so the whole bar
  // was pitched in the new one; `beamDirections` read the VOICE's clef where abcjs reads
  // the one in force at the note; and a line opens in the RUNNING clef, which leaks across
  // voices — `startNewLine`'s `staves[n].clef ?? multilineVars.clef`.
  // …and `abcts-lyric-verses.abc`, `w:` lines that do NOT cover every note.
  // …and `abcts-inline-fields-and-blocks.abc`, the mid-measure `[Q:]`, the left/right
  // annotations and the `%%begintext` block before the music.
  // …and `abcts-stafflines-and-modifiers.abc`, a 36-shape sweep over untouched territory
  // plus the three ladders that closed what it found.
  // …and `abcts-bars-graces-and-groups.abc`, a second 36-shape sweep.
  // …and `abcts-void-notes-and-stray-ties.abc`, the ladder that closed the warnings gate,
  // and `abcts-text-udef-parts-overlays.abc`, the third sweep — which reached ZERO on every
  // axis the day the in-system trailing block closed.
  "0.05": 226,
  "1": 226,
  "5": 226,
  "25": 226,
};

const names = readdirSync(fixturesDir)
  .filter((f) => f.endsWith(".abc"))
  .map((f) => f.replace(/\.abc$/, ""))
  .sort();

const goldens = readdirSync(goldenDir);

/**
 * abcjs writes one SVG per tune, `<name>.svg` alone or `<name>-tuneN.svg` for a book.
 *
 * ⚠️ **AND THE ORDER IS NUMERIC, NOT LEXICOGRAPHIC.** A plain `.sort()` puts `-tune10`
 * between `-tune1` and `-tune2`, so every tune from the tenth on is compared against the
 * WRONG golden. It read zero for months because no fixture with more than ten tunes
 * rendered them differently: `abcts-midi.abc` has fifty-six and not one `%%MIDI`
 * sub-command moves the drawing, so mis-pairing them is invisible by construction.
 * `abcts-voice-scale` is the first where it shows — twelve tunes at four different scales,
 * BYTE-IDENTICAL on `svg-bytes` and reported here at dy 42.6.
 *
 * **A GATE'S REACH IS A PROPERTY OF ITS ENUMERATION**, and so is its PAIRING.
 */
const tuneIndex = (file: string): number =>
  Number(/-tune(\d+)\.svg$/.exec(file)?.[1] ?? -1);
const goldensFor = (name: string): string[] =>
  existsSync(join(goldenDir, `${name}.svg`))
    ? [`${name}.svg`]
    : goldens
        .filter((g) => g.startsWith(`${name}-tune`))
        .sort((a, b) => tuneIndex(a) - tuneIndex(b));

interface Measured {
  ourHeads: number;
  goldenHeads: number;
  dy: number;
  dx: number;
  oy: number;
  ox: number;
}

function measure(name: string): Measured {
  const abc = readFileSync(join(fixturesDir, `${name}.abc`), "utf-8");
  const files = goldensFor(name);
  // The goldens' own `{staffwidth: 670}` — abcjs's default is 740 on screen.
  const ours = renderAll(abc, { staffwidth: 670 });
  if (ours.length !== files.length) {
    return {
      ourHeads: -ours.length,
      goldenHeads: -files.length,
      dy: 0,
      dx: 0,
      oy: 0,
      ox: 0,
    };
  }
  let goldenHeads = 0;
  let ourHeads = 0;
  let dy = 0;
  let dx = 0;
  let sumY = 0;
  let sumX = 0;
  let paired = 0;
  files.forEach((file, i) => {
    const g = byClass(
      absolutePixels(readFileSync(join(goldenDir, file), "utf-8")),
      "notehead",
    );
    const o = byClass(absolutePixels(ours[i]?.svg ?? ""), "notehead");
    goldenHeads += g.length;
    ourHeads += o.length;
    const n = Math.min(g.length, o.length);
    const deltas = (axis: "x" | "y"): number[] =>
      g.slice(0, n).map((head, k) => (o[k]?.[axis] ?? 0) - head[axis]);
    const spread = (v: number[]): number =>
      v.length === 0 ? 0 : Math.max(...v) - Math.min(...v);
    dy = Math.max(dy, spread(deltas("y")));
    dx = Math.max(dx, spread(deltas("x")));
    sumY += deltas("y").reduce((a, b) => a + b, 0);
    sumX += deltas("x").reduce((a, b) => a + b, 0);
    paired += n;
  });
  return {
    ourHeads,
    goldenHeads,
    dy,
    dx,
    oy: paired === 0 ? 0 : sumY / paired,
    ox: paired === 0 ? 0 : sumX / paired,
  };
}

describe("abcjs test-suite corpus", () => {
  it("the harvest and its goldens are in step", () => {
    expect(names.length).toBeGreaterThan(150);
    // A fixture without a golden would be silently unmeasured, which is the shape of
    // every gate bug this repo has recorded.
    expect(names.filter((n) => goldensFor(n).length === 0)).toEqual([]);
  });

  describe("nothing throws", () => {
    for (const name of names) {
      it(`${name}`, () => {
        const abc = readFileSync(join(fixturesDir, `${name}.abc`), "utf-8");
        const result = parse(abc);
        expect(result.ok).toBe(true);
        const rendered = renderAll(abc, { staffwidth: 670 });
        expect(rendered.length).toBeGreaterThan(0);
        for (const tune of rendered) expect(tune.svg).toContain("<svg");
      });
    }
  });

  it("notehead counts match abcjs, except where a gap is recorded", () => {
    const mismatched: string[] = [];
    for (const name of names) {
      const { ourHeads, goldenHeads } = measure(name);
      if (ourHeads !== goldenHeads) mismatched.push(name);
    }
    // Both directions: a new mismatch is a regression, and a fixed one means the list
    // above is stale. Neither is allowed to pass quietly.
    expect(mismatched.sort()).toEqual(Object.keys(CONTENT_GAPS).sort());
  });

    it("geometry does not regress", () => {
    const scores = names
      .filter((n) => CONTENT_GAPS[n] === undefined)
      .map((n) => {
        const m = measure(n);
        return Math.max(m.dy, m.dx, Math.abs(m.oy), Math.abs(m.ox));
      });
    const summary: Record<string, number> = {};
    for (const key of Object.keys(WITHIN)) {
      summary[key] = scores.filter((s) => s < Number.parseFloat(key)).length;
    }
    // A ratchet: only up. An improvement must be RECORDED, or the number drifts away
    // from reality and stops meaning anything.
    expect(summary).toEqual(WITHIN);
  });
});
