/**
 * THE ABCJS TEST-SUITE CORPUS — 174 tunes abcjs's own maintainers chose to test.
 *
 * ── WHY THIS EXISTS ─────────────────────────────────────────────────────────
 * The 41-fixture corpus is the gate everything else runs against, and it is OUR idea of
 * what is worth exercising. abcjs's `tests/` is ITS authors' idea, and the two are not
 * the same coverage — nothing in the 41 uses `%%stretchlast`, `%%maxStaves`, a zero-length
 * note, or a voice overlay that crosses a barline, and abcjs tests all four.
 *
 * The tunes are harvested by `scripts/harvest-abcjs-tests.mjs` and their goldens
 * generated by running abcjs itself (`scripts/harvest-abcjs-goldens.mjs`). Its 272 `it()`
 * cases are NOT ported: they assert against abcjs's internal `visualObj` tree, which
 * `abcts/compat` does not reproduce. The inputs transfer; the assertions do not.
 *
 * ── WHAT IS ASSERTED, AND WHY NOT 174 CEILINGS ──────────────────────────────
 * Three things, in the order they matter:
 *
 *  1. NOTHING THROWS. 174 tunes from someone else's test suite is the best fuzz corpus in
 *     the repo, and this is the assertion that has to stay flat at 100%.
 *  2. NOTEHEAD COUNTS, per fixture, against a named list of the ones that do not match.
 *     Those names are the CONTENT gaps and each is a bug with a cause recorded below. A
 *     new name failing means a regression; an old one passing means the list is stale and
 *     must be shortened — the same ratchet the pixel gate uses.
 *  3. GEOMETRY IN AGGREGATE — how many fixtures land within a threshold, not a ceiling
 *     each. 174 individual numbers would be noise nobody reads and a merge conflict every
 *     time; the counts move only when something real changes, and they only go up.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { renderAbc } from '../src/compat/index.js'
import { parse } from '../src/parser/parser.js'
import { absolutePixels, byClass } from './pixel-geometry.js'

const base = join(dirname(fileURLToPath(import.meta.url)), 'corpus-abcjs')
const fixturesDir = join(base, 'fixtures')
const goldenDir = join(base, 'golden')

/**
 * Fixtures whose notehead count does not match abcjs's, and WHY.
 *
 * Every one is a real gap found by this corpus and by nothing else in the repo.
 */
const CONTENT_GAPS: Readonly<Record<string, string>> = {
  // `(f3 {a})y` — the grace attaches to the `y` SPACER that follows it, and `Rest` has
  // no `graceNotes` field, so the parser drops it. The model says so deliberately: "a
  // rest does carry decorations — but not ties, slurs, grace notes or lyrics, none of
  // which apply to silence". abcjs disagrees for a spacer, which is a layout device
  // rather than silence, and draws the grace with its own stem, flag and ledger.
  // A MODEL DECISION, not a mechanical fix — see the checkpoint.
  'abcjs-visual-tablature-10-f3-a-y': 'a grace note before a `y` spacer is dropped at parse',
  // `%% example / T: wed / %%example / X:1` — a `T:` standing before any `X:`. abcjs
  // keeps the leading block as part of the first tune; we split it off as a tune of its
  // own, so the book has two where abcjs has one.
  'abcjs-parse-book_parser-04-wed': 'a header block before the first X: splits the book',
}

/**
 * How many fixtures land within each threshold, on all four axes at once.
 *
 * A RATCHET, like the pixel gate's ceilings: these may only go up, and a run that
 * improves one has to record it. They are counts rather than per-fixture numbers because
 * 174 ceilings is a table nobody reads — see the header.
 */
const WITHIN: Readonly<Record<string, number>> = {
  // 72 / 83 / 91 / 116 before four fixes only this gate could see, since no 41-fixture
  // exercises any of them: `clef=none` and `clef=perc` being read as a C clef on the
  // middle line, `%%text` / `%%begintext` reserving nothing, `V:… merge` unimplemented,
  // and a clef name matched as a whole word rather than by prefix, so `bass,,` was no
  // clef at all.
  '0.05': 79,
  '1': 90,
  '5': 97,
  '25': 120,
}

const names = readdirSync(fixturesDir)
  .filter((f) => f.endsWith('.abc'))
  .map((f) => f.replace(/\.abc$/, ''))
  .sort()

const goldens = readdirSync(goldenDir)

/** abcjs writes one SVG per tune, `<name>.svg` alone or `<name>-tuneN.svg` for a book. */
const goldensFor = (name: string): string[] =>
  existsSync(join(goldenDir, `${name}.svg`))
    ? [`${name}.svg`]
    : goldens.filter((g) => g.startsWith(`${name}-tune`)).sort()

interface Measured {
  ourHeads: number
  goldenHeads: number
  dy: number
  dx: number
  oy: number
  ox: number
}

function measure(name: string): Measured {
  const abc = readFileSync(join(fixturesDir, `${name}.abc`), 'utf-8')
  const files = goldensFor(name)
  const ours = renderAbc('paper', abc, {})
  if (ours.length !== files.length) {
    return { ourHeads: -ours.length, goldenHeads: -files.length, dy: 0, dx: 0, oy: 0, ox: 0 }
  }
  let goldenHeads = 0
  let ourHeads = 0
  let dy = 0
  let dx = 0
  let sumY = 0
  let sumX = 0
  let paired = 0
  files.forEach((file, i) => {
    const g = byClass(absolutePixels(readFileSync(join(goldenDir, file), 'utf-8')), 'notehead')
    const o = byClass(absolutePixels(ours[i]?.svg ?? ''), 'notehead')
    goldenHeads += g.length
    ourHeads += o.length
    const n = Math.min(g.length, o.length)
    const deltas = (axis: 'x' | 'y'): number[] =>
      g.slice(0, n).map((head, k) => (o[k]?.[axis] ?? 0) - head[axis])
    const spread = (v: number[]): number => (v.length === 0 ? 0 : Math.max(...v) - Math.min(...v))
    dy = Math.max(dy, spread(deltas('y')))
    dx = Math.max(dx, spread(deltas('x')))
    sumY += deltas('y').reduce((a, b) => a + b, 0)
    sumX += deltas('x').reduce((a, b) => a + b, 0)
    paired += n
  })
  return {
    ourHeads,
    goldenHeads,
    dy,
    dx,
    oy: paired === 0 ? 0 : sumY / paired,
    ox: paired === 0 ? 0 : sumX / paired,
  }
}

describe('abcjs test-suite corpus', () => {
  it('the harvest and its goldens are in step', () => {
    expect(names.length).toBeGreaterThan(150)
    // A fixture without a golden would be silently unmeasured, which is the shape of
    // every gate bug this repo has recorded.
    expect(names.filter((n) => goldensFor(n).length === 0)).toEqual([])
  })

  describe('nothing throws', () => {
    for (const name of names) {
      it(`${name}`, () => {
        const abc = readFileSync(join(fixturesDir, `${name}.abc`), 'utf-8')
        const result = parse(abc)
        expect(result.ok).toBe(true)
        const rendered = renderAbc('paper', abc, {})
        expect(rendered.length).toBeGreaterThan(0)
        for (const tune of rendered) expect(tune.svg).toContain('<svg')
      })
    }
  })

  it('notehead counts match abcjs, except where a gap is recorded', () => {
    const mismatched: string[] = []
    for (const name of names) {
      const { ourHeads, goldenHeads } = measure(name)
      if (ourHeads !== goldenHeads) mismatched.push(name)
    }
    // Both directions: a new mismatch is a regression, and a fixed one means the list
    // above is stale. Neither is allowed to pass quietly.
    expect(mismatched.sort()).toEqual(Object.keys(CONTENT_GAPS).sort())
  })

  it('geometry does not regress', () => {
    const scores = names
      .filter((n) => CONTENT_GAPS[n] === undefined)
      .map((n) => {
        const m = measure(n)
        return Math.max(m.dy, m.dx, Math.abs(m.oy), Math.abs(m.ox))
      })
    const summary: Record<string, number> = {}
    for (const key of Object.keys(WITHIN)) {
      summary[key] = scores.filter((s) => s < Number.parseFloat(key)).length
    }
    // A ratchet: only up. An improvement must be RECORDED, or the number drifts away
    // from reality and stops meaning anything.
    expect(summary).toEqual(WITHIN)
  })
})
