import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { parseOnly } from "../src/compat/index.js";
import { CreateSynth, playEvent, soundsCache } from "../src/compat/create-synth.js";
import { registerAudioContext } from "../src/compat/synth.js";
import { installRecorder } from "./audio-recorder.js";
import {
  CASES,
  drive,
  driveErrors,
  drivePlayEvent,
  ERROR_CASES,
  FIXTURES,
  PLAY_EVENT_CASES,
  type Step,
  type SynthLike,
} from "./create-synth-script.js";

/**
 * **`CreateSynth` — THE ONE THAT MAKES THE SOUND, GATED WITHOUT A SPEAKER.**
 *
 * The oracle is `tests/corpus-create-synth/golden.json`, generated by RUNNING abcjs 6.7.0
 * with the same recorder this file installs (`scripts/harvest-abcjs-create-synth.ts`).
 *
 * **NO WAVEFORM IS COMPUTED BY EITHER SIDE.** `CreateSynth` fetches one mp3 per instrument
 * and pitch, renders each UNIQUE sound once in an offline context, and copies it into an
 * output buffer at every start time it has — so what is compared is every one of those
 * decisions: the note URLs requested, the note map (`sequenceCallback`'s own argument), the
 * length of each offline render, the gain, pan and playback rate given to it, where each
 * copy landed in the output buffer, the transport's clock arithmetic through
 * `start`/`pause`/three flavours of `seek`/`stop`, and the WAV's length and checksum.
 *
 * The script and the recorder are SHARED FILES rather than duplicated blocks
 * (`create-synth-script.ts`, `audio-recorder.ts`): a state machine driven in two slightly
 * different orders would not be a comparison at all.
 *
 * ⚠️ **THE NOTE MAP CARRIES `startChar`/`endChar`** — abcjs stamps them in the flattener
 * onto the very note object the track holds, and this gate is what found that ours stamped
 * only its `midiPitches` copies, leaving `sequenceCallback`'s tracks without a span.
 */
type Golden = Record<string, Step[]>;

const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-create-synth", "golden.json"), "utf-8"),
) as Golden;

const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

const near = (a: unknown, b: unknown): boolean => {
  if (typeof a === "number" && typeof b === "number") return Math.abs(a - b) < 0.0005;
  if (Array.isArray(a) && Array.isArray(b))
    return a.length === b.length && a.every((v, i) => near(v, b[i]));
  if (a !== null && b !== null && typeof a === "object" && typeof b === "object") {
    const ka = Object.keys(a as object).filter(
      (k) => (a as Record<string, unknown>)[k] !== undefined,
    );
    const kb = Object.keys(b as object).filter(
      (k) => (b as Record<string, unknown>)[k] !== undefined,
    );
    if (ka.length !== kb.length) return false;
    return ka.every((k) =>
      near((a as Record<string, unknown>)[k], (b as Record<string, unknown>)[k]),
    );
  }
  return (a ?? null) === (b ?? null);
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const run = async (): Promise<Row[]> => {
  const g = globalThis as Record<string, unknown>;
  const saved = {
    window: g["window"],
    XMLHttpRequest: g["XMLHttpRequest"],
    OfflineAudioContext: g["OfflineAudioContext"],
    Blob: g["Blob"],
    AudioContext: g["AudioContext"],
  };
  const win: Record<string, unknown> = { URL: { createObjectURL: (): string => "" } };
  g["window"] = win;
  const recorder = installRecorder(win);
  registerAudioContext(recorder.ac);

  const out: Row[] = [];
  try {
    const tunes = new Map<string, unknown>();
    for (const fixture of FIXTURES) {
      const abc = readFileSync(join(IN_REPO, `${fixture}.abc`), "utf-8");
      tunes.set(fixture, parseOnly(abc)[0]);
      for (const [label, params] of CASES) {
        const key = `${fixture}#${label}`;
        const want = GOLDEN[key];
        if (want === undefined) continue;
        const got = await drive(
          () => new CreateSynth() as unknown as SynthLike,
          tunes.get(fixture),
          params,
          recorder,
        );
        let agree = 0;
        let first = "";
        for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
          if (near(want[i], got[i])) agree += 1;
          else if (first === "")
            first = `step ${i}: abcjs ${JSON.stringify(want[i]).slice(0, 240)} ours ${JSON.stringify(got[i]).slice(0, 240)}`;
        }
        out.push({ slug: key, agree, total: want.length, first });
      }
    }
    for (const [label, params] of PLAY_EVENT_CASES) {
      const key = `playEvent#${label}`;
      const want = GOLDEN[key];
      if (want === undefined) continue;
      const got = await drivePlayEvent(playEvent, params, recorder);
      let agree = 0;
      let first = "";
      for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
        if (near(want[i], got[i])) agree += 1;
        else if (first === "")
          first = `step ${i}: abcjs ${JSON.stringify(want[i]).slice(0, 240)} ours ${JSON.stringify(got[i]).slice(0, 240)}`;
      }
      out.push({ slug: key, agree, total: want.length, first });
    }
    for (const [label, spec] of ERROR_CASES) {
      const key = `error#${label}`;
      const want = GOLDEN[key];
      if (want === undefined) continue;
      const got = await driveErrors(
        () => new CreateSynth() as unknown as SynthLike,
        (abc: string) => parseOnly(abc)[0],
        spec,
        recorder,
        () => {
          for (const k of Object.keys(soundsCache)) delete soundsCache[k];
        },
      );
      let agree = 0;
      let first = "";
      for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
        if (near(want[i], got[i])) agree += 1;
        else if (first === "")
          first = `step ${i}: abcjs ${JSON.stringify(want[i]).slice(0, 240)} ours ${JSON.stringify(got[i]).slice(0, 240)}`;
      }
      out.push({ slug: key, agree, total: want.length, first });
    }
  } finally {
    for (const [k, v] of Object.entries(saved)) g[k] = v;
  }
  return out;
};

describe("CreateSynth — the scheduler behind the sound", async () => {
  const table = await run();

  it("writes the ranked table", () => {
    const off = table.filter((r) => r.agree < r.total);
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-create-synth-ranked.txt",
      `${[
        `${off.length} of ${table.length} cases differ; ${agree} of ${total} steps agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(52)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBe(24);
  });

  it("every case agrees on every step", () => {
    const broken = table
      .filter((r) => r.agree < r.total)
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken).toEqual([]);
  });
});
