import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";
import type { AbcLine } from "../src/compat/lines.js";

/**
 * **`tune.deline()` — abcjs's OWN MERGED LINE LIST, over 312 tunes and both option shapes.**
 *
 * The oracle is `tests/corpus-deline/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-deline.mjs`); abcjs asserts `deline` nowhere in its own suite.
 *
 * **THE ROWS ARE REDUCED AND THE REDUCTION IS THE POINT.** `deline`'s whole job is
 * bookkeeping — which lines merge, what order the voice stream ends up in, and which staff
 * field it moved — so each output line becomes text: `el_type@start..end` per element, and
 * `kept=` for the staff fields that survived. The spans themselves are `tune.lines`'s own
 * per-character gate's business, and the VALUES of the staff furniture are nobody's: they
 * decide only whether `objEqual` fires, which this gate sees through the unshift.
 *
 * So a row here fails for one of exactly three reasons, and they are worth telling apart
 * before touching anything:
 *
 *   1. **A `%%MIDI` IS A STREAM ELEMENT** with a `-1 … -1` span, and is not projected.
 *   2. **THE STREAM IS SHORT AN ELEMENT KIND** — a `stem` (which is `resolveOverlays`'s
 *      doing, not the parser's), a `midi`, a `style` or a `font`.
 *   3. **AN OVERLAY LAYER IS NOT `resolveOverlays`'s** — abcjs snips the `&` run out of the
 *      voice, pushes it as a new one and leaves THREE `stem` elements behind per snip.
 *
 * All three are `tune.lines` STRUCTURE gaps that its own gate cannot see, because
 * `getElementFromChar` walks every staff of every line and asks only about characters.
 */
const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-deline", "golden.json"), "utf-8"),
) as Record<string, string[]>;

const SIBLING = join(
  import.meta.dirname,
  "..",
  "..",
  "abcMusicKit",
  "Tools",
  "abcjs-debug",
  "fixtures",
);
const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/** The sibling repo edits these without regenerating goldens — see `lines.test.ts`. */
const STALE = ["sib/S7-voices", "sib/multi-voice-rest-placement"];

/** `rowsOfLine` from the harvester, over OUR projected lines. Keep the two identical. */
const rowsOfLine = (line: AbcLine, i: number): string[] => {
  const l = line as AbcLine & {
    text?: unknown;
    separator?: unknown;
    vskip?: unknown;
  };
  if (l.staff === undefined) {
    const kind =
      l.subtitle !== undefined
        ? "subtitle"
        : l.text !== undefined
          ? "text"
          : l.separator !== undefined
            ? "separator"
            : l.vskip !== undefined
              ? "vskip"
              : Object.keys(l).join("+");
    return [`L${i} ${kind}`];
  }
  const out: string[] = [];
  l.staff.forEach((staff, s) => {
    const st = staff as unknown as { [k: string]: unknown };
    const kept = ["meter", "key", "clef"].filter((k) => st[k] !== undefined);
    out.push(`L${i} s${s} kept=${kept.join(",")}`);
    staff.voices.forEach((voice, v) => {
      out.push(
        `L${i} s${s} v${v} ${voice
          .map((e) => `${e.el_type}@${e.startChar}..${e.endChar}`)
          .join(" ")}`,
      );
    });
  });
  return out;
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const rows = (): Row[] => {
  const out: Row[] = [];
  const cache = new Map<string, string>();
  for (const [key, want] of Object.entries(GOLDEN)) {
    if (STALE.some((slug) => key.startsWith(slug))) continue;
    const breaks = key.endsWith("#breaks");
    const slug = breaks ? key.slice(0, -"#breaks".length) : key;
    const corpus = slug.slice(0, slug.indexOf("/"));
    const rest = slug.slice(slug.indexOf("/") + 1);
    const at = rest.lastIndexOf("-tune");
    const file = rest.slice(0, at);
    const index = Number(rest.slice(at + "-tune".length));
    const dir = corpus === "sib" ? SIBLING : IN_REPO;
    let abc = cache.get(`${corpus}/${file}`);
    if (abc === undefined) {
      abc = readFileSync(join(dir, `${file}.abc`), "utf-8");
      cache.set(`${corpus}/${file}`, abc);
    }
    const slots: string[] = [];
    for (let k = 0; k <= index; k++) slots.push("*");
    const tune = renderAbc(slots, abc, {})[index];
    const got =
      tune === undefined
        ? []
        : tune.deline(breaks ? { lineBreaks: true } : {}).flatMap(rowsOfLine);
    let agree = 0;
    let first = "";
    for (let r = 0; r < Math.max(want.length, got.length); r += 1) {
      if (want[r] !== undefined && want[r] === got[r]) agree += 1;
      else if (first === "")
        first = `abcjs ${JSON.stringify(want[r])} ours ${JSON.stringify(got[r])}`;
    }
    out.push({ slug: key, agree, total: want.length, first });
  }
  return out;
};

/** Cases whose every row agrees. Grows, never shrinks. */
const PASSING: readonly string[] = [];

describe("tune.deline — abcjs's merged line list", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table
      .filter((r) => r.agree < r.total)
      .sort((a, b) => a.total - a.agree - (b.total - b.agree));
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-deline-ranked.txt",
      `${[
        `${off.length} of ${table.length} cases differ; ${agree} of ${total} rows agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(56)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(500);
  });

  it("every ratcheted case agrees on every row", () => {
    const broken = table
      .filter((r) => PASSING.includes(r.slug))
      .filter((r) => r.agree < r.total)
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken).toEqual([]);
  });

  /** A floor, not a target — it moves up and must never move down. */
  it("the whole corpus agrees on at least the rows it did", () => {
    const agree = table.reduce((t, r) => t + r.agree, 0);
    expect(agree).toBeGreaterThanOrEqual(1340);
  });
});
