import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { Editor } from "../src/compat/index.js";

/**
 * **`Editor` — THE TEXTAREA BINDING, DRIVEN THROUGH A SESSION AT THE KEYBOARD.**
 *
 * The oracle is `tests/corpus-editor/golden.json`, generated by RUNNING abcjs 6.7.0 in a
 * jsdom page (`scripts/harvest-abcjs-editor.mjs`). Ours is driven through the SAME
 * fourteen steps, in the same jsdom, and every column is what a HOST can see: how long the
 * rendered markup is and how many element groups it holds, which of those groups the
 * selection has painted, the textarea's class / `readonly` / selection, `isDirty()`, the
 * warnings div, and the two callbacks' own log.
 *
 * **THE DEBOUNCE IS THE REASON THIS IS A SEQUENCE AND NOT A SNAPSHOT.** `fireChanged`
 * schedules the re-render 300ms later and RESTARTS the timer on every keystroke
 * (`abc_editor.js:392-400`), so `setTimeout` is stubbed to CAPTURE and the harness fires it
 * at the step that says to — which makes "the text changed" and "the music caught up" two
 * separately observable states, and a `pause(true)` a state where neither happens.
 *
 * ⚠️ **jsdom COMES FROM THE SIBLING REPO'S `node_modules`, NOT FROM OURS** — the same rule
 * the animation gate follows, and for the same reason: the compat layer takes its DOM from
 * the HOST and abcts gains no dependency.
 */
const sibling = createRequire(
  join(
    import.meta.dirname,
    "..",
    "..",
    "abcMusicKit",
    "Tools",
    "abcjs-debug",
    "package.json",
  ),
);
interface DomElement {
  innerHTML: string;
  className: string;
  value: string;
  selectionStart: number;
  selectionEnd: number;
  getAttribute(name: string): string | null;
  setAttribute(name: string, value: string): void;
  removeAttribute(name: string): void;
  querySelectorAll(selector: string): ArrayLike<DomElement>;
}
interface DomDocument {
  getElementById(id: string): DomElement | null;
}
const { JSDOM } = sibling("jsdom") as {
  JSDOM: new (html: string) => { window: { document: DomDocument } };
};

/** ONE jsdom for the whole file, reset between cases — the harvester does the same. */
const dom = new JSDOM(
  '<!DOCTYPE html><html><body><textarea id="abc"></textarea><div id="paper"></div><div id="warn"></div></body></html>',
);

type Step = [
  string,
  number,
  number,
  number[],
  string,
  string | null,
  number,
  number,
  boolean,
  string,
  number,
  [number, number] | null,
];

const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-editor", "golden.json"), "utf-8"),
) as Record<string, Step[]>;

const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

const drive = (slug: string): Step[] => {
  const abc = readFileSync(join(IN_REPO, `${slug}.abc`), "utf-8");
  const g = globalThis as unknown as Record<string, unknown>;
  const saved = {
    document: g["document"],
    window: g["window"],
    setTimeout: g["setTimeout"],
    clearTimeout: g["clearTimeout"],
  };
  let pending: (() => void) | null = null;
  g["document"] = dom.window.document;
  g["window"] = dom.window;
  g["setTimeout"] = (fn: () => void) => {
    pending = fn;
    return 1;
  };
  g["clearTimeout"] = () => {
    pending = null;
  };
  const runTimer = (): void => {
    const fn = pending;
    pending = null;
    if (fn !== null) (fn as () => void)();
  };
  const log: Step[] = [];
  try {
    const ta = dom.window.document.getElementById("abc");
    const paper = dom.window.document.getElementById("paper");
    const warn = dom.window.document.getElementById("warn");
    if (ta === null || paper === null || warn === null) return [];
    ta.value = abc;
    ta.className = "";
    ta.removeAttribute("readonly");
    paper.innerHTML = "";
    warn.innerHTML = "";

    let changes = 0;
    let lastSelection: [number, number] | null = null;
    const editor = new Editor("abc", {
      paper_id: "paper",
      warnings_id: "warn",
      indicate_changed: true,
      onchange: () => {
        changes += 1;
      },
      selectionChangeCallback: (start: number, end: number) => {
        lastSelection = [start, end];
      },
    });

    const record = (label: string): void => {
      const groups = Array.from(paper.querySelectorAll("g[data-name]"));
      log.push([
        label,
        paper.innerHTML.length,
        groups.length,
        groups
          .map((el, i) =>
            (el.getAttribute("class") ?? "").indexOf("abcjs-note_selected") >= 0
              ? i
              : -1,
          )
          .filter((i) => i >= 0),
        ta.className,
        ta.getAttribute("readonly"),
        ta.selectionStart,
        ta.selectionEnd,
        editor.isDirty(),
        warn.innerHTML,
        changes,
        lastSelection,
      ]);
    };
    const select = (start: number, end: number): void => {
      ta.selectionStart = start;
      ta.selectionEnd = end;
      editor.fireSelectionChanged();
    };

    // ── THE FOURTEEN STEPS, verbatim from `scripts/harvest-abcjs-editor.mjs` ──
    record("construct");
    select(0, abc.length);
    record("select-all");
    select(Math.floor(abc.length / 2), Math.floor(abc.length / 2) + 2);
    record("select-mid");
    select(Math.floor(abc.length / 2), Math.floor(abc.length / 2));
    record("caret");
    ta.value = `${abc}|CDEF|\n`;
    editor.fireChanged();
    record("typed");
    runTimer();
    record("debounced");
    editor.setReadOnly(true);
    record("read-only-on");
    editor.setReadOnly(false);
    record("read-only-off");
    editor.setNotDirty();
    record("not-dirty");
    editor.pause(true);
    ta.value = `${ta.value}z`;
    editor.fireChanged();
    record("paused-typing");
    editor.pause(false);
    runTimer();
    record("resumed");
    editor.editarea.setString(abc);
    runTimer();
    record("set-string");
    editor.paramChanged({ staffwidth: 300 });
    runTimer();
    record("param-changed");
    editor.highlight({ startChar: 0, endChar: 4 });
    record("clicked");
  } finally {
    for (const [k, v] of Object.entries(saved)) g[k] = v;
  }
  return log;
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const rows = (): Row[] =>
  Object.entries(GOLDEN).map(([slug, want]) => {
    const got = drive(slug);
    let agree = 0;
    let first = "";
    for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
      if (JSON.stringify(want[i]) === JSON.stringify(got[i])) agree += 1;
      else if (first === "")
        first = `step ${i}: abcjs ${JSON.stringify(want[i])} ours ${JSON.stringify(got[i])}`;
    }
    return { slug, agree, total: want.length, first };
  });

/**
 * **THE RATCHET NAMES THE CASES THAT AGREE ON EVERY STEP** — an aggregate count hides a
 * regression that a named slug cannot, which is the lesson `tune.lines` paid for three
 * times in one session.
 */
const PASSING: readonly string[] = [
  "abcjs-parse-book_parser-01-example",
  "abcjs-parse-book_parser-02-tune",
  "abcjs-parse-book_parser-03-a",
  "abcjs-parse-note-01-c0-d1-eg-0-fa-1",
  "abcjs-visual-selection-02-g4-q-left-1-4-170-right-a4",
  "abcjs-visual-title-01-not-transformed",
  "abcjs-visual-title-02-transformed-the",
  "abcjs-visual-title-03-transformed-the",
];

describe("Editor — the textarea binding, step by step", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table.filter((r) => r.agree < r.total);
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-editor-ranked.txt",
      `${[
        `${off.length} of ${table.length} cases differ; ${agree} of ${total} steps agree`,
        "",
        ...off.map(
          (r) => `  ${r.slug.padEnd(56)} ${r.agree}/${r.total}  ${r.first}`,
        ),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(10);
  });

  it("every ratcheted case agrees on every step", () => {
    const broken = table
      .filter((r) => PASSING.includes(r.slug) && r.agree < r.total)
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken).toEqual([]);
  });

  it("nothing outside the ratchet has quietly started passing", () => {
    const arrived = table
      .filter((r) => !PASSING.includes(r.slug) && r.agree === r.total)
      .map((r) => r.slug);
    expect(
      arrived,
      "these agree on every step — add them to PASSING so the ratchet holds them",
    ).toEqual([]);
  });
});
