import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { extractMeasures } from "../src/compat/index.js";

/**
 * **`extractMeasures(abc)` — THE TUNE CUT INTO MEASURES OF ABC TEXT, over 223 files.**
 *
 * The oracle is `tests/corpus-extract-measures/golden.json`, generated by RUNNING abcjs
 * 6.7.0 (`scripts/harvest-abcjs-extract-measures.mjs`). abcjs's own suite asserts it on
 * three hand-written tunes; this is both corpora.
 *
 * **IT IS THE STRICTEST CONSUMER OF THE CHARACTER GATE THERE IS.** Every fragment is
 * `tune.abc.substring(fragStart, elem.endChar)` — `tune.lines`'s SPANS read back out as
 * text — so a span one character wrong shows up here as a bar that begins with the wrong
 * note, which is why it was worth building the day that gate closed.
 *
 * **28 FILES THROW AND THE THROW IS PART OF THE CONTRACT.** The header is split on the
 * first `K:` TEXTUALLY (`abc.split("K:")`, then `arr[1].split("\n")`), so a book whose
 * tunes have no `K:` dies on `arr[1]` — abcjs's own `TypeError`. The golden records it and
 * the port is held to it.
 */
interface Measure {
  readonly abc: string;
  readonly lastChord?: string;
  readonly startEnding?: string;
  readonly endEnding?: boolean;
}
interface Tune {
  readonly header: string;
  readonly measures: readonly Measure[];
  readonly hasPickup: boolean;
}

const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-extract-measures", "golden.json"),
    "utf-8",
  ),
) as Record<string, Tune[] | { throws: string }>;

const SIBLING = join(
  import.meta.dirname,
  "..",
  "..",
  "abcMusicKit",
  "Tools",
  "abcjs-debug",
  "fixtures",
);
const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/** The sibling repo edits these without regenerating goldens — see `lines.test.ts`. */
const STALE = ["sib/S7-voices", "sib/multi-voice-rest-placement"];

/**
 * Files where abcjs's own `extractMeasures` CRASHES and ours returns. A ruled divergence,
 * not a tolerance: each is written up in `Docs/ABCJS-DIFFERENCES.md` with its citation, and
 * **an entry here without one is a tolerance wearing a disguise** — the same contract
 * `svg-bytes`'s `DIVERGENT` list carries.
 *
 * ⚠️ Do NOT put these in `STALE`. That list means "the golden was not regenerated", which is
 * a different claim and would hide a real regression the day the file changed.
 */
const DIVERGENT = [
  /**
   * **`%%staffnonote 0` OVER A TUNE OF PURE RESTS CRASHES `extractMeasures`.** `cleanUp`
   * deletes every rest-only STAFF and leaves `line.staff` an EMPTY ARRAY — which is truthy —
   * and `extractMeasures` then reads `line.staff[0].voices` under a loop whose bound is a
   * hard-coded `k < 1` where `line.staff.length` is commented out
   * (`api/abc_tunebook.js:212-218`): `Cannot read properties of undefined (reading 'voices')`.
   *
   * Ours returns the measures. **Reproducing a crash is not parity**, and the SVG for both
   * tunes is byte-exact and ratcheted in `svg-bytes` — this surface alone diverges.
   */
  "repo/abcts-staffnonote-empty-staves",
];

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const rows = (): Row[] => {
  const out: Row[] = [];
  for (const [slug, want] of Object.entries(GOLDEN)) {
    if (STALE.includes(slug) || DIVERGENT.includes(slug)) continue;
    const corpus = slug.slice(0, slug.indexOf("/"));
    const file = slug.slice(slug.indexOf("/") + 1);
    const abc = readFileSync(
      join(corpus === "sib" ? SIBLING : IN_REPO, `${file}.abc`),
      "utf-8",
    );
    let got: Tune[] | { throws: string };
    try {
      got = extractMeasures(abc) as Tune[];
    } catch (e) {
      got = { throws: (e as Error).message };
    }
    // A throwing file is ONE row, and it agrees when both sides throw.
    if (!Array.isArray(want) || !Array.isArray(got)) {
      const same = !Array.isArray(want) && !Array.isArray(got);
      out.push({
        slug,
        agree: same ? 1 : 0,
        total: 1,
        first: same
          ? ""
          : `abcjs ${Array.isArray(want) ? "returned" : "threw"}, ours ${
              Array.isArray(got) ? "returned" : "threw"
            }`,
      });
      continue;
    }
    let agree = 0;
    let total = 0;
    let first = "";
    for (let t = 0; t < Math.max(want.length, got.length); t += 1) {
      const w = want[t];
      const g = got[t];
      total += 2 + (w?.measures.length ?? 0);
      if (w?.header === g?.header) agree += 1;
      else if (first === "")
        first = `tune ${t} header: abcjs ${JSON.stringify(w?.header)} ours ${JSON.stringify(g?.header)}`;
      if (w?.hasPickup === g?.hasPickup) agree += 1;
      else if (first === "")
        first = `tune ${t} hasPickup: abcjs ${String(w?.hasPickup)} ours ${String(g?.hasPickup)}`;
      for (let m = 0; m < (w?.measures.length ?? 0); m += 1) {
        const wm = w?.measures[m];
        const gm = g?.measures[m];
        if (JSON.stringify(wm) === JSON.stringify(gm)) agree += 1;
        else if (first === "")
          first = `tune ${t} measure ${m}: abcjs ${JSON.stringify(wm)} ours ${JSON.stringify(gm)}`;
      }
    }
    out.push({ slug, agree, total, first });
  }
  return out;
};

describe("extractMeasures — the tune cut into bars of ABC text", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table
      .filter((r) => r.agree < r.total)
      .sort((a, b) => a.total - a.agree - (b.total - b.agree));
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-extract-measures-ranked.txt",
      `${[
        `${off.length} of ${table.length} files differ; ${agree} of ${total} rows agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(56)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(200);
  });

  /**
   * ✅ **THE ONE ROW THIS GATE OPENED IS CLOSED, AND THE CHANNEL FOR IT ALREADY EXISTED.**
   * `C2|[-1 D2|]` read `"[-1 D2|]"` here where abcjs reads `" D2|]"`, and an abandoned
   * chord's `[` did the same to `tests/pitch-style.test.ts`. Both are one rule — abcjs
   * retakes `startI` at the top of every `parseMusic` iteration, so an iteration that
   * reads something and appends NOTHING leaves its characters to nobody — and
   * `Score.unreadable` was already the parser's channel for saying so, with `tile`
   * already pushing an element's opening past every range on it. Two producers were
   * added, not a mechanism.
   */
  it("every file agrees on every measure", () => {
    const broken = table
      .filter((r) => r.agree < r.total)
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken).toEqual([]);
  });
});
