import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { extractMeasures } from "../src/compat/index.js";

/**
 * **`extractMeasures(abc)` — THE TUNE CUT INTO MEASURES OF ABC TEXT, over 223 files.**
 *
 * The oracle is `tests/corpus-extract-measures/golden.json`, generated by RUNNING abcjs
 * 6.7.0 (`scripts/harvest-abcjs-extract-measures.mjs`). abcjs's own suite asserts it on
 * three hand-written tunes; this is both corpora.
 *
 * **IT IS THE STRICTEST CONSUMER OF THE CHARACTER GATE THERE IS.** Every fragment is
 * `tune.abc.substring(fragStart, elem.endChar)` — `tune.lines`'s SPANS read back out as
 * text — so a span one character wrong shows up here as a bar that begins with the wrong
 * note, which is why it was worth building the day that gate closed.
 *
 * **28 FILES THROW AND THE THROW IS PART OF THE CONTRACT.** The header is split on the
 * first `K:` TEXTUALLY (`abc.split("K:")`, then `arr[1].split("\n")`), so a book whose
 * tunes have no `K:` dies on `arr[1]` — abcjs's own `TypeError`. The golden records it and
 * the port is held to it.
 */
interface Measure {
  readonly abc: string;
  readonly lastChord?: string;
  readonly startEnding?: string;
  readonly endEnding?: boolean;
}
interface Tune {
  readonly header: string;
  readonly measures: readonly Measure[];
  readonly hasPickup: boolean;
}

const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-extract-measures", "golden.json"),
    "utf-8",
  ),
) as Record<string, Tune[] | { throws: string }>;

const SIBLING = join(
  import.meta.dirname,
  "..",
  "..",
  "abcMusicKit",
  "Tools",
  "abcjs-debug",
  "fixtures",
);
const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/** The sibling repo edits these without regenerating goldens — see `lines.test.ts`. */
const STALE = ["sib/S7-voices", "sib/multi-voice-rest-placement"];

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const rows = (): Row[] => {
  const out: Row[] = [];
  for (const [slug, want] of Object.entries(GOLDEN)) {
    if (STALE.includes(slug)) continue;
    const corpus = slug.slice(0, slug.indexOf("/"));
    const file = slug.slice(slug.indexOf("/") + 1);
    const abc = readFileSync(
      join(corpus === "sib" ? SIBLING : IN_REPO, `${file}.abc`),
      "utf-8",
    );
    let got: Tune[] | { throws: string };
    try {
      got = extractMeasures(abc) as Tune[];
    } catch (e) {
      got = { throws: (e as Error).message };
    }
    // A throwing file is ONE row, and it agrees when both sides throw.
    if (!Array.isArray(want) || !Array.isArray(got)) {
      const same = !Array.isArray(want) && !Array.isArray(got);
      out.push({
        slug,
        agree: same ? 1 : 0,
        total: 1,
        first: same
          ? ""
          : `abcjs ${Array.isArray(want) ? "returned" : "threw"}, ours ${
              Array.isArray(got) ? "returned" : "threw"
            }`,
      });
      continue;
    }
    let agree = 0;
    let total = 0;
    let first = "";
    for (let t = 0; t < Math.max(want.length, got.length); t += 1) {
      const w = want[t];
      const g = got[t];
      total += 2 + (w?.measures.length ?? 0);
      if (w?.header === g?.header) agree += 1;
      else if (first === "")
        first = `tune ${t} header: abcjs ${JSON.stringify(w?.header)} ours ${JSON.stringify(g?.header)}`;
      if (w?.hasPickup === g?.hasPickup) agree += 1;
      else if (first === "")
        first = `tune ${t} hasPickup: abcjs ${String(w?.hasPickup)} ours ${String(g?.hasPickup)}`;
      for (let m = 0; m < (w?.measures.length ?? 0); m += 1) {
        const wm = w?.measures[m];
        const gm = g?.measures[m];
        if (JSON.stringify(wm) === JSON.stringify(gm)) agree += 1;
        else if (first === "")
          first = `tune ${t} measure ${m}: abcjs ${JSON.stringify(wm)} ours ${JSON.stringify(gm)}`;
      }
    }
    out.push({ slug, agree, total, first });
  }
  return out;
};

describe("extractMeasures — the tune cut into bars of ABC text", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table
      .filter((r) => r.agree < r.total)
      .sort((a, b) => a.total - a.agree - (b.total - b.agree));
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-extract-measures-ranked.txt",
      `${[
        `${off.length} of ${table.length} files differ; ${agree} of ${total} rows agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(56)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(200);
  });

  /**
   * ⚠️ **ONE ROW IS OPEN, AND IT IS THE SPAN DEFECT ANOTHER GATE ALREADY NAMES.**
   * `C2|[-1 D2|]` — where the `[` is absorbed into the barline, `getTokenOf` reads `-1`
   * and the leading `-` REVERTS the whole ending (`abc_parse_music.js:885-886`) — leaves
   * `[-1` consumed by a failed parse and owned by NO element. abcjs's next measure
   * therefore opens at the surviving text and reads `" D2|]"`; ours TILES the line, so the
   * measure opens where the barline closed and reads `"[-1 D2|]"`.
   *
   * The same underlying rule is measured on `tests/pitch-style.test.ts`'s remaining
   * `it.fails`, where an abandoned chord's `[` and its lost `!>!` are owned by nothing and
   * abcjs opens the re-read note at 22 against our 18. **TWO SURFACES ASK FOR ONE FIX** —
   * the parser has nowhere to say "these characters were consumed and discarded", and the
   * tiling that the 100%-exact character gate rests on is what would have to learn it.
   * Named here rather than excluded silently.
   */
  it("every file agrees on every measure", () => {
    const broken = table
      .filter((r) => r.agree < r.total)
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken).toEqual([
      'repo/abcts-endings 32/33 tune 5 measure 1: abcjs {"abc":" D2|]"} ours {"abc":"[-1 D2|]"}',
    ]);
  });
});
