import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";

/**
 * **`tune.formatting` — THE `%%` SETTINGS abcjs COLLECTED — OVER 312 TUNES AND 7,219
 * SETTINGS.** Twenty-one font objects seeded before any directive is read, then whatever
 * the tune set IN SOURCE ORDER, then `pagewidth` and `pageheight`, which abcjs appends LAST
 * whatever the source said.
 *
 * The oracle is `tests/corpus-formatting/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-formatting.mjs`). **THE COMPARISON IS THE SERIALISED VALUE, KEY
 * ORDER INCLUDED**, because `JSON.stringify(tune.formatting)` is output a host can take —
 * and abcjs's order is what tells two kinds of entry apart on sight:
 *
 *   - **A DEFAULT FONT AND A SET FONT HAVE DIFFERENT KEY ORDERS.** The default literal is
 *     `{face, size, weight, style, decoration}`; `getFontParameter` builds a NEW object
 *     `{face, weight, style, decoration}` and only then assigns `size` and `box`
 *     (`abc_parse_directive.js:20-52`, `:295-313`). The `face` carries its own QUOTES —
 *     `"\"Times New Roman\""` is a CSS font-family list, not a name.
 *   - **`%%partsbox` MUTATES WHATEVER `partsfont` OBJECT IS CURRENT**, so it appends `box`
 *     to the DEFAULT literal when no `%%partsfont` replaced it (`:921-925`).
 *
 * Four rules decide what is IN it, and each was measured:
 *
 *   - **ELEVEN FONTS REPORT THEIR HEADER VALUE AND TEN REPORT THEIR LATEST.**
 *     `getChangingFont` writes `tune.formatting[cmd]` only `if (is_in_header)` — "If the
 *     font appears in the header, then it becomes the default font" (`:315-322`) — so
 *     `visual-tablature-17` sets `%%gchordfont` five times and abcjs reports the FIRST.
 *   - **`%%staffsep` IS THE POINTS AS WRITTEN, NOT THE PIXELS THEY BECOME.**
 *     `tune.formatting[cmd]` takes `points.value` off the token (`:421`); the 4/3 is applied
 *     later in `write/renderer.js`, so `%%staffsep 90` is 90 here and 120 there.
 *   - **A `%%MIDI` REACHES `formatting.midi` ONLY BEFORE `hasBeginMusic()`** — and that
 *     turns true at a BODY `V:`, which opens a line with a staff, while a HEADER `V:` only
 *     declares. **MEASURED ON A FIVE-RUNG LADDER through abcjs**, because the predicate is
 *     stated nowhere; and it is NOT the same flag as the one `appendStartingElement`
 *     branches on, which the byte gate proved by moving an accidental 7.75px when the two
 *     were merged.
 *   - **A `%%` DIRECTIVE ABOVE THE FIRST `X:` IS THE FILE HEADER** and its key must arrive
 *     in every tune — `%%stretchlast 1` written there was reaching the VALUE and not the
 *     ORDER, so the setting was right and the key absent.
 */
const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-formatting", "golden.json"),
    "utf-8",
  ),
) as Record<string, Record<string, unknown>>;

const SIBLING = join(
  import.meta.dirname,
  "..",
  "..",
  "abcMusicKit",
  "Tools",
  "abcjs-debug",
  "fixtures",
);
const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/**
 * Excluded, and NOT ours: both fixtures are edited in the sibling repo without their
 * goldens being regenerated — `S7-voices` since 2026-08-12 and both again on 2026-08-16,
 * when `multi-voice-rest-placement` gained an `X:1` line that moves every source offset by
 * four and no ink at all. `ls -la` on the fixture and its golden is the whole check.
 */
const STALE = ["sib/S7-voices", "sib/multi-voice-rest-placement"];

interface Row {
  readonly slug: string;
  readonly field: string;
  readonly want: string | undefined;
  readonly got: string | undefined;
}

const rows = (): Row[] => {
  const out: Row[] = [];
  for (const [slug, want] of Object.entries(GOLDEN)) {
    if (STALE.some((s) => slug.startsWith(s))) continue;
    const corpus = slug.slice(0, slug.indexOf("/"));
    const rest = slug.slice(slug.indexOf("/") + 1);
    const at = rest.lastIndexOf("-tune");
    const index = Number(rest.slice(at + 5));
    const abc = readFileSync(
      join(corpus === "sib" ? SIBLING : IN_REPO, `${rest.slice(0, at)}.abc`),
      "utf-8",
    );
    // One output slot per tune — `renderEngine` walks the SLOTS, not the tunes.
    const slots: string[] = [];
    for (let k = 0; k <= index; k++) slots.push("*");
    const got = (renderAbc(slots, abc, {})[index]?.formatting ?? {}) as Record<
      string,
      unknown
    >;
    for (const field of new Set([...Object.keys(want), ...Object.keys(got)]))
      out.push({
        slug,
        field,
        want: field in want ? JSON.stringify(want[field]) : undefined,
        got: field in got ? JSON.stringify(got[field]) : undefined,
      });
  }
  return out;
};

describe("formatting — abcjs's own %% settings", () => {
  const all = rows();

  it("holds every setting abcjs holds", () => {
    expect(
      all
        .filter((r) => r.want !== undefined && r.got === undefined)
        .map((r) => `${r.slug} ${r.field}`),
    ).toEqual([]);
  });

  it("invents no setting abcjs does not hold", () => {
    expect(
      all.filter((r) => r.want === undefined).map((r) => `${r.slug} ${r.field}`),
    ).toEqual([]);
  });

  it("serialises every setting exactly as abcjs does", () => {
    expect(
      all
        .filter((r) => r.want !== r.got)
        .map((r) => `${r.slug} ${r.field}: abcjs ${r.want} ours ${r.got}`),
    ).toEqual([]);
  });
});
