import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";

/**
 * **`metaTextInfo` — WHERE EACH `metaText` FIELD WAS WRITTEN — OVER 312 TUNES.**
 *
 * The oracle is `tests/corpus-metatextinfo/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-metatextinfo.mjs`), never copied out of its suite — abcjs's own
 * tests assert this nowhere at all.
 *
 * **IT IS ONE PIECE OF PLUMBING THAT PAYS FOUR TIMES.** The range is the FIELD LINE'S OWN
 * SPAN (`abc_parse_header.js:486-489`), and the same value is what a selectable `title` /
 * `subtitle` / `rhythm` / `composer` / `author` / `partOrder` row's `startChar`/`endChar`
 * come from: `TopText` builds each row with `info: metaTextInfo.<field>` and `nonMusic`
 * hands that `info` straight to `wrapSvgEl` (`draw/non-music.js:24-30`).
 *
 * Two rules it pinned that no other gate here could state:
 *
 *   - **THE TRAILING-WHITESPACE STRIP IS UNCONDITIONAL.** `line.replace(/\s+$/, '')` is
 *     its own statement after the comment cut, not part of that branch
 *     (`abc_parse.js:408-411`). We ran it only when a `%` was found, so
 *     `T:20. Subtitles, The ` gave `title` 4…25 against abcjs's 4…24. It is the `end`
 *     every field AND every music element takes its offsets from.
 *   - **A `%%` DIRECTIVE'S SPAN IS THE LINE WITHOUT ITS `%%`** — `iChar + str.length`
 *     where `str` is `addDirective`'s argument, `line.substring(2)` (`abc_parse.js:403`).
 *     So `%%header` starts at the first `%` and ends two characters short of the line.
 *
 * **`group`, `header` AND `footer` ARE POSITIONS WITH NO TEXT HERE.** abcjs records all
 * three (`abc_parse_header.js:469`, `abc_parse_directive.js:1183`); `G:` is read by
 * neither `TopText` nor `BottomText`, and the running head is print-only and unbuilt. The
 * POSITION is answered because that is what `metaTextInfo` is; the TEXT is the same gap
 * `metaText` still has for every field but `title`.
 */
interface Info {
  readonly startChar: number;
  readonly endChar: number;
}

const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-metatextinfo", "golden.json"),
    "utf-8",
  ),
) as Record<string, Record<string, Info>>;

const SIBLING = join(
  import.meta.dirname,
  "..",
  "..",
  "abcMusicKit",
  "Tools",
  "abcjs-debug",
  "fixtures",
);
const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/**
 * Excluded, and NOT ours: both fixtures are edited in the sibling repo without their
 * goldens being regenerated — `S7-voices` since 2026-08-12 and both again on 2026-08-16,
 * when `multi-voice-rest-placement` gained an `X:1` line that moves every source offset by
 * four and no ink at all. `ls -la` on the fixture and its golden is the whole check.
 */
const STALE = ["sib/S7-voices", "sib/multi-voice-rest-placement"];

interface Row {
  readonly slug: string;
  readonly field: string;
  readonly want: Info | undefined;
  readonly got: Info | undefined;
}

const rows = (): Row[] => {
  const out: Row[] = [];
  for (const [slug, want] of Object.entries(GOLDEN)) {
    if (STALE.some((s) => slug.startsWith(s))) continue;
    const corpus = slug.slice(0, slug.indexOf("/"));
    const rest = slug.slice(slug.indexOf("/") + 1);
    const at = rest.lastIndexOf("-tune");
    const index = Number(rest.slice(at + 5));
    const abc = readFileSync(
      join(corpus === "sib" ? SIBLING : IN_REPO, `${rest.slice(0, at)}.abc`),
      "utf-8",
    );
    // One output slot per tune — `renderEngine` walks the SLOTS, not the tunes.
    const slots: string[] = [];
    for (let k = 0; k <= index; k++) slots.push("*");
    const got = (renderAbc(slots, abc, {})[index]?.metaTextInfo ?? {}) as Record<
      string,
      Info
    >;
    for (const field of new Set([...Object.keys(want), ...Object.keys(got)]))
      out.push({ slug, field, want: want[field], got: got[field] });
  }
  return out;
};

describe("metaTextInfo — abcjs's own field positions", () => {
  const all = rows();

  it("records a position for every field abcjs records one for", () => {
    const missing = all.filter((r) => r.want !== undefined && r.got === undefined);
    expect(missing.map((r) => `${r.slug} ${r.field}`)).toEqual([]);
  });

  it("invents no position abcjs does not record", () => {
    const extra = all.filter((r) => r.want === undefined);
    expect(extra.map((r) => `${r.slug} ${r.field}`)).toEqual([]);
  });

  it("puts every field where abcjs puts it", () => {
    const differ = all.filter(
      (r) =>
        r.want?.startChar !== r.got?.startChar ||
        r.want?.endChar !== r.got?.endChar,
    );
    expect(
      differ.map(
        (r) =>
          `${r.slug} ${r.field}: abcjs ${JSON.stringify(r.want)} ours ${JSON.stringify(r.got)}`,
      ),
    ).toEqual([]);
  });
});
