import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";

/**
 * **`metaText` — THE TUNE'S FIELD VALUES — OVER 312 TUNES AND 368 FIELDS.**
 *
 * The oracle is `tests/corpus-metatext/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-metatext.mjs`), never copied out of its suite. It is the twin of
 * `metatextinfo.test.ts` beside it: that one says WHERE each field was written and this says
 * WHAT it said, and `TopText`/`BottomText` each read a value from one and a span from the
 * other. Ours answered `{title}` alone until 2026-08-17.
 *
 * **THE COMPARISON IS ON THE SERIALISED VALUE, KEY ORDER INCLUDED**, because
 * `JSON.stringify(tune.metaText)` is output a host can take. Four rules came out of that:
 *
 *   - **`W:` STAYS AN ARRAY AND `N:`/`H:` DO NOT.** `simplifyMetaText` joins an
 *     array-of-strings with `\n` and `unalignedWords` is not in its list
 *     (`tune-builder.js:479-484`), so a single plain `W:` line is `["…"]` where a single
 *     plain `N:` is `"…"`. It is also why `W:` is the one field that reaches
 *     `addMultiLine`'s array branch and the only bottom-block group with a selectable close.
 *   - **AN EMPTY FIELD IS STILL A FIELD.** `addMetaText` keys on `=== undefined`, not on
 *     truthiness (`:433`), so a bare `T:` records `title: ""`.
 *   - **AN INLINE `[Q:]` IS NOT `metaText.tempo` AT ALL.** `letter_to_inline_header`'s arm
 *     appends an ELEMENT or parks one for the next line and never touches `metaText`
 *     (`abc_parse_header.js:384-397`); only the field-line arm assigns it (`:530-536`).
 *   - **AND THE TEMPO'S KEY ORDER FOLLOWS FROM WHEN EACH VALUE IS ASSIGNED** — a written
 *     `1/4=120` gives its `duration` during `setTempo`, before the bpm, while a word-only
 *     `Q:"Adagio"` has no duration in the field and `calcTempo` supplies one at
 *     `resolveTempo`, after `suppressBpm`. The two are exclusive.
 *
 * `%%abc-copyright` and its siblings are absent because the parser does not collect them
 * yet, and `header`/`footer` carry their three parts and not their print sizes.
 */
const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-metatext", "golden.json"),
    "utf-8",
  ),
) as Record<string, Record<string, unknown>>;

const SIBLING = join(
  import.meta.dirname,
  "..",
  "..",
  "abcMusicKit",
  "Tools",
  "abcjs-debug",
  "fixtures",
);
const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/** Excluded, and NOT ours — see `metatextinfo.test.ts`. */
const STALE = ["sib/S7-voices", "sib/multi-voice-rest-placement"];

interface Row {
  readonly slug: string;
  readonly field: string;
  readonly want: string | undefined;
  readonly got: string | undefined;
}

const rows = (): Row[] => {
  const out: Row[] = [];
  for (const [slug, want] of Object.entries(GOLDEN)) {
    if (STALE.some((s) => slug.startsWith(s))) continue;
    const corpus = slug.slice(0, slug.indexOf("/"));
    const rest = slug.slice(slug.indexOf("/") + 1);
    const at = rest.lastIndexOf("-tune");
    const index = Number(rest.slice(at + 5));
    const abc = readFileSync(
      join(corpus === "sib" ? SIBLING : IN_REPO, `${rest.slice(0, at)}.abc`),
      "utf-8",
    );
    const slots: string[] = [];
    for (let k = 0; k <= index; k++) slots.push("*");
    const got = (renderAbc(slots, abc, {})[index]?.metaText ?? {}) as Record<
      string,
      unknown
    >;
    for (const field of new Set([...Object.keys(want), ...Object.keys(got)]))
      out.push({
        slug,
        field,
        want: field in want ? JSON.stringify(want[field]) : undefined,
        got: field in got ? JSON.stringify(got[field]) : undefined,
      });
  }
  return out;
};

describe("metaText — abcjs's own field values", () => {
  const all = rows();

  it("holds every field abcjs holds", () => {
    expect(
      all
        .filter((r) => r.want !== undefined && r.got === undefined)
        .map((r) => `${r.slug} ${r.field}`),
    ).toEqual([]);
  });

  it("invents no field abcjs does not hold", () => {
    expect(
      all.filter((r) => r.want === undefined).map((r) => `${r.slug} ${r.field}`),
    ).toEqual([]);
  });

  it("serialises every field exactly as abcjs does", () => {
    expect(
      all
        .filter((r) => r.want !== r.got)
        .map((r) => `${r.slug} ${r.field}: abcjs ${r.want} ours ${r.got}`),
    ).toEqual([]);
  });
});
