/**
 * **THE MIDI-FILE BYTE GATE OVER THE WHOLE CORPUS — 231 fixtures, no tolerance.**
 *
 * `tests/midi-file-ranked.test.ts` is three cases lifted from abcjs's own `midi.test.js`
 * assertions. **Three inputs is what "the MIDI file is byte-exact" rested on for a month**,
 * and every predicate those three exercise is TRUE in every row they have: all three tunes
 * have music, a `K:` and an `M:`. The first run of this gate found four defects that could
 * not be seen from there, three of them rules already ported elsewhere in this repo.
 *
 * The oracle is `tests/corpus-abcjs/midi.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-midi-corpus.mjs`) — never copied from its suite, which asserts
 * none of it. **THE ORACLE IS WHAT abcjs DOES, NOT WHAT ITS SUITE ASSERTS**, the same rule
 * the transpose oracle earned when abcjs's own test expected output abcjs does not produce.
 *
 * ── WHAT IT COMPARES ─────────────────────────────────────────────────────────
 * A BYTE STRING, so "differs" means differs. It writes `/tmp/abcts-midi-bytes.txt` in the
 * shape the other ranked tables use: the first divergence per case, both sides printed,
 * sorted by how far in it is — because the file is percent-encoded three characters to a
 * byte, and a character offset is not a position anyone can act on.
 *
 * ⚠️ **ONE TUNE PER FIXTURE, NOT ONE PER `X:`.** `getMidiFile` on a string is
 * `renderEngine(callback, "*", …)`, and `renderEngine` renders one tune per output SLOT, so
 * a multi-tune book yields its FIRST tune and nothing else. That is abcjs's own answer for
 * this entry point; reaching the others is a different call and would be a different gate.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { synth } from "../src/compat/index.js";

const fixtures = join(import.meta.dirname, "corpus-abcjs", "fixtures");
const oracle = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-abcjs", "midi.json"), "utf-8"),
) as { abcjs: string; midi: Record<string, string> };

/**
 * Cases where abcjs's own output is one we DECLINE to reproduce. A slug here without an
 * entry in `Docs/ABCJS-DIFFERENCES.md` is a tolerance wearing a disguise — the same rule
 * `svg-bytes`'s `DIVERGENT` list carries.
 */
const DIVERGENT: readonly string[] = [
  /**
   * **A TUNE WITH NO MUSIC WRITES `NaN` INTO THE TEMPO.** `commands.tempo` is undefined, so
   * `Math.round(60000000 / undefined)` is NaN and `toHex(NaN, 6)` pads the STRING `"NaN"`
   * to six characters and slices it into `%00%0N%aN` (`abc_midi_create.js:21`,
   * `abc_midi_renderer.js:35`). Those are not hex; abcjs's own binary decoder reads them
   * with `parseInt(…, 16)` as 0 and 10, so the file it hands a host has a tempo of about
   * 2.6 microseconds per quarter note. We write the 180bpm default instead.
   */
  "abcjs-parse-book_parser-01-example",
  "abcjs-parse-book_parser-02-tune",
  "abcjs-parse-book_parser-03-a",
  "abcjs-parse-book_parser-04-wed",
  "abcjs-parse-book_parser-05-a",
  "abcjs-parse-book_parser-06-a",
  "abcjs-parse-book_parser-07-a",
  "abcjs-visual-misc-14-tune",
  "abcjs-visual-misc-x07",
  "abcjs-visual-transpose-output-02-transpose-output",
  "abcts-staffnonote-empty-staves",
  /**
   * **A RICH `T:` MAKES abcjs THROW.** The track name goes through `encodeString(name,
   * "%01")`, which calls `charCodeAt` on it; a title carrying a font change is an OBJECT,
   * not a string, so `getMidiFile` dies with `e.charCodeAt is not a function` and the host
   * gets no file at all. **Our own note predicted `[object Object]` in the track name** —
   * measured, and it is worse than that. We skip the name and produce a playable file.
   */
  "abcjs-visual-misc-06-title-1bold-0-100-reg-the",
];


/**
 * **THE 205 FIXTURES THAT ARE BYTE-EXACT AND MUST STAY SO.** Named rather than counted: a
 * ratchet holding 4% of what is green is a ratchet in name, and `svg-bytes` twice had a
 * fixture go from exact to differing WHILE THE AGGREGATE IMPROVED. Add a slug the moment it
 * goes green, in the same commit that makes it so; never remove one to make a change pass.
 */
const PASSING: readonly string[] = [
  "abcjs-parse-note-id-01-v-v1-c-d-e-f",
  "abcjs-parse-tie-slur-01-multipart",
  "abcjs-parse-tie-slur-01-staffwidth-200",
  "abcjs-parse-tie-slur-02-chord",
  "abcjs-parse-tie-slur-02-staffwidth-200",
  "abcjs-parse-tie-slur-03-onestaff",
  "abcjs-parse-tie-slur-03-staffwidth-200",
  "abcjs-parse-tie-slur-04-height",
  "abcjs-parse-tie-slur-04-stretchlast-1",
  "abcjs-synth-flattener-01-crescendo-efga-gab-crescendo-c-diminuend",
  "abcjs-synth-flattener-02-p-c-def-gabc-d2-b2-g2-f2-f-e-fga-bcde-p-",
  "abcjs-synth-flattener-03-pppp-cdef-gabc-y-ffff-bcba-gfed-y-pppp-c",
  "abcjs-synth-flattener-04-g-gab-cde-d7-fga-def",
  "abcjs-synth-flattener-05-c-cde-def-c2e-d2f-c-c2-d-d-g-d2-e-e",
  "abcjs-synth-flattener-06-cde-d7-f2-d2-e2-f2-1-g-g4-fedc-c-e4z4",
  "abcjs-synth-flattener-07-metronome",
  "abcjs-synth-flattener-08-em-egab",
  "abcjs-synth-flattener-09-d-defg-q-1-2-90-defg",
  "abcjs-synth-flattener-10-q-1-4-129-0476605-cdef-q-1-4-127-gabc-q-",
  "abcjs-synth-flattener-11-midi-program-3",
  "abcjs-synth-flattener-12-chords-meter-change",
  "abcjs-synth-flattener-13-e7-bcde-a-f-break-efe-e7-bc-ignore-de",
  "abcjs-synth-flattener-14-eb7-zg2ga2a2-a2ab-b4-ab-z-break-c2cd2d2-",
  "abcjs-synth-flattener-15-c-c4-c",
  "abcjs-synth-flattener-16-gm-gfdf-gfdf-gf-d2-f-c4",
  "abcjs-synth-flattener-17-midi-grace-notes",
  "abcjs-synth-flattener-18-midi-program-40",
  "abcjs-synth-flattener-19-cdef-z4-fedc",
  "abcjs-synth-flattener-20-k-treble-8-b-a4-ce-f-4-k-treble-8-g8-g-2",
  "abcjs-synth-flattener-21-c4-d4",
  "abcjs-synth-flattener-22-b-c4-d4",
  "abcjs-synth-flattener-23-percmap-d-pedal-hi-hat-x",
  "abcjs-synth-flattener-24-percmap-c-high-tom-x",
  "abcjs-synth-flattener-25-cd-d2-d2-dz",
  "abcjs-synth-flattener-26-gbcd-d4-zcdc-dc3",
  "abcjs-synth-flattener-27-triplets-and-chord-rhythm",
  "abcjs-synth-flattener-28-midi-channel-10",
  "abcjs-synth-flattener-29-midi-drum-dddd-76-77-77-77-50-50-50-50",
  "abcjs-synth-flattener-30-am-a2e-e2d-g-bab-d2b-am-a2e-e2d-g-b2a-ga",
  "abcjs-synth-flattener-31-tempo-change-three-voices",
  "abcjs-synth-flattener-32-quarter-tone2",
  "abcjs-synth-flattener-33-tempo-override",
  "abcjs-synth-flattener-34-score-s-a-t-b",
  "abcjs-synth-flattener-35-midi-bassprog-10",
  "abcjs-synth-flattener-36-midi-gchord-fhihfhih",
  "abcjs-synth-flattener-37-midi-gchord-bzczbzcz",
  "abcjs-synth-flattener-38-c-zz-d-z-e-z",
  "abcjs-synth-flattener-39-midi-gchord-bzczbzcz",
  "abcjs-synth-flattener-40-c5-z4",
  "abcjs-synth-flattener-41-midi-bassprog-10-octave-1",
  "abcjs-synth-flattener-42-midi-gchord-ffffffff",
  "abcjs-synth-flattener-43-gm-zzz-cm-zzz",
  "abcjs-synth-flattener-44-cd-pppp-c-ffff-d-ffff-c-pppp-d-cd",
  "abcjs-synth-flattener-45-segno-f-d2",
  "abcjs-synth-flattener-46-c8-1-d8-2-e8-3-f8",
  "abcjs-synth-midi-01-midi-options",
  "abcjs-synth-midi-02-staccato",
  "abcjs-synth-midi-03-percmap",
  "abcjs-synth-timing-01-cde-fg-ab-1-bcd-2-efg",
  "abcjs-synth-timing-02-score-1-2",
  "abcjs-synth-timing-03-cd-e-f-3gab-ac",
  "abcjs-synth-timing-04-cd-e-f-3gab-ac",
  "abcjs-synth-timing-05-subtitle-crash",
  "abcjs-synth-timing-06-repeat-at-start-of-line-crash",
  "abcjs-synth-timing-07-skip-ties-crash",
  "abcjs-synth-timing-08-tie-repeat-crash",
  "abcjs-synth-timing-09-f-c-2d-2-e-4-g-6-a-2-g-4-e-4",
  "abcjs-synth-timing-10-stretchlast-1",
  "abcjs-synth-timing-11-stretchlast-1",
  "abcjs-synth-timing-12-stretchlast-1",
  "abcjs-synth-timing-y02",
  "abcjs-synth-timing-y03",
  "abcjs-visual-decorations-01-score-s-a-b",
  "abcjs-visual-decorations-x02",
  "abcjs-visual-directives-01-incipit-test",
  "abcjs-visual-directives-x01",
  "abcjs-visual-layout-01-barlabelfont-times-bold-18-box",
  "abcjs-visual-layout-02-barlabelfont-times-bold-18-box",
  "abcjs-visual-layout-03-cdef-cdef",
  "abcjs-visual-layout-04-score-s-a",
  "abcjs-visual-layout-05-c3-abc-cf-3-abc-c3-fa-bc",
  "abcjs-visual-layout-06-staves-1-2-3-4",
  "abcjs-visual-layout-07-v-1-b2-a2",
  "abcjs-visual-layout-08-staffwidth-100",
  "abcjs-visual-layout-09-endings",
  "abcjs-visual-misc-01-barnumbers-1",
  "abcjs-visual-misc-02-title",
  "abcjs-visual-misc-03-jazzchords",
  "abcjs-visual-misc-04-stretchlast",
  "abcjs-visual-misc-05-cccc-d-c-alcoda-dddd-d-c-alfine-eeee-d-s",
  "abcjs-visual-misc-07-ab-ef-g-d-df-f-d-a-4-c-4",
  "abcjs-visual-misc-08-a2-c2-t-a2t-c2",
  "abcjs-visual-misc-09-begintext",
  "abcjs-visual-misc-10-begintext",
  "abcjs-visual-misc-11-begintext",
  "abcjs-visual-misc-12-b-beambr1-b-bb",
  "abcjs-visual-misc-13-ceg-t-gce-d-f-b-3-dm7-d-te",
  "abcjs-visual-multi-voice-01-score-top-bottom",
  "abcjs-visual-multi-voice-02-p-c-2b2-z4-f2a2-f4",
  "abcjs-visual-multi-voice-x01",
  "abcjs-visual-multi-voice-x02",
  "abcjs-visual-multi-voice-x03",
  "abcjs-visual-multi-voice-x04",
  "abcjs-visual-multi-voice-x05",
  "abcjs-visual-multi-voice-x08",
  "abcjs-visual-parsing-01-azzz-e2",
  "abcjs-visual-parsing-02-sx",
  "abcjs-visual-parsing-03-v-1-f",
  "abcjs-visual-parsing-04-v-t-c",
  "abcjs-visual-parsing-05-v-t-c-v-b-a-v-t-d",
  "abcjs-visual-parsing-06-score-t-b",
  "abcjs-visual-parsing-07-score-t-b",
  "abcjs-visual-parsing-08-score-t-b",
  "abcjs-visual-parsing-09-score-t-b",
  "abcjs-visual-parsing-x10",
  "abcjs-visual-parsing-x11",
  "abcjs-visual-parsing-x12",
  "abcjs-visual-parsing-x14",
  "abcjs-visual-selection-02-g4-q-left-1-4-170-right-a4",
  "abcjs-visual-selection-03-c4",
  "abcjs-visual-slurs-01-score-s-a",
  "abcjs-visual-slurs-02-score-s-a-t-b",
  "abcjs-visual-svg-01-staffwidth-5",
  "abcjs-visual-svg-02-staffwidth-12",
  "abcjs-visual-svg-03-a4",
  "abcjs-visual-svg-per-line-02-scaled",
  "abcjs-visual-tablature-01-gr",
  "abcjs-visual-tablature-02-g-fg-a-g2-a-very-very-long-chord-d2-cd-f",
  "abcjs-visual-tablature-03-staves-rh-lh",
  "abcjs-visual-tablature-04-barnumbers-1",
  "abcjs-visual-tablature-05-a7-a",
  "abcjs-visual-tablature-06-a7-a",
  "abcjs-visual-tablature-07-staves-rh-lh",
  "abcjs-visual-tablature-08-first",
  "abcjs-visual-tablature-09-f-g",
  "abcjs-visual-tablature-10-f3-a-y",
  "abcjs-visual-tablature-11-f-f",
  "abcjs-visual-tablature-12-b",
  "abcjs-visual-tablature-13-g8-c4-d4-e4-f4",
  "abcjs-visual-tablature-14-c",
  "abcjs-visual-tablature-16-g-g-g-g",
  "abcjs-visual-tablature-18-a-b",
  "abcjs-visual-tablature-19-d-a-d-g-b-e",
  "abcjs-visual-tablature-20-score-1-2",
  "abcjs-visual-tablature-21-a2-a-a-f-f-f-f-f-e-ee-g-gg-g-k-eb-a2-a2",
  "abcjs-visual-tablature-22-g-cegda",
  "abcjs-visual-tablature-23-gab",
  "abcjs-visual-tablature-24-stretchlast",
  "abcjs-visual-title-01-not-transformed",
  "abcjs-visual-title-02-transformed-the",
  "abcjs-visual-title-03-transformed-the",
  "abcjs-visual-title-04-transformed-a",
  "abcjs-visual-title-05-transformed-an",
  "abcjs-visual-title-06-transformed-a",
  "abcjs-visual-title-07-24-number-transform-the",
  "abcjs-visual-title-08-24-number-transform-a",
  "abcjs-visual-title-09-mal-the-formed",
  "abcjs-visual-title-10-20-subtitles-the",
  "abcjs-visual-transpose-01-f2-f-f-f-f-f2-e2-e-e-e-e-e2-k-ab-f2-f-f-",
  "abcjs-visual-transpose-02-cdef-gabc-c-d-e-f-g-a-b-c-c-d-e-f-g-a-b-",
  "abcjs-visual-transpose-03-cdef-gabc-c-d-e-f-g-a-b-c-c-d-e-f-g-a-b-",
  "abcjs-visual-transpose-04-transpose-annotations",
  "abcjs-visual-transpose-05-n-c-ab-c-c-c-c-d-d-d-d-e-e-f-f-f-f-g-g-g",
  "abcjs-visual-transpose-06-c-d-e-f-g-a-b-c-cdef-gabc-c-d-e-f-g-a-b-",
  "abcjs-visual-transpose-output-01-transpose-output",
  "abcjs-visual-transpose-output-03-transpose-output",
  "abcjs-visual-transpose-output-04-transpose-output",
  "abcjs-visual-transpose-output-05-g",
  "abcjs-visual-transpose-output-06-f",
  "abcjs-visual-wrap-01-b-4-c2d2-e3f-gabc-d-e-f-g-marcato-d-e-f-",
  "abcjs-visual-wrap-02-stretchlast-1",
  "abcjs-visual-wrap-03-piano-wrap",
  "abcjs-visual-wrap-05-score-1-2-3-4",
  "abcts-bars-graces-and-groups",
  "abcts-clef-midmeasure",
  "abcts-decorations",
  "abcts-directives",
  "abcts-directives-2",
  "abcts-endings",
  "abcts-grace-order-and-lanes",
  "abcts-grace-tie",
  "abcts-keywarn",
  "abcts-last-bar",
  "abcts-ledger-gaps",
  "abcts-ledger-gaps-2",
  "abcts-ledger-gaps-4",
  "abcts-lyric-verses",
  "abcts-midi",
  "abcts-model-gaps",
  "abcts-pitch-style",
  "abcts-positioning",
  "abcts-rests-and-bars",
  "abcts-shared-staff-rests",
  "abcts-slur-shapes",
  "abcts-stafflines-and-modifiers",
  "abcts-start-char",
  "abcts-tempo-rung",
  "abcts-text-udef-parts-overlays",
  "abcts-unknown-clef",
  "abcts-visualtranspose",
  "abcts-voice-modifiers",
  "abcts-voice-scale",
  "abcts-voice-style",
  "abcts-void-notes-and-stray-ties",
  "abcts-vskip",
];

/**
 * How many non-divergent fixtures may still differ. **It may only fall.** 14 when this gate
 * landed, from 26 before the four defects it found were fixed and 33 before that. The
 * families left are named in `/tmp/abcts-midi-bytes.txt`.
 */
const OPEN_CEILING = 14;

const PREFIX = "data:audio/midi,";

/** The file as a list of BYTES — `midi-file-ranked`'s decode, and abcjs's own. */
function bytes(data: string): string[] {
  const body = data
    .replace(PREFIX, "")
    .replace(/MThd/g, "%4d%54%68%64")
    .replace(/MTrk/g, "%4d%54%72%6b");
  const out: string[] = [];
  for (let i = 0; i + 2 < body.length + 1; i += 3)
    out.push(body.substring(i + 1, i + 3).toLowerCase());
  return out;
}

interface Diff {
  readonly matched: number;
  readonly where: string;
}

function firstDifference(got: string, want: string): Diff | null {
  if (got === want) return null;
  if (!got.startsWith(PREFIX))
    return { matched: 0, where: `no \`${PREFIX}\` prefix: ${got.slice(0, 60)}` };
  if (!want.startsWith(PREFIX))
    return { matched: 0, where: `abcjs produced no file: ${want.slice(0, 60)}` };
  const a = bytes(got);
  const b = bytes(want);
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i += 1) {
    if (a[i] !== b[i]) {
      const from = Math.max(0, i - 6);
      return {
        matched: i,
        where:
          `byte ${i}\n      ours  …${a.slice(from, i).join(" ")} [${a[i]}] ${a.slice(i + 1, i + 7).join(" ")}…` +
          `\n      abcjs …${b.slice(from, i).join(" ")} [${b[i]}] ${b.slice(i + 1, i + 7).join(" ")}…`,
      };
    }
  }
  return {
    matched: n,
    where:
      a.length > b.length
        ? `${a.length} bytes, abcjs ${b.length}: we add ${a.slice(n, n + 8).join(" ")}…`
        : `${a.length} bytes, abcjs ${b.length}: we drop ${b.slice(n, n + 8).join(" ")}…`,
  };
}

const SLUGS = Object.keys(oracle.midi).sort();

const ours = (slug: string): string => {
  try {
    const abc = readFileSync(join(fixtures, `${slug}.abc`), "utf-8");
    const r = synth.getMidiFile(abc, { midiOutputType: "encoded" });
    const first = Array.isArray(r) ? r[0] : r;
    return typeof first === "string" ? first : `NOT A STRING: ${typeof first}`;
  } catch (e) {
    return `THREW: ${e instanceof Error ? e.message : String(e)}`;
  }
};

const ROWS = SLUGS.map((slug) => ({
  slug,
  diff: firstDifference(ours(slug), oracle.midi[slug] ?? "(absent)"),
}));

describe("the MIDI file, byte for byte against abcjs 6.7.0", () => {
  /**
   * ⚠️ **THE ORACLE'S VERSION IS ASSERTED, NOT ASSUMED.** `CLAUDE.md` records
   * `harvest-abcjs-goldens.mjs` silently rebaselining the SVG byte gate against 6.6.3 — a
   * harvester whose version was a default rather than a statement moves the TARGET, and a
   * gate cannot see its own target move.
   */
  it("is generated from abcjs 6.7.0", () => {
    expect(oracle.abcjs).toBe("6.7.0");
    expect(SLUGS.length).toBeGreaterThan(200);
  });

  /**
   * **THE RATCHET.** Every slug that is byte-exact must stay so; it grows and never shrinks.
   * `svg-bytes` learned why the hard way — seven named slugs could not defend eighty-nine,
   * and twice a fixture went from exact to differing WHILE THE AGGREGATE IMPROVED.
   */
  it("keeps every byte-exact fixture byte-exact", () => {
    const broken = ROWS.filter(
      (r) => PASSING.includes(r.slug) && r.diff !== null,
    ).map((r) => `${r.slug}: ${r.diff?.where.split("\n")[0]}`);
    expect(broken).toEqual([]);
  });

  it("has no differing fixture that is not ruled divergent", () => {
    const open = ROWS.filter(
      (r) => r.diff !== null && !DIVERGENT.includes(r.slug),
    ).sort((a, b) => (b.diff?.matched ?? 0) - (a.diff?.matched ?? 0));

    const report = [
      `abcts vs abcjs ${oracle.abcjs}, MIDI file bytes, ${SLUGS.length} fixtures`,
      `${open.length} differing (${DIVERGENT.length} ruled divergent)`,
      "",
      ...open.map((r) => `  ${r.slug}  matched ${r.diff?.matched}\n      ${r.diff?.where}\n`),
    ].join("\n");
    writeFileSync("/tmp/abcts-midi-bytes.txt", `${report}\n`);

    // Ratcheted by COUNT while the tail is worked down, and by NAME above. The count may
    // only fall; a row that closes is added to PASSING in the same commit.
    expect(open.length, `see /tmp/abcts-midi-bytes.txt\n${report.slice(0, 2000)}`).toBeLessThanOrEqual(OPEN_CEILING);
  });

  /** A slug ruled divergent must actually differ, or the ruling is stale. */
  it("has no stale divergent ruling", () => {
    const agreeing = DIVERGENT.filter(
      (slug) => ROWS.find((r) => r.slug === slug)?.diff === null,
    );
    expect(agreeing).toEqual([]);
  });
});
