/**
 * **THE MIDI-FILE BYTE GATE OVER THE WHOLE CORPUS — 231 fixtures, no tolerance.**
 *
 * `tests/midi-file-ranked.test.ts` is three cases lifted from abcjs's own `midi.test.js`
 * assertions. **Three inputs is what "the MIDI file is byte-exact" rested on for a month**,
 * and every predicate those three exercise is TRUE in every row they have: all three tunes
 * have music, a `K:` and an `M:`. The first run of this gate found four defects that could
 * not be seen from there, three of them rules already ported elsewhere in this repo.
 *
 * The oracle is `tests/corpus-abcjs/midi.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-midi-corpus.mjs`) — never copied from its suite, which asserts
 * none of it. **THE ORACLE IS WHAT abcjs DOES, NOT WHAT ITS SUITE ASSERTS**, the same rule
 * the transpose oracle earned when abcjs's own test expected output abcjs does not produce.
 *
 * ── WHAT IT COMPARES ─────────────────────────────────────────────────────────
 * A BYTE STRING, so "differs" means differs. It writes `/tmp/abcts-midi-bytes.txt` in the
 * shape the other ranked tables use: the first divergence per case, both sides printed,
 * sorted by how far in it is — because the file is percent-encoded three characters to a
 * byte, and a character offset is not a position anyone can act on.
 *
 * ⚠️ **ONE TUNE PER FIXTURE, NOT ONE PER `X:`.** `getMidiFile` on a string is
 * `renderEngine(callback, "*", …)`, and `renderEngine` renders one tune per output SLOT, so
 * a multi-tune book yields its FIRST tune and nothing else. That is abcjs's own answer for
 * this entry point; reaching the others is a different call and would be a different gate.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseOnly, synth } from "../src/compat/index.js";

const fixtures = join(import.meta.dirname, "corpus-abcjs", "fixtures");
const oracle = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-abcjs", "midi.json"), "utf-8"),
) as { abcjs: string; midi: Record<string, string> };

/**
 * Cases where abcjs's own output is one we DECLINE to reproduce. A slug here without an
 * entry in `Docs/ABCJS-DIFFERENCES.md` is a tolerance wearing a disguise — the same rule
 * `svg-bytes`'s `DIVERGENT` list carries.
 */
const DIVERGENT: readonly string[] = [
  /**
   * **A TUNE WITH NO MUSIC WRITES `NaN` INTO THE TEMPO.** `commands.tempo` is undefined, so
   * `Math.round(60000000 / undefined)` is NaN and `toHex(NaN, 6)` pads the STRING `"NaN"`
   * to six characters and slices it into `%00%0N%aN` (`abc_midi_create.js:21`,
   * `abc_midi_renderer.js:35`). Those are not hex; abcjs's own binary decoder reads them
   * with `parseInt(…, 16)` as 0 and 10, so the file it hands a host has a tempo of about
   * 2.6 microseconds per quarter note. We write the 180bpm default instead.
   *
   * **AND TWO TUNES MAKE abcjs THROW OUTRIGHT**, so a host gets no file at all:
   *   - `visual-misc-06`: a rich `T:` reaches `encodeString`'s `charCodeAt` as an OBJECT —
   *     `e.charCodeAt is not a function`. **Our own note predicted `[object Object]` in the
   *     track name; measured, it is worse than that.**
   *   - `abcts-endings#3` and `#4`: `Cannot read properties of undefined (reading
   *     'el_type')`, found only once the gate reached past tune 0.
   *
   * Every entry here needs a `Docs/ABCJS-DIFFERENCES.md` entry — a slug without one is a
   * tolerance wearing a disguise.
   */
  "abcjs-parse-book_parser-01-example#0",
  "abcjs-parse-book_parser-02-tune#0",
  "abcjs-parse-book_parser-03-a#0",
  "abcjs-parse-book_parser-03-a#1",
  "abcjs-parse-book_parser-03-a#2",
  "abcjs-parse-book_parser-04-wed#0",
  "abcjs-parse-book_parser-05-a#0",
  "abcjs-parse-book_parser-05-a#1",
  "abcjs-parse-book_parser-06-a#0",
  "abcjs-parse-book_parser-07-a#0",
  "abcjs-visual-misc-06-title-1bold-0-100-reg-the#0",
  "abcjs-visual-misc-14-tune#0",
  "abcjs-visual-misc-x07#0",
  "abcjs-visual-transpose-output-02-transpose-output#0",
  "abcts-endings#3",
  "abcts-endings#4",
  "abcts-inline-fields-and-blocks#9",
  "abcts-staffnonote-empty-staves#0",
  "abcts-staffnonote-empty-staves#1",
];


/**
 * **THE 648 TUNES THAT ARE BYTE-EXACT AND MUST STAY SO.** Named rather than counted: a
 * ratchet holding 4% of what is green is a ratchet in name, and `svg-bytes` twice had a
 * fixture go from exact to differing WHILE THE AGGREGATE IMPROVED. Add a slug the moment it
 * goes green, in the same commit that makes it so; never remove one to make a change pass.
 */
const PASSING: readonly string[] = [
  "abcjs-parse-note-id-01-v-v1-c-d-e-f#0",
  "abcjs-parse-tie-slur-01-multipart#0",
  "abcjs-parse-tie-slur-01-staffwidth-200#0",
  "abcjs-parse-tie-slur-02-chord#0",
  "abcjs-parse-tie-slur-02-staffwidth-200#0",
  "abcjs-parse-tie-slur-03-onestaff#0",
  "abcjs-parse-tie-slur-03-staffwidth-200#0",
  "abcjs-parse-tie-slur-04-height#0",
  "abcjs-parse-tie-slur-04-stretchlast-1#0",
  "abcjs-synth-flattener-01-crescendo-efga-gab-crescendo-c-diminuend#0",
  "abcjs-synth-flattener-02-p-c-def-gabc-d2-b2-g2-f2-f-e-fga-bcde-p-#0",
  "abcjs-synth-flattener-03-pppp-cdef-gabc-y-ffff-bcba-gfed-y-pppp-c#0",
  "abcjs-synth-flattener-04-g-gab-cde-d7-fga-def#0",
  "abcjs-synth-flattener-05-c-cde-def-c2e-d2f-c-c2-d-d-g-d2-e-e#0",
  "abcjs-synth-flattener-06-cde-d7-f2-d2-e2-f2-1-g-g4-fedc-c-e4z4#0",
  "abcjs-synth-flattener-07-metronome#0",
  "abcjs-synth-flattener-08-em-egab#0",
  "abcjs-synth-flattener-09-d-defg-q-1-2-90-defg#0",
  "abcjs-synth-flattener-10-q-1-4-129-0476605-cdef-q-1-4-127-gabc-q-#0",
  "abcjs-synth-flattener-11-midi-program-3#0",
  "abcjs-synth-flattener-12-chords-meter-change#0",
  "abcjs-synth-flattener-13-e7-bcde-a-f-break-efe-e7-bc-ignore-de#0",
  "abcjs-synth-flattener-14-eb7-zg2ga2a2-a2ab-b4-ab-z-break-c2cd2d2-#0",
  "abcjs-synth-flattener-15-c-c4-c#0",
  "abcjs-synth-flattener-16-gm-gfdf-gfdf-gf-d2-f-c4#0",
  "abcjs-synth-flattener-17-midi-grace-notes#0",
  "abcjs-synth-flattener-18-midi-program-40#0",
  "abcjs-synth-flattener-19-cdef-z4-fedc#0",
  "abcjs-synth-flattener-20-k-treble-8-b-a4-ce-f-4-k-treble-8-g8-g-2#0",
  "abcjs-synth-flattener-21-c4-d4#0",
  "abcjs-synth-flattener-22-b-c4-d4#0",
  "abcjs-synth-flattener-23-percmap-d-pedal-hi-hat-x#0",
  "abcjs-synth-flattener-24-percmap-c-high-tom-x#0",
  "abcjs-synth-flattener-25-cd-d2-d2-dz#0",
  "abcjs-synth-flattener-26-gbcd-d4-zcdc-dc3#0",
  "abcjs-synth-flattener-27-triplets-and-chord-rhythm#0",
  "abcjs-synth-flattener-28-midi-channel-10#0",
  "abcjs-synth-flattener-29-midi-drum-dddd-76-77-77-77-50-50-50-50#0",
  "abcjs-synth-flattener-30-am-a2e-e2d-g-bab-d2b-am-a2e-e2d-g-b2a-ga#0",
  "abcjs-synth-flattener-31-tempo-change-three-voices#0",
  "abcjs-synth-flattener-32-quarter-tone2#0",
  "abcjs-synth-flattener-33-tempo-override#0",
  "abcjs-synth-flattener-34-score-s-a-t-b#0",
  "abcjs-synth-flattener-35-midi-bassprog-10#0",
  "abcjs-synth-flattener-36-midi-gchord-fhihfhih#0",
  "abcjs-synth-flattener-37-midi-gchord-bzczbzcz#0",
  "abcjs-synth-flattener-38-c-zz-d-z-e-z#0",
  "abcjs-synth-flattener-39-midi-gchord-bzczbzcz#0",
  "abcjs-synth-flattener-40-c5-z4#0",
  "abcjs-synth-flattener-41-midi-bassprog-10-octave-1#0",
  "abcjs-synth-flattener-42-midi-gchord-ffffffff#0",
  "abcjs-synth-flattener-43-gm-zzz-cm-zzz#0",
  "abcjs-synth-flattener-44-cd-pppp-c-ffff-d-ffff-c-pppp-d-cd#0",
  "abcjs-synth-flattener-45-segno-f-d2#0",
  "abcjs-synth-flattener-46-c8-1-d8-2-e8-3-f8#0",
  "abcjs-synth-midi-01-midi-options#0",
  "abcjs-synth-midi-02-staccato#0",
  "abcjs-synth-midi-03-percmap#0",
  "abcjs-synth-timing-01-cde-fg-ab-1-bcd-2-efg#0",
  "abcjs-synth-timing-02-score-1-2#0",
  "abcjs-synth-timing-03-cd-e-f-3gab-ac#0",
  "abcjs-synth-timing-04-cd-e-f-3gab-ac#0",
  "abcjs-synth-timing-05-subtitle-crash#0",
  "abcjs-synth-timing-06-repeat-at-start-of-line-crash#0",
  "abcjs-synth-timing-07-skip-ties-crash#0",
  "abcjs-synth-timing-08-tie-repeat-crash#0",
  "abcjs-synth-timing-09-f-c-2d-2-e-4-g-6-a-2-g-4-e-4#0",
  "abcjs-synth-timing-10-stretchlast-1#0",
  "abcjs-synth-timing-11-stretchlast-1#0",
  "abcjs-synth-timing-12-stretchlast-1#0",
  "abcjs-synth-timing-y02#0",
  "abcjs-synth-timing-y03#0",
  "abcjs-visual-decorations-01-score-s-a-b#0",
  "abcjs-visual-decorations-x02#0",
  "abcjs-visual-directives-01-incipit-test#0",
  "abcjs-visual-directives-x01#0",
  "abcjs-visual-layout-01-barlabelfont-times-bold-18-box#0",
  "abcjs-visual-layout-02-barlabelfont-times-bold-18-box#0",
  "abcjs-visual-layout-03-cdef-cdef#0",
  "abcjs-visual-layout-04-score-s-a#0",
  "abcjs-visual-layout-05-c3-abc-cf-3-abc-c3-fa-bc#0",
  "abcjs-visual-layout-06-staves-1-2-3-4#0",
  "abcjs-visual-layout-07-v-1-b2-a2#0",
  "abcjs-visual-layout-08-staffwidth-100#0",
  "abcjs-visual-layout-09-endings#0",
  "abcjs-visual-misc-01-barnumbers-1#0",
  "abcjs-visual-misc-02-title#0",
  "abcjs-visual-misc-03-jazzchords#0",
  "abcjs-visual-misc-04-stretchlast#0",
  "abcjs-visual-misc-05-cccc-d-c-alcoda-dddd-d-c-alfine-eeee-d-s#0",
  "abcjs-visual-misc-06-title-1bold-0-100-reg-the#1",
  "abcjs-visual-misc-07-ab-ef-g-d-df-f-d-a-4-c-4#0",
  "abcjs-visual-misc-08-a2-c2-t-a2t-c2#0",
  "abcjs-visual-misc-09-begintext#0",
  "abcjs-visual-misc-10-begintext#0",
  "abcjs-visual-misc-11-begintext#0",
  "abcjs-visual-misc-12-b-beambr1-b-bb#0",
  "abcjs-visual-misc-13-ceg-t-gce-d-f-b-3-dm7-d-te#0",
  "abcjs-visual-mouse-click-01-selection-test#0",
  "abcjs-visual-multi-voice-01-score-top-bottom#0",
  "abcjs-visual-multi-voice-02-p-c-2b2-z4-f2a2-f4#0",
  "abcjs-visual-multi-voice-x01#0",
  "abcjs-visual-multi-voice-x02#0",
  "abcjs-visual-multi-voice-x03#0",
  "abcjs-visual-multi-voice-x04#0",
  "abcjs-visual-multi-voice-x05#0",
  "abcjs-visual-multi-voice-x08#0",
  "abcjs-visual-parsing-01-azzz-e2#0",
  "abcjs-visual-parsing-02-sx#0",
  "abcjs-visual-parsing-03-v-1-f#0",
  "abcjs-visual-parsing-04-v-t-c#0",
  "abcjs-visual-parsing-05-v-t-c-v-b-a-v-t-d#0",
  "abcjs-visual-parsing-06-score-t-b#0",
  "abcjs-visual-parsing-07-score-t-b#0",
  "abcjs-visual-parsing-08-score-t-b#0",
  "abcjs-visual-parsing-09-score-t-b#0",
  "abcjs-visual-parsing-x10#0",
  "abcjs-visual-parsing-x11#0",
  "abcjs-visual-parsing-x12#0",
  "abcjs-visual-parsing-x14#0",
  "abcjs-visual-selection-01-selection-test#0",
  "abcjs-visual-selection-02-g4-q-left-1-4-170-right-a4#0",
  "abcjs-visual-selection-03-c4#0",
  "abcjs-visual-slurs-01-score-s-a#0",
  "abcjs-visual-slurs-02-score-s-a-t-b#0",
  "abcjs-visual-svg-01-staffwidth-5#0",
  "abcjs-visual-svg-02-staffwidth-12#0",
  "abcjs-visual-svg-03-a4#0",
  "abcjs-visual-svg-per-line-01-selection-test#0",
  "abcjs-visual-svg-per-line-02-scaled#0",
  "abcjs-visual-tablature-01-gr#0",
  "abcjs-visual-tablature-02-g-fg-a-g2-a-very-very-long-chord-d2-cd-f#0",
  "abcjs-visual-tablature-03-staves-rh-lh#0",
  "abcjs-visual-tablature-04-barnumbers-1#0",
  "abcjs-visual-tablature-05-a7-a#0",
  "abcjs-visual-tablature-06-a7-a#0",
  "abcjs-visual-tablature-07-staves-rh-lh#0",
  "abcjs-visual-tablature-08-first#0",
  "abcjs-visual-tablature-09-f-g#0",
  "abcjs-visual-tablature-10-f3-a-y#0",
  "abcjs-visual-tablature-11-f-f#0",
  "abcjs-visual-tablature-12-b#0",
  "abcjs-visual-tablature-13-g8-c4-d4-e4-f4#0",
  "abcjs-visual-tablature-14-c#0",
  "abcjs-visual-tablature-15-all-element-types#0",
  "abcjs-visual-tablature-16-g-g-g-g#0",
  "abcjs-visual-tablature-18-a-b#0",
  "abcjs-visual-tablature-19-d-a-d-g-b-e#0",
  "abcjs-visual-tablature-20-score-1-2#0",
  "abcjs-visual-tablature-21-a2-a-a-f-f-f-f-f-e-ee-g-gg-g-k-eb-a2-a2#0",
  "abcjs-visual-tablature-22-g-cegda#0",
  "abcjs-visual-tablature-23-gab#0",
  "abcjs-visual-tablature-24-stretchlast#0",
  "abcjs-visual-title-01-not-transformed#0",
  "abcjs-visual-title-02-transformed-the#0",
  "abcjs-visual-title-03-transformed-the#0",
  "abcjs-visual-title-04-transformed-a#0",
  "abcjs-visual-title-05-transformed-an#0",
  "abcjs-visual-title-06-transformed-a#0",
  "abcjs-visual-title-07-24-number-transform-the#0",
  "abcjs-visual-title-08-24-number-transform-a#0",
  "abcjs-visual-title-09-mal-the-formed#0",
  "abcjs-visual-title-10-20-subtitles-the#0",
  "abcjs-visual-transpose-01-f2-f-f-f-f-f2-e2-e-e-e-e-e2-k-ab-f2-f-f-#0",
  "abcjs-visual-transpose-02-cdef-gabc-c-d-e-f-g-a-b-c-c-d-e-f-g-a-b-#0",
  "abcjs-visual-transpose-03-cdef-gabc-c-d-e-f-g-a-b-c-c-d-e-f-g-a-b-#0",
  "abcjs-visual-transpose-04-transpose-annotations#0",
  "abcjs-visual-transpose-05-n-c-ab-c-c-c-c-d-d-d-d-e-e-f-f-f-f-g-g-g#0",
  "abcjs-visual-transpose-06-c-d-e-f-g-a-b-c-cdef-gabc-c-d-e-f-g-a-b-#0",
  "abcjs-visual-transpose-output-01-transpose-output#0",
  "abcjs-visual-transpose-output-03-transpose-output#0",
  "abcjs-visual-transpose-output-04-transpose-output#0",
  "abcjs-visual-transpose-output-05-g#0",
  "abcjs-visual-transpose-output-06-f#0",
  "abcjs-visual-wrap-01-b-4-c2d2-e3f-gabc-d-e-f-g-marcato-d-e-f-#0",
  "abcjs-visual-wrap-02-stretchlast-1#0",
  "abcjs-visual-wrap-03-piano-wrap#0",
  "abcjs-visual-wrap-04-wrap-quartet#0",
  "abcjs-visual-wrap-05-score-1-2-3-4#0",
  "abcts-bars-graces-and-groups#0",
  "abcts-bars-graces-and-groups#1",
  "abcts-bars-graces-and-groups#10",
  "abcts-bars-graces-and-groups#11",
  "abcts-bars-graces-and-groups#12",
  "abcts-bars-graces-and-groups#13",
  "abcts-bars-graces-and-groups#14",
  "abcts-bars-graces-and-groups#15",
  "abcts-bars-graces-and-groups#16",
  "abcts-bars-graces-and-groups#17",
  "abcts-bars-graces-and-groups#18",
  "abcts-bars-graces-and-groups#2",
  "abcts-bars-graces-and-groups#20",
  "abcts-bars-graces-and-groups#21",
  "abcts-bars-graces-and-groups#22",
  "abcts-bars-graces-and-groups#23",
  "abcts-bars-graces-and-groups#24",
  "abcts-bars-graces-and-groups#25",
  "abcts-bars-graces-and-groups#26",
  "abcts-bars-graces-and-groups#27",
  "abcts-bars-graces-and-groups#28",
  "abcts-bars-graces-and-groups#29",
  "abcts-bars-graces-and-groups#3",
  "abcts-bars-graces-and-groups#30",
  "abcts-bars-graces-and-groups#31",
  "abcts-bars-graces-and-groups#32",
  "abcts-bars-graces-and-groups#33",
  "abcts-bars-graces-and-groups#34",
  "abcts-bars-graces-and-groups#35",
  "abcts-bars-graces-and-groups#36",
  "abcts-bars-graces-and-groups#37",
  "abcts-bars-graces-and-groups#38",
  "abcts-bars-graces-and-groups#39",
  "abcts-bars-graces-and-groups#4",
  "abcts-bars-graces-and-groups#40",
  "abcts-bars-graces-and-groups#5",
  "abcts-bars-graces-and-groups#6",
  "abcts-bars-graces-and-groups#7",
  "abcts-bars-graces-and-groups#8",
  "abcts-bars-graces-and-groups#9",
  "abcts-clef-midmeasure#0",
  "abcts-clef-midmeasure#1",
  "abcts-clef-midmeasure#10",
  "abcts-clef-midmeasure#11",
  "abcts-clef-midmeasure#12",
  "abcts-clef-midmeasure#13",
  "abcts-clef-midmeasure#14",
  "abcts-clef-midmeasure#15",
  "abcts-clef-midmeasure#16",
  "abcts-clef-midmeasure#17",
  "abcts-clef-midmeasure#18",
  "abcts-clef-midmeasure#19",
  "abcts-clef-midmeasure#2",
  "abcts-clef-midmeasure#20",
  "abcts-clef-midmeasure#21",
  "abcts-clef-midmeasure#3",
  "abcts-clef-midmeasure#4",
  "abcts-clef-midmeasure#5",
  "abcts-clef-midmeasure#6",
  "abcts-clef-midmeasure#7",
  "abcts-clef-midmeasure#8",
  "abcts-clef-midmeasure#9",
  "abcts-decorations#0",
  "abcts-decorations#1",
  "abcts-decorations#2",
  "abcts-decorations#3",
  "abcts-decorations#4",
  "abcts-decorations#5",
  "abcts-directives#0",
  "abcts-directives#1",
  "abcts-directives#2",
  "abcts-directives#3",
  "abcts-directives#4",
  "abcts-directives#5",
  "abcts-directives#6",
  "abcts-directives#7",
  "abcts-directives#8",
  "abcts-directives#9",
  "abcts-directives-2#0",
  "abcts-directives-2#1",
  "abcts-directives-2#2",
  "abcts-directives-2#3",
  "abcts-directives-2#4",
  "abcts-directives-2#5",
  "abcts-endings#0",
  "abcts-endings#1",
  "abcts-endings#5",
  "abcts-endings#6",
  "abcts-endings#7",
  "abcts-grace-order-and-lanes#0",
  "abcts-grace-order-and-lanes#1",
  "abcts-grace-order-and-lanes#10",
  "abcts-grace-order-and-lanes#11",
  "abcts-grace-order-and-lanes#12",
  "abcts-grace-order-and-lanes#13",
  "abcts-grace-order-and-lanes#14",
  "abcts-grace-order-and-lanes#15",
  "abcts-grace-order-and-lanes#16",
  "abcts-grace-order-and-lanes#17",
  "abcts-grace-order-and-lanes#18",
  "abcts-grace-order-and-lanes#19",
  "abcts-grace-order-and-lanes#2",
  "abcts-grace-order-and-lanes#20",
  "abcts-grace-order-and-lanes#21",
  "abcts-grace-order-and-lanes#22",
  "abcts-grace-order-and-lanes#23",
  "abcts-grace-order-and-lanes#24",
  "abcts-grace-order-and-lanes#25",
  "abcts-grace-order-and-lanes#26",
  "abcts-grace-order-and-lanes#27",
  "abcts-grace-order-and-lanes#28",
  "abcts-grace-order-and-lanes#3",
  "abcts-grace-order-and-lanes#4",
  "abcts-grace-order-and-lanes#5",
  "abcts-grace-order-and-lanes#6",
  "abcts-grace-order-and-lanes#7",
  "abcts-grace-order-and-lanes#8",
  "abcts-grace-order-and-lanes#9",
  "abcts-grace-tie#0",
  "abcts-grace-tie#1",
  "abcts-grace-tie#2",
  "abcts-grace-tie#3",
  "abcts-grace-tie#4",
  "abcts-grace-tie#5",
  "abcts-grace-tie#6",
  "abcts-grace-tie#7",
  "abcts-inline-fields-and-blocks#0",
  "abcts-inline-fields-and-blocks#1",
  "abcts-inline-fields-and-blocks#10",
  "abcts-inline-fields-and-blocks#11",
  "abcts-inline-fields-and-blocks#12",
  "abcts-inline-fields-and-blocks#13",
  "abcts-inline-fields-and-blocks#14",
  "abcts-inline-fields-and-blocks#2",
  "abcts-inline-fields-and-blocks#3",
  "abcts-inline-fields-and-blocks#4",
  "abcts-inline-fields-and-blocks#5",
  "abcts-inline-fields-and-blocks#6",
  "abcts-inline-fields-and-blocks#7",
  "abcts-inline-fields-and-blocks#8",
  "abcts-key-modifiers#0",
  "abcts-key-modifiers#1",
  "abcts-key-modifiers#10",
  "abcts-key-modifiers#11",
  "abcts-key-modifiers#12",
  "abcts-key-modifiers#2",
  "abcts-key-modifiers#3",
  "abcts-key-modifiers#4",
  "abcts-key-modifiers#5",
  "abcts-key-modifiers#6",
  "abcts-key-modifiers#7",
  "abcts-key-modifiers#8",
  "abcts-key-modifiers#9",
  "abcts-keywarn#0",
  "abcts-keywarn#1",
  "abcts-keywarn#2",
  "abcts-last-bar#0",
  "abcts-last-bar#1",
  "abcts-last-bar#2",
  "abcts-ledger-gaps#0",
  "abcts-ledger-gaps#2",
  "abcts-ledger-gaps#3",
  "abcts-ledger-gaps#5",
  "abcts-ledger-gaps-2#0",
  "abcts-ledger-gaps-2#1",
  "abcts-ledger-gaps-2#2",
  "abcts-ledger-gaps-2#3",
  "abcts-ledger-gaps-2#4",
  "abcts-ledger-gaps-2#5",
  "abcts-ledger-gaps-2#6",
  "abcts-ledger-gaps-2#7",
  "abcts-ledger-gaps-3#1",
  "abcts-ledger-gaps-3#2",
  "abcts-ledger-gaps-3#3",
  "abcts-ledger-gaps-3#4",
  "abcts-ledger-gaps-3#5",
  "abcts-ledger-gaps-3#6",
  "abcts-ledger-gaps-3#7",
  "abcts-ledger-gaps-4#0",
  "abcts-ledger-gaps-4#2",
  "abcts-ledger-gaps-4#3",
  "abcts-ledger-gaps-4#4",
  "abcts-ledger-gaps-4#5",
  "abcts-lyric-verses#0",
  "abcts-lyric-verses#1",
  "abcts-lyric-verses#10",
  "abcts-lyric-verses#11",
  "abcts-lyric-verses#2",
  "abcts-lyric-verses#3",
  "abcts-lyric-verses#4",
  "abcts-lyric-verses#5",
  "abcts-lyric-verses#6",
  "abcts-lyric-verses#7",
  "abcts-lyric-verses#8",
  "abcts-lyric-verses#9",
  "abcts-midi#0",
  "abcts-midi#1",
  "abcts-midi#10",
  "abcts-midi#11",
  "abcts-midi#12",
  "abcts-midi#13",
  "abcts-midi#14",
  "abcts-midi#15",
  "abcts-midi#16",
  "abcts-midi#17",
  "abcts-midi#18",
  "abcts-midi#19",
  "abcts-midi#2",
  "abcts-midi#20",
  "abcts-midi#21",
  "abcts-midi#22",
  "abcts-midi#23",
  "abcts-midi#24",
  "abcts-midi#25",
  "abcts-midi#26",
  "abcts-midi#27",
  "abcts-midi#28",
  "abcts-midi#29",
  "abcts-midi#30",
  "abcts-midi#31",
  "abcts-midi#32",
  "abcts-midi#33",
  "abcts-midi#34",
  "abcts-midi#35",
  "abcts-midi#36",
  "abcts-midi#37",
  "abcts-midi#38",
  "abcts-midi#39",
  "abcts-midi#4",
  "abcts-midi#40",
  "abcts-midi#41",
  "abcts-midi#43",
  "abcts-midi#44",
  "abcts-midi#45",
  "abcts-midi#46",
  "abcts-midi#47",
  "abcts-midi#48",
  "abcts-midi#49",
  "abcts-midi#5",
  "abcts-midi#50",
  "abcts-midi#51",
  "abcts-midi#52",
  "abcts-midi#53",
  "abcts-midi#54",
  "abcts-midi#55",
  "abcts-midi#7",
  "abcts-midi#8",
  "abcts-midi#9",
  "abcts-model-gaps#0",
  "abcts-model-gaps#1",
  "abcts-model-gaps#2",
  "abcts-model-gaps#3",
  "abcts-model-gaps#4",
  "abcts-model-gaps#5",
  "abcts-model-gaps#6",
  "abcts-model-gaps#7",
  "abcts-model-gaps#8",
  "abcts-pitch-style#0",
  "abcts-pitch-style#1",
  "abcts-pitch-style#2",
  "abcts-pitch-style#3",
  "abcts-pitch-style#4",
  "abcts-pitch-style#5",
  "abcts-pitch-style#6",
  "abcts-pitch-style#7",
  "abcts-positioning#0",
  "abcts-positioning#1",
  "abcts-positioning#2",
  "abcts-positioning#3",
  "abcts-positioning#4",
  "abcts-positioning#5",
  "abcts-positioning#6",
  "abcts-positioning#7",
  "abcts-rests-and-bars#0",
  "abcts-rests-and-bars#10",
  "abcts-rests-and-bars#11",
  "abcts-rests-and-bars#12",
  "abcts-rests-and-bars#13",
  "abcts-rests-and-bars#14",
  "abcts-rests-and-bars#15",
  "abcts-rests-and-bars#2",
  "abcts-rests-and-bars#3",
  "abcts-rests-and-bars#4",
  "abcts-rests-and-bars#5",
  "abcts-rests-and-bars#6",
  "abcts-rests-and-bars#7",
  "abcts-rests-and-bars#8",
  "abcts-rests-and-bars#9",
  "abcts-shared-staff-rests#0",
  "abcts-shared-staff-rests#1",
  "abcts-shared-staff-rests#2",
  "abcts-slur-shapes#0",
  "abcts-slur-shapes#1",
  "abcts-slur-shapes#2",
  "abcts-slur-shapes#3",
  "abcts-slur-shapes#4",
  "abcts-slur-shapes#5",
  "abcts-slur-shapes#6",
  "abcts-slur-shapes#7",
  "abcts-slur-shapes#8",
  "abcts-slur-shapes#9",
  "abcts-stafflines-and-modifiers#0",
  "abcts-stafflines-and-modifiers#1",
  "abcts-stafflines-and-modifiers#10",
  "abcts-stafflines-and-modifiers#11",
  "abcts-stafflines-and-modifiers#12",
  "abcts-stafflines-and-modifiers#13",
  "abcts-stafflines-and-modifiers#14",
  "abcts-stafflines-and-modifiers#15",
  "abcts-stafflines-and-modifiers#16",
  "abcts-stafflines-and-modifiers#17",
  "abcts-stafflines-and-modifiers#18",
  "abcts-stafflines-and-modifiers#19",
  "abcts-stafflines-and-modifiers#2",
  "abcts-stafflines-and-modifiers#20",
  "abcts-stafflines-and-modifiers#21",
  "abcts-stafflines-and-modifiers#22",
  "abcts-stafflines-and-modifiers#23",
  "abcts-stafflines-and-modifiers#24",
  "abcts-stafflines-and-modifiers#25",
  "abcts-stafflines-and-modifiers#26",
  "abcts-stafflines-and-modifiers#27",
  "abcts-stafflines-and-modifiers#28",
  "abcts-stafflines-and-modifiers#29",
  "abcts-stafflines-and-modifiers#3",
  "abcts-stafflines-and-modifiers#30",
  "abcts-stafflines-and-modifiers#31",
  "abcts-stafflines-and-modifiers#32",
  "abcts-stafflines-and-modifiers#33",
  "abcts-stafflines-and-modifiers#34",
  "abcts-stafflines-and-modifiers#35",
  "abcts-stafflines-and-modifiers#36",
  "abcts-stafflines-and-modifiers#37",
  "abcts-stafflines-and-modifiers#38",
  "abcts-stafflines-and-modifiers#39",
  "abcts-stafflines-and-modifiers#4",
  "abcts-stafflines-and-modifiers#40",
  "abcts-stafflines-and-modifiers#41",
  "abcts-stafflines-and-modifiers#42",
  "abcts-stafflines-and-modifiers#43",
  "abcts-stafflines-and-modifiers#44",
  "abcts-stafflines-and-modifiers#45",
  "abcts-stafflines-and-modifiers#46",
  "abcts-stafflines-and-modifiers#47",
  "abcts-stafflines-and-modifiers#48",
  "abcts-stafflines-and-modifiers#49",
  "abcts-stafflines-and-modifiers#5",
  "abcts-stafflines-and-modifiers#6",
  "abcts-stafflines-and-modifiers#7",
  "abcts-stafflines-and-modifiers#8",
  "abcts-stafflines-and-modifiers#9",
  "abcts-staffnonote-and-directives#0",
  "abcts-staffnonote-and-directives#1",
  "abcts-staffnonote-and-directives#10",
  "abcts-staffnonote-and-directives#11",
  "abcts-staffnonote-and-directives#12",
  "abcts-staffnonote-and-directives#13",
  "abcts-staffnonote-and-directives#14",
  "abcts-staffnonote-and-directives#15",
  "abcts-staffnonote-and-directives#16",
  "abcts-staffnonote-and-directives#2",
  "abcts-staffnonote-and-directives#3",
  "abcts-staffnonote-and-directives#4",
  "abcts-staffnonote-and-directives#5",
  "abcts-staffnonote-and-directives#6",
  "abcts-staffnonote-and-directives#7",
  "abcts-staffnonote-and-directives#8",
  "abcts-staffnonote-and-directives#9",
  "abcts-start-char#0",
  "abcts-tempo-rung#0",
  "abcts-tempo-rung#1",
  "abcts-tempo-rung#2",
  "abcts-tempo-rung#3",
  "abcts-text-udef-parts-overlays#0",
  "abcts-text-udef-parts-overlays#1",
  "abcts-text-udef-parts-overlays#10",
  "abcts-text-udef-parts-overlays#11",
  "abcts-text-udef-parts-overlays#12",
  "abcts-text-udef-parts-overlays#13",
  "abcts-text-udef-parts-overlays#14",
  "abcts-text-udef-parts-overlays#15",
  "abcts-text-udef-parts-overlays#16",
  "abcts-text-udef-parts-overlays#17",
  "abcts-text-udef-parts-overlays#18",
  "abcts-text-udef-parts-overlays#19",
  "abcts-text-udef-parts-overlays#2",
  "abcts-text-udef-parts-overlays#20",
  "abcts-text-udef-parts-overlays#21",
  "abcts-text-udef-parts-overlays#22",
  "abcts-text-udef-parts-overlays#23",
  "abcts-text-udef-parts-overlays#24",
  "abcts-text-udef-parts-overlays#25",
  "abcts-text-udef-parts-overlays#26",
  "abcts-text-udef-parts-overlays#27",
  "abcts-text-udef-parts-overlays#28",
  "abcts-text-udef-parts-overlays#29",
  "abcts-text-udef-parts-overlays#3",
  "abcts-text-udef-parts-overlays#30",
  "abcts-text-udef-parts-overlays#31",
  "abcts-text-udef-parts-overlays#32",
  "abcts-text-udef-parts-overlays#33",
  "abcts-text-udef-parts-overlays#34",
  "abcts-text-udef-parts-overlays#35",
  "abcts-text-udef-parts-overlays#36",
  "abcts-text-udef-parts-overlays#37",
  "abcts-text-udef-parts-overlays#38",
  "abcts-text-udef-parts-overlays#39",
  "abcts-text-udef-parts-overlays#4",
  "abcts-text-udef-parts-overlays#40",
  "abcts-text-udef-parts-overlays#41",
  "abcts-text-udef-parts-overlays#42",
  "abcts-text-udef-parts-overlays#43",
  "abcts-text-udef-parts-overlays#44",
  "abcts-text-udef-parts-overlays#45",
  "abcts-text-udef-parts-overlays#46",
  "abcts-text-udef-parts-overlays#47",
  "abcts-text-udef-parts-overlays#48",
  "abcts-text-udef-parts-overlays#49",
  "abcts-text-udef-parts-overlays#5",
  "abcts-text-udef-parts-overlays#50",
  "abcts-text-udef-parts-overlays#51",
  "abcts-text-udef-parts-overlays#52",
  "abcts-text-udef-parts-overlays#53",
  "abcts-text-udef-parts-overlays#54",
  "abcts-text-udef-parts-overlays#55",
  "abcts-text-udef-parts-overlays#6",
  "abcts-text-udef-parts-overlays#7",
  "abcts-text-udef-parts-overlays#8",
  "abcts-text-udef-parts-overlays#9",
  "abcts-unknown-clef#0",
  "abcts-unknown-clef#1",
  "abcts-unknown-clef#2",
  "abcts-unknown-clef#3",
  "abcts-unknown-clef#4",
  "abcts-visualtranspose#0",
  "abcts-visualtranspose#1",
  "abcts-visualtranspose#2",
  "abcts-visualtranspose#3",
  "abcts-voice-modifiers#0",
  "abcts-voice-modifiers#1",
  "abcts-voice-modifiers#2",
  "abcts-voice-modifiers#3",
  "abcts-voice-modifiers#4",
  "abcts-voice-scale#0",
  "abcts-voice-scale#1",
  "abcts-voice-scale#10",
  "abcts-voice-scale#11",
  "abcts-voice-scale#2",
  "abcts-voice-scale#3",
  "abcts-voice-scale#4",
  "abcts-voice-scale#5",
  "abcts-voice-scale#6",
  "abcts-voice-scale#7",
  "abcts-voice-scale#8",
  "abcts-voice-scale#9",
  "abcts-voice-style#0",
  "abcts-voice-style#1",
  "abcts-voice-style#2",
  "abcts-voice-style#3",
  "abcts-voice-style#4",
  "abcts-void-notes-and-stray-ties#0",
  "abcts-void-notes-and-stray-ties#1",
  "abcts-void-notes-and-stray-ties#10",
  "abcts-void-notes-and-stray-ties#11",
  "abcts-void-notes-and-stray-ties#12",
  "abcts-void-notes-and-stray-ties#13",
  "abcts-void-notes-and-stray-ties#14",
  "abcts-void-notes-and-stray-ties#2",
  "abcts-void-notes-and-stray-ties#3",
  "abcts-void-notes-and-stray-ties#4",
  "abcts-void-notes-and-stray-ties#5",
  "abcts-void-notes-and-stray-ties#6",
  "abcts-void-notes-and-stray-ties#7",
  "abcts-void-notes-and-stray-ties#8",
  "abcts-void-notes-and-stray-ties#9",
  "abcts-vskip#0",
  "abcts-vskip#1",
  "abcts-vskip#2",
];

/**
 * How many non-divergent fixtures may still differ. **It may only fall.** 14 when this gate
 * landed over ALL 691 tunes — 14 when it covered only the 231 tune-0s, and widening to the
 * other 460 added 23. The families left are named in `/tmp/abcts-midi-bytes.txt`; the
 * largest is `%%staffnonote 0` over pure rests, where abcjs drops every staff and emits NO
 * TRACKS and we emit one per voice.
 */
const OPEN_CEILING = 15;

const PREFIX = "data:audio/midi,";

/** The file as a list of BYTES — `midi-file-ranked`'s decode, and abcjs's own. */
function bytes(data: string): string[] {
  const body = data
    .replace(PREFIX, "")
    .replace(/MThd/g, "%4d%54%68%64")
    .replace(/MTrk/g, "%4d%54%72%6b");
  const out: string[] = [];
  for (let i = 0; i + 2 < body.length + 1; i += 3)
    out.push(body.substring(i + 1, i + 3).toLowerCase());
  return out;
}

interface Diff {
  readonly matched: number;
  readonly where: string;
}

function firstDifference(got: string, want: string): Diff | null {
  if (got === want) return null;
  if (!got.startsWith(PREFIX))
    return { matched: 0, where: `no \`${PREFIX}\` prefix: ${got.slice(0, 60)}` };
  if (!want.startsWith(PREFIX))
    return { matched: 0, where: `abcjs produced no file: ${want.slice(0, 60)}` };
  const a = bytes(got);
  const b = bytes(want);
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i += 1) {
    if (a[i] !== b[i]) {
      const from = Math.max(0, i - 6);
      return {
        matched: i,
        where:
          `byte ${i}\n      ours  …${a.slice(from, i).join(" ")} [${a[i]}] ${a.slice(i + 1, i + 7).join(" ")}…` +
          `\n      abcjs …${b.slice(from, i).join(" ")} [${b[i]}] ${b.slice(i + 1, i + 7).join(" ")}…`,
      };
    }
  }
  return {
    matched: n,
    where:
      a.length > b.length
        ? `${a.length} bytes, abcjs ${b.length}: we add ${a.slice(n, n + 8).join(" ")}…`
        : `${a.length} bytes, abcjs ${b.length}: we drop ${b.slice(n, n + 8).join(" ")}…`,
  };
}

const SLUGS = Object.keys(oracle.midi).sort();

/**
 * ⚠️ **EVERY TUNE, THROUGH THE OBJECT ENTRY POINT.** A key is `<slug>#<tune>`.
 * `getMidiFile` on a STRING is `renderEngine(callback, "*", …)` and yields the FIRST tune
 * only, which left 460 of the corpus's 691 tunes never compared. The other arm takes ONE
 * TUNE OBJECT (`synth/get-midi-file.js:40`), so `parseOnly` then one call per tune reaches
 * all of them — and **that arm was broken here until 2026-09-05**, throwing
 * `tunes.map is not a function`, so the entry point needed to widen this gate was itself
 * the first thing widening found.
 */
const parsedOf = new Map<string, ReturnType<typeof parseOnly>>();
const ours = (key: string): string => {
  const [slug, at] = key.split("#");
  try {
    if (!parsedOf.has(slug ?? ""))
      parsedOf.set(
        slug ?? "",
        parseOnly(readFileSync(join(fixtures, `${slug}.abc`), "utf-8")),
      );
    const tune = parsedOf.get(slug ?? "")?.[Number(at)];
    if (tune === undefined) return "NO SUCH TUNE";
    const r = synth.getMidiFile(tune, { midiOutputType: "encoded" });
    const first = Array.isArray(r) ? r[0] : r;
    return typeof first === "string" ? first : `NOT A STRING: ${typeof first}`;
  } catch (e) {
    return `THREW: ${e instanceof Error ? e.message : String(e)}`;
  }
};

const ROWS = SLUGS.map((slug) => ({
  slug,
  diff: firstDifference(ours(slug), oracle.midi[slug] ?? "(absent)"),
}));

describe("the MIDI file, byte for byte against abcjs 6.7.0", () => {
  /**
   * ⚠️ **THE ORACLE'S VERSION IS ASSERTED, NOT ASSUMED.** `CLAUDE.md` records
   * `harvest-abcjs-goldens.mjs` silently rebaselining the SVG byte gate against 6.6.3 — a
   * harvester whose version was a default rather than a statement moves the TARGET, and a
   * gate cannot see its own target move.
   */
  it("is generated from abcjs 6.7.0", () => {
    expect(oracle.abcjs).toBe("6.7.0");
    expect(SLUGS.length).toBeGreaterThan(600);
  });

  /**
   * **THE RATCHET.** Every slug that is byte-exact must stay so; it grows and never shrinks.
   * `svg-bytes` learned why the hard way — seven named slugs could not defend eighty-nine,
   * and twice a fixture went from exact to differing WHILE THE AGGREGATE IMPROVED.
   */
  it("keeps every byte-exact fixture byte-exact", () => {
    const broken = ROWS.filter(
      (r) => PASSING.includes(r.slug) && r.diff !== null,
    ).map((r) => `${r.slug}: ${r.diff?.where.split("\n")[0]}`);
    expect(broken).toEqual([]);
  });

  it("has no differing fixture that is not ruled divergent", () => {
    const open = ROWS.filter(
      (r) => r.diff !== null && !DIVERGENT.includes(r.slug),
    ).sort((a, b) => (b.diff?.matched ?? 0) - (a.diff?.matched ?? 0));

    const report = [
      `abcts vs abcjs ${oracle.abcjs}, MIDI file bytes, ${SLUGS.length} tunes`,
      `${open.length} differing (${DIVERGENT.length} ruled divergent)`,
      "",
      ...open.map((r) => `  ${r.slug}  matched ${r.diff?.matched}\n      ${r.diff?.where}\n`),
    ].join("\n");
    writeFileSync("/tmp/abcts-midi-bytes.txt", `${report}\n`);

    // Ratcheted by COUNT while the tail is worked down, and by NAME above. The count may
    // only fall; a row that closes is added to PASSING in the same commit.
    expect(open.length, `see /tmp/abcts-midi-bytes.txt\n${report.slice(0, 2000)}`).toBeLessThanOrEqual(OPEN_CEILING);
  });

  /** A slug ruled divergent must actually differ, or the ruling is stale. */
  it("has no stale divergent ruling", () => {
    const agreeing = DIVERGENT.filter(
      (slug) => ROWS.find((r) => r.slug === slug)?.diff === null,
    );
    expect(agreeing).toEqual([]);
  });
});
