import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { synth } from "../src/compat/index.js";

/**
 * **`midiRenderer` — THE MIDI FILE WRITER, DRIVEN DIRECTLY.**
 *
 * The oracle is `tests/corpus-midi-renderer/golden.json`, generated by RUNNING abcjs 6.7.0
 * through the SAME eight scripts (`scripts/harvest-abcjs-midi-renderer.mjs`) and recording
 * `getData()` — the whole percent-encoded `data:audio/midi,` string — after each. That is
 * the writer's entire observable output, so a mismatch names the call that diverged.
 *
 * **THE WRITER IS THE ONE `getMidiFile` ALREADY DRIVES**, so this exposes the walk rather
 * than copying it: the same object, the same bytes the MIDI file gate holds.
 *
 * Four rules the script pins, each abcjs's own:
 *
 * - **`setTempo` AND `setGlobalInfo` FIRE ONLY ON THE FIRST TRACK** — both open with
 *   `if (this.trackcount === 0)`.
 * - **A KEY IS COUNTED, NOT DERIVED**: one per `sharp`, or 256 less one per `flat`, with
 *   `%01` for mode `"m"`.
 * - **A MICROTONE BENDS THE PITCH WHEEL AND BENDS IT BACK** at the note's end, each at zero
 *   duration.
 * - **A METER WITH NO CLOCK ENTRY WRITES NO TIME SIGNATURE AT ALL** — 7/8 is legal and has
 *   none.
 */
const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-midi-renderer", "golden.json"), "utf-8"),
) as [string, string][];

type Renderer = ReturnType<typeof synth.midiRenderer>;

/** THE SCRIPT, verbatim from the harvester. */
const script = (): [string, string][] => {
  const log: [string, string][] = [];
  const run = (label: string, fn: () => Renderer): void => {
    log.push([label, fn().getData()]);
  };
  const make = synth.midiRenderer;

  run("setTempo alone", () => {
    const m = make();
    m.setTempo(120);
    return m;
  });
  run("setTempo twice", () => {
    const m = make();
    m.setTempo(120);
    m.setTempo(90);
    return m;
  });
  run("setGlobalInfo", () => {
    const m = make();
    m.setGlobalInfo(
      144,
      "A tune",
      { accidentals: [{ acc: "sharp" }, { acc: "sharp" }], mode: "" },
      { num: 3, den: 4 },
    );
    return m;
  });
  run("setGlobalInfo minor and flats", () => {
    const m = make();
    m.setGlobalInfo(
      60,
      "Flat",
      { accidentals: [{ acc: "flat" }, { acc: "flat" }, { acc: "flat" }], mode: "m" },
      { num: 4, den: 4 },
    );
    return m;
  });
  run("one note", () => {
    const m = make();
    m.setGlobalInfo(120, "", { accidentals: [] }, { num: 4, den: 4 });
    m.startTrack();
    m.setChannel(0, undefined);
    m.setInstrument(40);
    m.startNote(60, 105, undefined);
    m.addRest(0.25);
    m.endNote(60);
    m.endTrack();
    return m;
  });
  run("rests, text and a second track", () => {
    const m = make();
    m.setGlobalInfo(120, "", { accidentals: [] }, { num: 4, den: 4 });
    m.startTrack();
    m.setText("name", "Voice one");
    m.setChannel(1, 0.5);
    m.setInstrument(0);
    m.addRest(0.5);
    m.startNote(72, 95, undefined);
    m.addRest(0.125);
    m.endNote(72);
    m.addRest(-3);
    m.endTrack();
    m.startTrack();
    m.setChannel(10, -1);
    m.startNote(38, 80, undefined);
    m.addRest(1);
    m.endNote(38);
    m.endTrack();
    return m;
  });
  run("cents", () => {
    const m = make();
    m.setGlobalInfo(120, "", { accidentals: [] }, { num: 4, den: 4 });
    m.startTrack();
    m.setChannel(0, undefined);
    m.startNote(61, 100, 50);
    m.addRest(0.25);
    m.endNote(61);
    m.startNote(63, 100, -50);
    m.addRest(0.25);
    m.endNote(63);
    m.endTrack();
    return m;
  });
  run("7/8 has no clock", () => {
    const m = make();
    m.setGlobalInfo(120, "", { accidentals: [] }, { num: 7, den: 8 });
    return m;
  });
  return log;
};

describe("midiRenderer — the MIDI writer, call by call", () => {
  it("writes what abcjs writes after every call", () => {
    expect(script()).toEqual(GOLDEN);
  });
});
