import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { parseOnly } from "../src/compat/index.js";
import type { AbcLine } from "../src/compat/lines.js";
import { rowsOfTune } from "./parse-only-script.js";

/**
 * **`parseOnly` — THE TUNE THAT WAS NEVER ENGRAVED, AND THE FIELDS THAT PROVES.**
 *
 * The oracle is `tests/corpus-parse-only/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-parse-only.mjs`).
 *
 * abcjs's `parseOnly` is `renderEngine` with a callback that does nothing
 * (`api/abc_tunebook.js:42-54`), so the tune is PARSED and never LAID OUT. Every other
 * oracle in this repo is harvested from a RENDERED tune, which is exactly why nothing here
 * could see the difference: the engraver ADDS to the parse tree and RENAMES it, and a host
 * calling `parseOnly` sees the parser's own answer.
 *
 * **SO THE COMPARISON IS FIELD NAMES, NOT VALUES.** Per tune, the union of own property
 * names per `el_type` — plus what the staff furniture's `el_type` says, which is the
 * rename. The values a RENDERED tune carries are already held by `tune.lines`'s character
 * gate and by `synth.sequence`.
 *
 * ⚠️ **`undefined` IS NOT A FIELD.** `exactOptionalPropertyTypes` means our side omits a
 * key where abcjs sometimes assigns `undefined` to it, and counting those would report a
 * difference no host can observe.
 */
const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-parse-only", "golden.json"), "utf-8"),
) as Record<string, string[]>;

const config = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "abcts.config.json"), "utf-8"),
) as { corpus: string };

const DIRS: Record<string, string> = {
  repo: join(import.meta.dirname, "corpus-abcjs", "fixtures"),
  sib: join(import.meta.dirname, "..", config.corpus),
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const table = (): Row[] => {
  const out: Row[] = [];
  const cache = new Map<string, string[][]>();
  for (const [slug, want] of Object.entries(GOLDEN)) {
    const at = slug.indexOf("/");
    const corpus = slug.slice(0, at);
    const rest = slug.slice(at + 1);
    const cut = rest.lastIndexOf("-tune");
    const file = rest.slice(0, cut);
    const index = Number(rest.slice(cut + "-tune".length));
    const key = `${corpus}/${file}`;
    let all = cache.get(key);
    if (all === undefined) {
      const abc = readFileSync(join(DIRS[corpus] ?? "", `${file}.abc`), "utf-8");
      all = parseOnly(abc).map((tune) => rowsOfTune(tune as { lines?: readonly AbcLine[] }));
      cache.set(key, all);
    }
    const got = all[index] ?? [];
    let agree = 0;
    let first = "";
    for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
      if (want[i] !== undefined && want[i] === got[i]) agree += 1;
      else if (first === "")
        first = `abcjs ${JSON.stringify(want[i])} ours ${JSON.stringify(got[i])}`;
    }
    out.push({ slug, agree, total: want.length, first });
  }
  return out;
};

/** Every fixture directory the harvester walked, so a new one cannot be missed. */
const fixtureCount = (): number =>
  Object.values(DIRS).reduce(
    (n, dir) => n + readdirSync(dir).filter((f) => f.endsWith(".abc")).length,
    0,
  );

describe("parseOnly — the tune that was never engraved", () => {
  const rows = table();

  it("writes the ranked table", () => {
    const off = rows
      .filter((r) => r.agree < r.total)
      .sort((a, b) => b.total - b.agree - (a.total - a.agree));
    const agree = rows.reduce((t, r) => t + r.agree, 0);
    const total = rows.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-parse-only-ranked.txt",
      `${[
        `${off.length} of ${rows.length} tunes differ; ${agree} of ${total} rows agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(56)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(fixtureCount()).toBeGreaterThan(200);
  });

  it("the whole corpus agrees on at least the rows it did", () => {
    const agree = rows.reduce((t, r) => t + r.agree, 0);
    expect(agree).toBeGreaterThanOrEqual(308);
  });
});
