import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";

/**
 * **`engraver.selectables` — 389 ENTRIES ACROSS FOUR CASES.**
 *
 * The oracle is `tests/corpus-selection/golden.json`, generated by RUNNING abcjs 6.7.0 over
 * the four cases harvested out of its own `tests/visual/selection.test.js`
 * (`scripts/harvest-abcjs-selection.mjs`). Every row is `{draggable, svgEl, abcEl}`, and
 * what the test FILE claims is carried beside it in `testFileSays` — it disagrees with
 * abcjs on eleven rows, nine of them a font-height fallback in the golden generator and two
 * a clef-octave transposition 6.7.0 applies only to `treble±8`/`bass±8`.
 *
 * **`size` IS NOT GATED, AND THAT IS STATED RATHER THAN FUDGED.** It is `svgEl.getBBox()`
 * on a GROUP — the browser's ink measurement of glyph outlines. jsdom implements it for
 * nothing at all and the golden generator stubs it for `<text>`/`<tspan>` only, so no
 * oracle for it can be produced here; the test file's numbers are kept in the corpus and
 * nothing compares them.
 *
 * **HALF OF THIS GATE WAS ALREADY PROVEN BEFORE IT EXISTED.** `data-index` is byte-exact on
 * all 356 sibling rows and all 188 in-repo ones, so the ORDER and the COUNT of the array
 * follow a walk that is already right; what this measures is the `abcelem` each entry
 * carries.
 */
const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-selection", "golden.json"),
    "utf-8",
  ),
) as {
  slug: string;
  abc: string;
  options: { selectTypes?: boolean | string[] };
  audio: boolean;
  rows: {
    draggable: boolean;
    svgEl: Record<string, string>;
    abcEl: Record<string, unknown>;
  }[];
}[];

/** Cases whose every row agrees. Grows, never shrinks. */
const PASSING: readonly string[] = ["selection-clefs", "selection-tempo"];

/** Deep equality that ignores KEY ORDER, as `chai.assert.deepStrictEqual` does. */
const same = (a: unknown, b: unknown): boolean => {
  if (a === b) return true;
  if (Array.isArray(a) || Array.isArray(b))
    return (
      Array.isArray(a) &&
      Array.isArray(b) &&
      a.length === b.length &&
      a.every((x, i) => same(x, b[i]))
    );
  if (typeof a !== "object" || typeof b !== "object" || a === null || b === null)
    return false;
  const ka = Object.keys(a).sort();
  const kb = Object.keys(b).sort();
  return (
    ka.join() === kb.join() &&
    ka.every((k) =>
      same(
        (a as Record<string, unknown>)[k],
        (b as Record<string, unknown>)[k],
      ),
    )
  );
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly ours: number;
  readonly first: readonly string[];
}

const table = (): Row[] =>
  GOLDEN.map((c) => {
    const tune = renderAbc("*", c.abc, c.options)[0];
    if (tune === undefined)
      return { slug: c.slug, agree: 0, total: c.rows.length, ours: 0, first: [] };
    if (c.audio) tune.setUpAudio();
    const ours = tune.getSelectableArray();
    let agree = 0;
    const first: string[] = [];
    c.rows.forEach((want, i) => {
      const got = ours[i];
      const mine =
        got === undefined
          ? undefined
          : {
              draggable: got.isDraggable,
              svgEl: Object.fromEntries(
                got.svgEl.attributes.map((a) => [a.nodeName, a.nodeValue]),
              ),
              abcEl: got.absEl.abcelem as unknown,
            };
      if (mine !== undefined && same(mine, want)) agree += 1;
      else if (first.length < 3) {
        first.push(
          `    [${i}] abcjs ${JSON.stringify(want)}\n        ours  ${JSON.stringify(mine ?? null)}`,
        );
      }
    });
    return {
      slug: c.slug,
      agree,
      total: c.rows.length,
      ours: ours.length,
      first,
    };
  });

describe("engraver.selectables", () => {
  const rows = table();

  it("writes the ranked table", () => {
    const off = rows.filter((r) => r.agree < r.total);
    const agree = rows.reduce((t, r) => t + r.agree, 0);
    const total = rows.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-selection-ranked.txt",
      [
        `${off.length} of ${rows.length} cases differ; ${agree} of ${total} selectables agree`,
        "",
        ...off.map(
          (r) =>
            `  ${r.slug.padEnd(20)} ${r.agree}/${r.total} rows agree, ${r.ours} emitted\n${r.first.join("\n")}`,
        ),
      ].join("\n") + "\n",
    );
    expect(rows.length).toBe(4);
  });

  it("every ratcheted case agrees on every row", () => {
    expect(
      rows
        .filter((r) => PASSING.includes(r.slug))
        .filter((r) => r.agree < r.total)
        .map((r) => `${r.slug} ${r.agree}/${r.total}`),
    ).toEqual([]);
  });

  /** A floor, not a target: it moves up as the projection grows and never down. */
  it("agrees on at least the rows it did", () => {
    expect(rows.reduce((t, r) => t + r.agree, 0)).toBeGreaterThanOrEqual(356);
  });

  /**
   * **THE SELECTABLE ARRAY AND `tune.lines` HAND BACK THE SAME OBJECTS.**
   *
   * abcjs's two surfaces agree by IDENTITY — its engraver holds the very parse element
   * `tune.lines` holds — and this session's whole design rests on reproducing that: the
   * drawing carries a reference to the model event, the projection is built once, and the
   * engrave-time and flattener fields are stamped on one object and read through the other.
   * Nothing else in the suite would notice if that quietly became a copy, and a host would:
   * it would stamp a note through `getSelectableArray()` and read `tune.lines` back
   * unchanged.
   */
  it("hands the same element object to both surfaces", () => {
    const abc = "X:1\nT:t\nM:4/4\nL:1/4\nK:C\nCDEF|GABc|\n";
    const tune = renderAbc("*", abc, {})[0];
    expect(tune).toBeDefined();
    if (tune === undefined) return;
    const first = tune.getSelectableArray()[0];
    expect(first).toBeDefined();
    // AT its own `startChar`, not one past it: in `CDEF` every note is ONE character, so
    // `startChar + 1` is the NEXT element — which is what the first version of this test
    // asked for and then reported as a broken identity.
    const fromLines = tune.getElementFromChar(first?.absEl.abcelem.startChar ?? 0);
    expect(fromLines).toBe(first?.absEl.abcelem);
    // …and a stamp through one is visible through the other, which is what a host does.
    tune.setUpAudio();
    expect(fromLines?.midiPitches).toBeDefined();
  });

  /**
   * **THE COUNT IS THE HALF ALREADY PROVEN.** With the default `selectTypes` the array is
   * the notes and rests, in drawing order — which is what `data-index` numbers, and that
   * is byte-exact against abcjs on every fixture of both corpora.
   */
  it("emits abcjs's own number of selectables when only notes can be selected", () => {
    const noteCases = GOLDEN.filter((c) => c.options.selectTypes !== true);
    expect(noteCases.length).toBeGreaterThan(0);
    expect(
      noteCases.map((c) => {
        const tune = renderAbc("*", c.abc, c.options)[0];
        return `${c.slug} ${tune?.getSelectableArray().length ?? -1}`;
      }),
    ).toEqual(noteCases.map((c) => `${c.slug} ${c.rows.length}`));
  });
});
