import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { parseOnly } from "../src/compat/index.js";
import { sequenceOf, type SequenceRow, type SequenceTune } from "../src/compat/sequence.js";

/**
 * **`synth.sequence` — THE INTERMEDIATE, ROW FOR ROW.**
 *
 * The oracle is `tests/corpus-sequence/golden.json`, generated by RUNNING abcjs 6.7.0 over
 * every fixture (`scripts/harvest-abcjs-sequence.mjs`) — abcjs's own suite asserts this
 * surface nowhere.
 *
 * **IT IS A SECOND DERIVATION OF THE SAME MUSIC AND THAT IS ITS VALUE.** Our flattener runs
 * over the parse MODEL and never touches the projection; this runs over `tune.lines`, as
 * abcjs's does. The MIDI writer and `setupEvents` were both built on that argument and both
 * found defects the gate beside them could not see.
 *
 * `elem` is dropped on both sides: it is the parse element itself, so it makes the
 * structure cyclic and carries the whole engraving with it. The keys are SORTED, because
 * the row's contract is its fields rather than the order they were assigned in.
 */
type Golden = Record<string, SequenceRow[][]>;

const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-sequence", "golden.json"), "utf-8"),
) as Golden;

const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/** The same reduction the harvester makes. */
const row = (el: SequenceRow): Record<string, unknown> => {
  const out: Record<string, unknown> = { el_type: el.el_type };
  for (const key of Object.keys(el).sort()) {
    // **A KEY WHOSE VALUE IS `undefined` IS NOT A KEY** — abcjs pushes
    // `{el_type, value, octaveShift}` for a `%%MIDI bassprog` with one parameter, and the
    // harvest's own JSON drops the second. Ours has to drop it the same way or the row
    // differs by a field neither side can see.
    if (key === "el_type" || key === "elem" || el[key] === undefined) continue;
    out[key] = el[key];
  }
  return out;
};

const near = (a: unknown, b: unknown): boolean => {
  if (typeof a === "number" && typeof b === "number") return Math.abs(a - b) < 0.0000005;
  if (Array.isArray(a) && Array.isArray(b))
    return a.length === b.length && a.every((v, i) => near(v, b[i]));
  if (a !== null && b !== null && typeof a === "object" && typeof b === "object") {
    const ka = Object.keys(a as object);
    const kb = Object.keys(b as object);
    if (ka.length !== kb.length) return false;
    return ka.every((k) =>
      near((a as Record<string, unknown>)[k], (b as Record<string, unknown>)[k]),
    );
  }
  return (a ?? null) === (b ?? null);
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const rows = (): Row[] => {
  const out: Row[] = [];
  for (const [slug, want] of Object.entries(GOLDEN)) {
    const abc = readFileSync(join(IN_REPO, `${slug}.abc`), "utf-8");
    let got: SequenceRow[][] = [];
    try {
      const tune = parseOnly(abc)[0];
      got =
        tune === undefined ? [] : sequenceOf(tune as unknown as SequenceTune, {}).map((v) => v);
    } catch (e) {
      out.push({
        slug,
        agree: 0,
        total: want.reduce((n, v) => n + v.length, 0),
        first: `threw: ${(e as Error).message}`,
      });
      continue;
    }
    let agree = 0;
    let total = 0;
    let first = "";
    for (let v = 0; v < Math.max(want.length, got.length); v += 1) {
      const a = want[v] ?? [];
      const b = (got[v] ?? []).map(row);
      total += a.length;
      for (let i = 0; i < Math.max(a.length, b.length); i += 1) {
        if (near(a[i], b[i])) agree += 1;
        else if (first === "")
          first = `voice ${v} row ${i}: abcjs ${JSON.stringify(a[i])} ours ${JSON.stringify(b[i])}`;
      }
    }
    out.push({ slug, agree, total, first });
  }
  return out;
};

describe("synth.sequence — the intermediate abcjs plays from", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table
      .filter((r) => r.agree < r.total)
      .sort((a, b) => b.total - b.agree - (a.total - a.agree));
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-sequence-ranked.txt",
      `${[
        `${off.length} of ${table.length} tunes differ; ${agree} of ${total} rows agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(56)} ${r.agree}/${r.total}  ${r.first.slice(0, 220)}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(150);
  });

  /**
   * A floor, not a target — it moves up and must never move down.
   *
   * **WHAT IS LEFT IS 21 ROWS AND MOSTLY ONE KNOWN MODEL GAP.** Twenty are
   * `synth-flattener-32`'s quarter tones, where abcjs's `accMap` has seven entries and our
   * `Accidental` has five — microtones are deferred, and this is the surface that says so.
   * The rest are single rows, each measured and named: a pitch with no `highestVert` on an
   * incipit, a per-voice key's accidental `verticalPos`, a `!segno!` on an invisible rest,
   * an annotation's `rel_position`, and a DOTTED tie's `startTie: {style: "dotted"}`.
   *
   * **NINE CLASSES HAVE ALREADY CLOSED BY BEING NAMED HERE** — the staff's voice `title`, a
   * barline's decorations and chord, `V:… transpose=` on the clef, a multi-measure rest's
   * length, `midipitch` from a drummap, `endTie` across a line break, a whole-measure
   * rest's type, `printer_shift`, and the clef, meter and key elements in the stream, which
   * were all pushed as bare markers with a span and nothing else.
   */
  it("the whole corpus agrees on at least the rows it did", () => {
    const agree = table.reduce((t, r) => t + r.agree, 0);
    expect(agree).toBeGreaterThanOrEqual(4774);
  });
});
