import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";

/**
 * **`tune.setupEvents(startingDelay, timeDivider, startingBpm, warp)` — `setTiming`'S WALK
 * WITH ITS FOUR NUMBERS HANDED IN.**
 *
 * The oracle is `tests/corpus-setupevents/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-setupevents.mjs`). The timing gate already holds `setTiming`'s
 * ANSWER at zero — but `setTiming` only ever calls this with the four values IT computed,
 * so nothing there can say what a host choosing its own gets.
 *
 * **AND THE `timeDivider` IS THE ONE THAT MATTERS**: abcjs uses the parameter until the
 * first tempo change and then RECOMPUTES it from the running bpm (`abc_tune.js:438`,
 * `:471`), so a halved one stretches the run up to the first `Q:` and nothing after it.
 * The three parameter sets are the canonical four, a halved divider, and a delayed start
 * with a warp of 2.
 *
 * Four columns per row — `milliseconds`, `millisecondsPerMeasure`, `measureNumber` and
 * `top`. The last is what makes this a JOIN gate rather than a clock one, and **IT OPENED
 * THE GATE AT 145 OF 3,366 ROWS WHILE THE TIMING GATE SAT AT ZERO**: our timing rows carry
 * the CLOCK and nothing else, where abcjs's carry `line`, `top`, `height`, `left`, `width`,
 * `elements`, `startChar`, `endChar`, `startCharArray` and `endCharArray` — everything a
 * playback cursor draws with (`abc_tune.js:298-395`). The timing oracle is harvested from
 * abcjs's own `doWarpTest`, which asserts `milliseconds` and `millisecondsPerMeasure`
 * alone, so no number it printed could ever have named this. **A COMPARISON CAN ONLY CATCH
 * WHAT ITS REPRESENTATION CAN EXPRESS**, again.
 */
const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-setupevents", "golden.json"),
    "utf-8",
  ),
) as Record<string, [number, number, number | null, number | null][]>;

const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const near = (a: number | null, b: number | null): boolean =>
  a === null || b === null ? a === b : Math.abs(a - b) < 0.0005;

const rows = (): Row[] => {
  const out: Row[] = [];
  const cache = new Map<string, string>();
  for (const [key, want] of Object.entries(GOLDEN)) {
    const [file = "", label = ""] = key.split("#");
    let abc = cache.get(file);
    if (abc === undefined) {
      abc = readFileSync(join(IN_REPO, `${file}.abc`), "utf-8");
      cache.set(file, abc);
    }
    const tune = renderAbc(["*"], abc, {})[0];
    if (tune === undefined) continue;
    const bpm = tune.getBpm();
    const divider = (tune.getBeatLength() * bpm) / 60;
    const params: Record<string, [number, number, number, number]> = {
      canonical: [0, divider, bpm, 1],
      "half-divider": [0, divider / 2, bpm, 1],
      "delayed-warped": [1.5, divider, bpm, 2],
    };
    const p = params[label];
    if (p === undefined) continue;
    const got = tune.setupEvents(p[0], p[1], p[2], p[3]) as unknown as {
      milliseconds: number;
      millisecondsPerMeasure: number;
      measureNumber?: number;
      top?: number;
    }[];
    let agree = 0;
    let first = "";
    for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
      const w = want[i];
      const g = got[i];
      const same =
        w !== undefined &&
        g !== undefined &&
        near(w[0], g.milliseconds) &&
        near(w[1], g.millisecondsPerMeasure) &&
        (w[2] ?? null) === (g.measureNumber ?? null) &&
        near(w[3], g.top ?? null);
      if (same) agree += 1;
      else if (first === "")
        first = `row ${i}: abcjs ${JSON.stringify(w)} ours ${JSON.stringify(
          g === undefined
            ? undefined
            : [g.milliseconds, g.millisecondsPerMeasure, g.measureNumber ?? null, g.top ?? null],
        )}`;
    }
    out.push({ slug: key, agree, total: want.length, first });
  }
  return out;
};

describe("tune.setupEvents — the walk with its numbers handed in", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table
      .filter((r) => r.agree < r.total)
      .sort((a, b) => a.total - a.agree - (b.total - b.agree));
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-setupevents-ranked.txt",
      `${[
        `${off.length} of ${table.length} cases differ; ${agree} of ${total} rows agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(64)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(150);
  });

  /** A floor, not a target — it moves up as the geometry lands and must never move down. */
  it("the whole corpus agrees on at least the rows it did", () => {
    const agree = table.reduce((t, r) => t + r.agree, 0);
    expect(agree).toBeGreaterThanOrEqual(145);
  });

  /**
   * The CLOCK columns alone, which is what `setTiming`'s own gate covers — this is the
   * half that must be exact today, and it is what proves the `timeDivider` parameter is
   * honoured rather than recomputed.
   */
  it("every case agrees on every millisecond", () => {
    const broken: string[] = [];
    for (const [key, want] of Object.entries(GOLDEN)) {
      const [file = "", label = ""] = key.split("#");
      const abc = readFileSync(join(IN_REPO, `${file}.abc`), "utf-8");
      const tune = renderAbc(["*"], abc, {})[0];
      if (tune === undefined) continue;
      const bpm = tune.getBpm();
      const divider = (tune.getBeatLength() * bpm) / 60;
      const params: Record<string, [number, number, number, number]> = {
        canonical: [0, divider, bpm, 1],
        "half-divider": [0, divider / 2, bpm, 1],
        "delayed-warped": [1.5, divider, bpm, 2],
      };
      const p = params[label];
      if (p === undefined) continue;
      const got = tune.setupEvents(p[0], p[1], p[2], p[3]);
      for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
        const w = want[i];
        const g = got[i];
        if (
          w === undefined ||
          g === undefined ||
          !near(w[0], g.milliseconds) ||
          !near(w[1], g.millisecondsPerMeasure) ||
          (w[2] ?? null) !== (g.measureNumber ?? null)
        ) {
          broken.push(
            `${key} row ${i}: abcjs ${JSON.stringify(w?.slice(0, 3))} ours ${JSON.stringify(
              g === undefined ? undefined : [g.milliseconds, g.millisecondsPerMeasure, g.measureNumber ?? null],
            )}`,
          );
          break;
        }
      }
    }
    expect(broken).toEqual([]);
  });
});
