import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";

/**
 * **`tune.setupEvents(startingDelay, timeDivider, startingBpm, warp)` — `setTiming`'S WALK
 * WITH ITS FOUR NUMBERS HANDED IN, AND EVERY COLUMN OF THE ROW IT BUILDS.**
 *
 * The oracle is `tests/corpus-setupevents/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-setupevents.mjs`). The timing gate already holds `setTiming`'s
 * ANSWER at zero — but that oracle comes from abcjs's own `doWarpTest`, which asserts
 * `milliseconds` and `millisecondsPerMeasure` and nothing else.
 *
 * **IT OPENED AT 174 OF 3,366 ROWS WITH THE TIMING GATE AT ZERO.** A row carries
 * `line`, `top`, `height`, `left`, `width`, `startChar`, `endChar`, `startCharArray` and
 * `endCharArray` as well as the clock (`abc_tune.js:298-395`) — the GEOMETRY a playback
 * cursor draws with, joined to the time. Ours carried the clock alone. **A COMPARISON CAN
 * ONLY CATCH WHAT ITS REPRESENTATION CAN EXPRESS**, and the representation here is the
 * oracle's column list.
 *
 * `elements` is the one column that cannot cross a process boundary — a DOM node per drawn
 * glyph — so its LENGTH is compared, which is what a host counts.
 *
 ⚠️ **THE FLOOR WENT DOWN WHEN `endX` WAS ADDED AS A COLUMN, AND THAT IS A CHANGE OF UNITS
 * RATHER THAN A REGRESSION** — 3,339 of 3,366 became 3,042 of the same 3,366 the moment a
 * fifteenth column was compared. Nothing moved; the gate simply asks more. The three-column
 * clock assertion below is what did not change.
 *
 * **324 ROWS ARE OPEN AND ALL THREE CAUSES ARE MEASURED**, none of them a number to be tuned:
 *
 *   - **21 `startCharArray`: an overlay layer exists on every measure of ours and only
 *     where abcjs's `resolveOverlays` put one.** Our model pads every measure of the tune
 *     to its overlay depth so the renderer can tile the layers; abcjs back-fills only the
 *     lines BEFORE the `&` and leaves the rest alone, so `synth-flattener-21` has three
 *     elements at a time where abcjs has two.
 *   - **297 `endX`: THE SYSTEM'S OWN RIGHT EDGE, which is abcjs's `staffGroup.w`.** Every
 *     row whose successor is on the SAME system is exact, because that value is the next
 *     row's `left`; a row at the END of a system runs out to `lines[el.line].staffGroup.w`
 *     instead, and our `LayoutSystem.width` is not that number. Measured: for a STRETCHED
 *     line abcjs's is our width plus the 15 left margin (755 against 740), and for a SHORT
 *     one it is our width MINUS 15 (315.609 against 330.609) — because our `width` is
 *     `max(musicWidth, proseWidth)` and abcjs's is the cursor its own layout ended at.
 *     Neither the ink's right edge (725 on a stretched line) nor either offset is it in
 *     both cases. The layout would have to record the x it laid the line out to.
 *   - **6 `height`: one system's BOTTOM pitch, and only where a tie hangs below it.**
 *     `synth-timing-10-stretchlast-1` reports −1.0493 against abcjs's −2 on its first
 *     system and −3 on its second, which is exact. Both engines PLACE the two systems
 *     identically — the next system's `absoluteY` agrees to the digit — so this is what
 *     the extent is REPORTED as, not where anything is drawn.
 *
 * Three parameter sets: the canonical four, a HALVED `timeDivider` and a delayed start with
 * a warp of 2. The halved divider is what proved **`timeDivider` IS A DEAD PARAMETER**:
 * abcjs overwrites it before reading a single element (`:459`), so that case is
 * byte-identical to the canonical one.
 */
type Row = readonly [
  milliseconds: number,
  millisecondsPerMeasure: number,
  measureNumber: number | null,
  line: number | null,
  top: number | null,
  height: number | null,
  left: number | null,
  width: number | null,
  startChar: number | null,
  endChar: number | null,
  startCharArray: readonly number[] | null,
  endCharArray: readonly number[] | null,
  measureStart: boolean | null,
  type: string,
  endX: number | null,
  elements: number,
];

const COLUMNS = [
  "milliseconds",
  "millisecondsPerMeasure",
  "measureNumber",
  "line",
  "top",
  "height",
  "left",
  "width",
  "startChar",
  "endChar",
  "startCharArray",
  "endCharArray",
  "measureStart",
  "type",
  "endX",
  "elements",
] as const;

const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-setupevents", "golden.json"),
    "utf-8",
  ),
) as Record<string, Row[]>;

const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/** The abcjs row, as a host sees it. Everything but `elements` is data. */
interface TimingRow {
  readonly type: string;
  readonly milliseconds: number;
  readonly millisecondsPerMeasure: number;
  readonly measureNumber?: number;
  readonly measureStart?: boolean;
  readonly line?: number;
  readonly top?: number;
  readonly height?: number;
  readonly left?: number | null;
  readonly width?: number;
  readonly startChar?: number | null;
  readonly endChar?: number | null;
  readonly startCharArray?: readonly number[];
  readonly endCharArray?: readonly number[];
  readonly endX?: number;
  readonly elements?: readonly unknown[];
}

const near = (a: unknown, b: unknown): boolean => {
  if (typeof a === "number" && typeof b === "number")
    return Math.abs(a - b) < 0.0005;
  if (Array.isArray(a) && Array.isArray(b))
    return a.length === b.length && a.every((v, i) => near(v, b[i]));
  return (a ?? null) === (b ?? null);
};

const ours = (row: TimingRow): readonly unknown[] => [
  row.milliseconds,
  row.millisecondsPerMeasure,
  row.measureNumber ?? null,
  row.line ?? null,
  row.top ?? null,
  row.height ?? null,
  row.left ?? null,
  row.width ?? null,
  row.startChar ?? null,
  row.endChar ?? null,
  row.startCharArray ?? null,
  row.endCharArray ?? null,
  row.measureStart ?? null,
  row.type,
  row.endX ?? null,
  row.elements?.length ?? 0,
];

interface Case {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
  /** Which COLUMN first differs, per row — the work list, counted by name. */
  readonly columns: readonly string[];
}

const run = (key: string): TimingRow[] => {
  const [file = "", label = ""] = key.split("#");
  const abc = readFileSync(join(IN_REPO, `${file}.abc`), "utf-8");
  const tune = renderAbc(["*"], abc, {})[0];
  if (tune === undefined) return [];
  const bpm = tune.getBpm();
  const divider = (tune.getBeatLength() * bpm) / 60;
  const params: Record<string, [number, number, number, number]> = {
    canonical: [0, divider, bpm, 1],
    "half-divider": [0, divider / 2, bpm, 1],
    "delayed-warped": [1.5, divider, bpm, 2],
  };
  const p = params[label];
  if (p === undefined) return [];
  return tune.setupEvents(p[0], p[1], p[2], p[3]) as unknown as TimingRow[];
};

const cases = (): Case[] => {
  const out: Case[] = [];
  for (const [key, want] of Object.entries(GOLDEN)) {
    const got = run(key);
    let agree = 0;
    let first = "";
    const columns: string[] = [];
    for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
      const w = want[i];
      const g = got[i];
      const mine = g === undefined ? undefined : ours(g);
      const bad =
        w === undefined || mine === undefined
          ? [0]
          : COLUMNS.map((_, c) => c).filter((c) => !near(w[c], mine[c]));
      if (bad.length === 0) agree += 1;
      else {
        const c = bad[0] ?? 0;
        columns.push(COLUMNS[c] ?? "?");
        if (first === "")
          first = `row ${i} ${COLUMNS[c]}: abcjs ${JSON.stringify(
            w?.[c],
          )} ours ${JSON.stringify(mine?.[c])}`;
      }
    }
    out.push({ slug: key, agree, total: want.length, first, columns });
  }
  return out;
};

describe("tune.setupEvents — every column of the row", () => {
  const table = cases();

  it("writes the ranked table", () => {
    const off = table
      .filter((r) => r.agree < r.total)
      .sort((a, b) => a.total - a.agree - (b.total - b.agree));
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    const byColumn = new Map<string, number>();
    for (const r of table)
      for (const c of r.columns) byColumn.set(c, (byColumn.get(c) ?? 0) + 1);
    writeFileSync(
      "/tmp/abcts-setupevents-ranked.txt",
      `${[
        `${off.length} of ${table.length} cases differ; ${agree} of ${total} rows agree`,
        "",
        "  FIRST DIFFERING COLUMN, by row:",
        ...[...byColumn.entries()]
          .sort((a, b) => b[1] - a[1])
          .map(([c, n]) => `    ${c.padEnd(24)} ${n}`),
        "",
        ...off.map((r) => `  ${r.slug.padEnd(64)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(150);
  });

  /** A floor, not a target — it moves up as the geometry lands and must never move down. */
  it("the whole corpus agrees on at least the rows it did", () => {
    const agree = table.reduce((t, r) => t + r.agree, 0);
    expect(agree).toBeGreaterThanOrEqual(3042);
  });

  /**
   * The CLOCK columns alone — what `setTiming`'s own gate covers, and the half that must be
   * exact today. It is also what proves the `timeDivider` parameter is ignored rather than
   * honoured, and that `noteFound` resets at every line.
   */
  it("every case agrees on every millisecond and measure number", () => {
    const broken: string[] = [];
    for (const [key, want] of Object.entries(GOLDEN)) {
      const got = run(key);
      for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
        const w = want[i];
        const g = got[i];
        if (
          w === undefined ||
          g === undefined ||
          !near(w[0], g.milliseconds) ||
          !near(w[1], g.millisecondsPerMeasure) ||
          !near(w[2], g.measureNumber ?? null) ||
          !near(w[12], g.measureStart ?? null) ||
          w[13] !== g.type
        ) {
          broken.push(
            `${key} row ${i}: abcjs ${JSON.stringify(w?.slice(0, 3))} ours ${JSON.stringify(
              g === undefined
                ? undefined
                : [g.milliseconds, g.millisecondsPerMeasure, g.measureNumber ?? null],
            )}`,
          );
          break;
        }
      }
    }
    expect(broken).toEqual([]);
  });
});
