import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";
import type { TuneObject } from "../src/compat/index.js";
import { SynthController } from "../src/compat/synth-controller.js";
import { registerAudioContext } from "../src/compat/synth.js";
import {
  CASES,
  type Controller,
  drive,
  driveLoading,
  type El,
  makeBuffer,
  type Step,
} from "./synth-controller-script.js";

/**
 * **`SynthController` — THE STATE MACHINE, GATED BEFORE `CreateSynth` EXISTS.**
 *
 * The oracle is `tests/corpus-synth-controller/golden.json`, generated by RUNNING abcjs
 * 6.7.0 with `CreateSynth` replaced by a RECORDER (`scripts/harvest-abcjs-synth-controller.ts`).
 *
 * **THE CONTROLLER MAKES NO SOUND — IT DECIDES WHEN.** Nine calls go down to the audio
 * class (`init`, `prime`, `start`, `pause`, `seek`, `finished`, `stop`, `download`, and
 * `duration` read back); replace that class on both sides and everything the controller
 * does is comparable: the CALL SEQUENCE into the buffer, the transport bar's state, the
 * `cursorControl` callbacks, and its own fields after every step. abcjs's copy is swapped
 * through `require.cache`; ours takes a factory argument, which is the only line of the
 * port that exists for the gate.
 *
 * The clock is stubbed as in the `TimingCallbacks` gate, so `timer.start()` starts the
 * state machine without a frame ever firing — what is held here is what the CONTROLLER
 * did, not what a browser would have played.
 *
 * ⚠️ **`onWarp` THROWS when the bar has no warp input** — `CreateSynthControl.setWarp` does
 * not null-check where `setTempo` does — and the `no-cursor` case records the throw with
 * the buffer already re-initialised behind it. A port that guarded it would fail here.
 */
const sibling = createRequire(
  join(import.meta.dirname, "..", "..", "abcMusicKit", "Tools", "abcjs-debug", "package.json"),
);
const { JSDOM } = sibling("jsdom") as {
  JSDOM: new (html: string) => { window: Record<string, never> };
};

const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-synth-controller", "golden.json"), "utf-8"),
) as Record<string, Step[]>;

const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

const near = (a: unknown, b: unknown): boolean => {
  if (typeof a === "number" && typeof b === "number") return Math.abs(a - b) < 0.0005;
  if (Array.isArray(a) && Array.isArray(b))
    return a.length === b.length && a.every((v, i) => near(v, b[i]));
  return (a ?? null) === (b ?? null);
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const run = async (): Promise<Row[]> => {
  // The page, the clock and the audio context — the same three the harvester replaced.
  const dom = new JSDOM(
    '<!DOCTYPE html><html><body><div id="bar"></div><div id="paper"></div></body></html>',
  );
  const win = dom.window as unknown as {
    document: { getElementById(id: string): El | null };
    URL: { revokeObjectURL: (u: string) => void };
  };
  win.URL.revokeObjectURL = () => {};
  const g = globalThis as Record<string, unknown>;
  const saved = {
    document: g["document"],
    window: g["window"],
    performance: g["performance"],
    requestAnimationFrame: g["requestAnimationFrame"],
    setTimeout: g["setTimeout"],
    clearTimeout: g["clearTimeout"],
  };
  g["document"] = win.document;
  g["window"] = dom.window;
  g["performance"] = { now: () => 0 };
  g["requestAnimationFrame"] = () => 0;
  g["setTimeout"] = () => 0;
  g["clearTimeout"] = () => {};
  const ac = { state: "running", resume: () => Promise.resolve() };
  registerAudioContext(ac);

  const out: Row[] = [];
  try {
    const tunes = new Map<string, TuneObject>();
    for (const [key, want] of Object.entries(GOLDEN)) {
      const [fixture = "", label = ""] = key.split("#");
      let tune = tunes.get(fixture);
      if (tune === undefined) {
        const abc = readFileSync(join(IN_REPO, `${fixture}.abc`), "utf-8");
        tune = renderAbc(["*"], abc, {})[0] as TuneObject;
        tunes.set(fixture, tune);
      }
      const parent = win.document.getElementById("bar") as El | null;
      if (parent === null) continue;
      const make = (): Controller =>
        new SynthController(makeBuffer as never) as unknown as Controller;
      const shape = CASES.find(([name]) => name === label);
      const got =
        label === "loading"
          ? await driveLoading(make, tune, parent)
          : shape === undefined
            ? null
            : await drive(make, tune, shape[1], shape[2], parent);
      if (got === null) continue;
      let agree = 0;
      let first = "";
      for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
        if (near(want[i], got[i])) agree += 1;
        else if (first === "")
          first = `step ${i}: abcjs ${JSON.stringify(want[i]).slice(0, 200)} ours ${JSON.stringify(got[i]).slice(0, 200)}`;
      }
      out.push({ slug: key, agree, total: want.length, first });
    }
  } finally {
    for (const [k, v] of Object.entries(saved)) g[k] = v;
  }
  return out;
};

describe("SynthController — the transport state machine", async () => {
  const table = await run();

  it("writes the ranked table", () => {
    const off = table.filter((r) => r.agree < r.total);
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-synth-controller-ranked.txt",
      `${[
        `${off.length} of ${table.length} cases differ; ${agree} of ${total} steps agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(56)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBe(10);
  });

  it("every case agrees on every step", () => {
    const broken = table
      .filter((r) => r.agree < r.total)
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken).toEqual([]);
  });
});
