import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";
import type { TuneObject } from "../src/compat/index.js";
import { SynthController, type MidiBuffer } from "../src/compat/synth-controller.js";
import { registerAudioContext } from "../src/compat/synth.js";

/**
 * **`SynthController` — THE STATE MACHINE, GATED BEFORE `CreateSynth` EXISTS.**
 *
 * The oracle is `tests/corpus-synth-controller/golden.json`, generated by RUNNING abcjs
 * 6.7.0 with `CreateSynth` replaced by a RECORDER (`scripts/harvest-abcjs-synth-controller.mjs`).
 *
 * **THE CONTROLLER MAKES NO SOUND — IT DECIDES WHEN.** Nine calls go down to the audio
 * class (`init`, `prime`, `start`, `pause`, `seek`, `finished`, `stop`, `download`, and
 * `duration` read back); replace that class on both sides and everything the controller
 * does is comparable: the CALL SEQUENCE into the buffer, the transport bar's state, the
 * `cursorControl` callbacks, and its own fields after every step. abcjs's copy is swapped
 * through `require.cache`; ours takes a factory argument, which is the only line of the
 * port that exists for the gate.
 *
 * The clock is stubbed as in the `TimingCallbacks` gate, so `timer.start()` starts the
 * state machine without a frame ever firing — what is held here is what the CONTROLLER
 * did, not what a browser would have played.
 *
 * ⚠️ **`onWarp` THROWS when the bar has no warp input** — `CreateSynthControl.setWarp` does
 * not null-check where `setTempo` does — and the `no-cursor` case records the throw with
 * the buffer already re-initialised behind it. A port that guarded it would fail here.
 */
const sibling = createRequire(
  join(import.meta.dirname, "..", "..", "abcMusicKit", "Tools", "abcjs-debug", "package.json"),
);
const { JSDOM } = sibling("jsdom") as {
  JSDOM: new (html: string) => { window: Record<string, never> };
};

type Step = [string, unknown[], unknown[], unknown[], unknown[]];

const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-synth-controller", "golden.json"), "utf-8"),
) as Record<string, Step[]>;

const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/** THE CASES, verbatim from the harvester. */
const CASES: [string, Record<string, boolean> | null, string | null][] = [
  ["all", { displayLoop: true, displayRestart: true, displayPlay: true, displayProgress: true, displayWarp: true }, "full"],
  ["no-control", null, "full"],
  ["no-cursor", { displayLoop: true, displayPlay: true }, null],
  ["subdivisions", {}, "subdivided"],
];

/** THE BUFFER STUB, verbatim from the harvester. */
let bufLog: unknown[] = [];
const makeBuffer = (): MidiBuffer => ({
  duration: 12.5,
  init: (options) => {
    bufLog.push(["init", options.millisecondsPerMeasure, JSON.stringify(options.options)]);
    return Promise.resolve({ status: "ok", loaded: ["a"] });
  },
  prime: () => {
    bufLog.push(["prime"]);
    return Promise.resolve({ status: "primed" });
  },
  start: () => void bufLog.push(["start"]),
  pause: () => void bufLog.push(["pause"]),
  seek: (position, units) => void bufLog.push(["seek", position, units ?? null]),
  finished: () => void bufLog.push(["finished"]),
  stop: () => void bufLog.push(["stop"]),
  download: () => {
    bufLog.push(["download"]);
    return "blob:stub";
  },
});

type El = {
  innerHTML: string;
  value?: string;
  style: { left?: string };
  classList: { contains(name: string): boolean };
  querySelector(s: string): El | null;
};

const cursorFor = (kind: string | null, log: unknown[]): Record<string, unknown> | null => {
  if (kind === null) return null;
  const cc: Record<string, unknown> = {
    onReady: () => log.push(["onReady"]),
    onStart: () => log.push(["onStart"]),
    onFinished: () => log.push(["onFinished"]),
    onBeat: (
      beat: number,
      total: number,
      totalTime: number,
      position: { left?: number; top?: number },
    ) =>
      log.push([
        "onBeat",
        beat,
        total,
        totalTime,
        position ? [position.left ?? null, position.top ?? null] : null,
      ]),
    onEvent: (e: { milliseconds?: number } | null) =>
      log.push(["onEvent", e ? (e.milliseconds ?? null) : null]),
    onLineEnd: (
      lineEvent: { milliseconds?: number } | undefined,
      leftEvent: { milliseconds?: number } | undefined,
    ) =>
      log.push([
        "onLineEnd",
        lineEvent ? (lineEvent.milliseconds ?? null) : null,
        leftEvent ? (leftEvent.milliseconds ?? null) : null,
      ]),
  };
  if (kind === "subdivided") {
    cc["beatSubdivisions"] = 4;
    cc["extraMeasuresAtBeginning"] = 1;
    cc["lineEndAnticipation"] = 50;
  }
  return cc;
};

const controlState = (parent: El): unknown[] => {
  const q = (s: string): El | null => parent.querySelector(s);
  const cls = (s: string, name: string): boolean | null => q(s)?.classList.contains(name) ?? null;
  const html = (s: string): string | null => q(s)?.innerHTML ?? null;
  return [
    cls(".abcjs-inline-audio", "abcjs-disabled"),
    cls(".abcjs-midi-start", "abcjs-pushed"),
    cls(".abcjs-midi-loop", "abcjs-pushed"),
    html(".abcjs-midi-clock"),
    html(".abcjs-midi-current-tempo"),
    q(".abcjs-midi-tempo")?.value ?? null,
    q(".abcjs-midi-progress-indicator")?.style.left ?? null,
  ];
};

const state = (c: SynthController): unknown[] => [
  c.isStarted,
  c.isLoaded,
  c.isLoading,
  c.isLooping,
  c.warp,
  c.percent === undefined ? null : c.percent,
  c.currentTempo,
  c.timer ? [c.timer.lastMoment, c.timer.totalBeats] : null,
];

/** The fake progress-bar click, verbatim from the harvester. */
const CLICK = {
  x: 60,
  target: {
    classList: { contains: () => false },
    parentNode: null,
    getBoundingClientRect: () => ({ left: 10 }),
    offsetWidth: 200,
  },
};

/** THE SCRIPT, verbatim from the harvester. */
const drive = async (
  tune: TuneObject,
  visualOptions: Record<string, boolean> | null,
  cursorKind: string | null,
  parent: El,
): Promise<Step[]> => {
  parent.innerHTML = "";
  bufLog = [];
  const cursorLog: unknown[] = [];
  const log: Step[] = [];
  const c = new SynthController(makeBuffer);
  const snap = (step: string): void => {
    log.push([step, bufLog.splice(0), cursorLog.splice(0), controlState(parent), state(c)]);
  };
  const step = async (label: string, fn: () => Promise<unknown>): Promise<void> => {
    try {
      snap(`${label}${(await fn()) ?? ""}`);
    } catch (e) {
      snap(`${label} threw: ${(e as Error).message}`);
    }
  };

  snap("new");
  if (visualOptions !== null) {
    c.load("#bar", cursorFor(cursorKind, cursorLog) as never, visualOptions as never);
    snap(`load ${JSON.stringify(visualOptions)}`);
  }
  await step("setTune passive -> ", async () =>
    JSON.stringify(await c.setTune(tune, false, {})),
  );
  await step("setTune userAction -> ", async () =>
    JSON.stringify(await c.setTune(tune, true, { chordsOff: true })),
  );
  await step("play -> ", async () => JSON.stringify(await c.play()));
  c.beatCallback(2, 8, 4000, { left: 5, top: 6, height: 7 });
  snap("beatCallback");
  c.eventCallback({ type: "event", milliseconds: 100, startChar: 3 } as never);
  snap("eventCallback event");
  c.lineEndCallback({ milliseconds: 50 }, { type: "event", milliseconds: 20 } as never);
  snap("lineEndCallback");
  snap(`eventCallback null -> ${c.eventCallback(null)}`);
  await step("play again -> ", async () => JSON.stringify(await c.play()));
  c.toggleLoop();
  snap("toggleLoop");
  c.restart();
  snap("restart");
  c.seek(0.25);
  snap("seek 0.25");
  c.seek(3, "seconds");
  snap("seek 3 seconds");
  await step("randomAccess -> ", async () => JSON.stringify(await c.randomAccess(CLICK)));
  await step("onWarp 50", async () => {
    await c.onWarp({ target: { value: "50" } });
  });
  snap(`eventCallback null looping -> ${c.eventCallback(null)}`);
  c.toggleLoop();
  c.pause();
  snap("pause");
  snap(`getUrl -> ${c.getUrl()}`);
  try {
    c.download("x.wav");
    snap("download");
  } catch (e) {
    snap(`download threw: ${(e as Error).message}`);
  }
  c.destroy();
  snap("destroy");
  c.disable(true);
  snap("disable true");
  return log;
};

const near = (a: unknown, b: unknown): boolean => {
  if (typeof a === "number" && typeof b === "number") return Math.abs(a - b) < 0.0005;
  if (Array.isArray(a) && Array.isArray(b))
    return a.length === b.length && a.every((v, i) => near(v, b[i]));
  return (a ?? null) === (b ?? null);
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const run = async (): Promise<Row[]> => {
  // The page, the clock and the audio context — the same three the harvester replaced.
  const dom = new JSDOM(
    '<!DOCTYPE html><html><body><div id="bar"></div><div id="paper"></div></body></html>',
  );
  const win = dom.window as unknown as {
    document: { getElementById(id: string): El | null };
    URL: { revokeObjectURL: (u: string) => void };
  };
  win.URL.revokeObjectURL = () => {};
  const g = globalThis as Record<string, unknown>;
  const saved = {
    document: g["document"],
    window: g["window"],
    performance: g["performance"],
    requestAnimationFrame: g["requestAnimationFrame"],
    setTimeout: g["setTimeout"],
    clearTimeout: g["clearTimeout"],
  };
  g["document"] = win.document;
  g["window"] = dom.window;
  g["performance"] = { now: () => 0 };
  g["requestAnimationFrame"] = () => 0;
  g["setTimeout"] = () => 0;
  g["clearTimeout"] = () => {};
  const ac = { state: "running", resume: () => Promise.resolve() };
  registerAudioContext(ac);

  const out: Row[] = [];
  try {
    const tunes = new Map<string, TuneObject>();
    for (const [key, want] of Object.entries(GOLDEN)) {
      const [fixture = "", label = ""] = key.split("#");
      let tune = tunes.get(fixture);
      if (tune === undefined) {
        const abc = readFileSync(join(IN_REPO, `${fixture}.abc`), "utf-8");
        tune = renderAbc(["*"], abc, {})[0] as TuneObject;
        tunes.set(fixture, tune);
      }
      const shape = CASES.find(([name]) => name === label);
      const parent = win.document.getElementById("bar");
      if (parent === null || shape === undefined) continue;
      const got = await drive(tune, shape[1], shape[2], parent);
      let agree = 0;
      let first = "";
      for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
        if (near(want[i], got[i])) agree += 1;
        else if (first === "")
          first = `step ${i}: abcjs ${JSON.stringify(want[i]).slice(0, 200)} ours ${JSON.stringify(got[i]).slice(0, 200)}`;
      }
      out.push({ slug: key, agree, total: want.length, first });
    }
  } finally {
    for (const [k, v] of Object.entries(saved)) g[k] = v;
  }
  return out;
};

describe("SynthController — the transport state machine", async () => {
  const table = await run();

  it("writes the ranked table", () => {
    const off = table.filter((r) => r.agree < r.total);
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-synth-controller-ranked.txt",
      `${[
        `${off.length} of ${table.length} cases differ; ${agree} of ${total} steps agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(56)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBe(8);
  });

  it("every case agrees on every step", () => {
    const broken = table
      .filter((r) => r.agree < r.total)
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken).toEqual([]);
  });
});
