import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { synth } from "../src/compat/index.js";

/**
 * **`CreateSynthControl` — THE TRANSPORT BAR, MARKUP AND ALL.**
 *
 * The oracle is `tests/corpus-synth-control/golden.json`, generated by RUNNING abcjs 6.7.0
 * in a jsdom page (`scripts/harvest-abcjs-synth-control.mjs`). Six option shapes, and for
 * each one the parent's WHOLE markup after every step of a fourteen-step script — the
 * setters, then a click on each button — beside the list of handlers that have fired.
 *
 * **THIS IS THE ONE OF THE FOUR SOUND-MAKING SYMBOLS THAT NEEDS NO SOUND.** The control is
 * DOM and handlers; the only thing it knows about an AudioContext is that a click may have
 * to resume one, so the harness registers a context that is already running and every click
 * is synchronous.
 *
 * ⚠️ **`setWarp` THROWS when there is no warp input** — it does not null-check where
 * `setTempo` does — so that step is recorded as `setWarp threw` and a port that guards it
 * would fail here.
 *
 * jsdom comes from the SIBLING repo, as every DOM gate here does.
 */
const sibling = createRequire(
  join(import.meta.dirname, "..", "..", "abcMusicKit", "Tools", "abcjs-debug", "package.json"),
);
const { JSDOM } = sibling("jsdom") as {
  JSDOM: new (html: string) => {
    window: {
      document: {
        getElementById(id: string): {
          innerHTML: string;
          querySelector(s: string): { dispatchEvent(e: unknown): void } | null;
        } | null;
      };
      Event: new (type: string) => unknown;
      HTMLElement: unknown;
    };
  };
};

type Step = [string, string, string[]];

const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-synth-control", "golden.json"), "utf-8"),
) as Record<string, Step[]>;

/** THE SHAPES, verbatim from the harvester. */
const SHAPES: [string, Record<string, unknown>][] = [
  ["bare", {}],
  ["play", { play: true }],
  ["all", { play: true, loop: true, restart: true, progress: true, warp: true }],
  ["no-clock", { play: true, hasClock: false }],
  ["titles", { play: true, loop: true, playTitle: "Go", repeatTitle: "Again", bpm: "beats" }],
  ["promise", { playPromise: true, progress: true }],
];

const dom = new JSDOM('<!DOCTYPE html><html><body><div id="bar"></div></body></html>');

const drive = (label: string): Step[] => {
  const shape = SHAPES.find(([name]) => name === label)?.[1] ?? {};
  const g = globalThis as unknown as Record<string, unknown>;
  const saved = { document: g["document"], window: g["window"] };
  g["document"] = dom.window.document;
  g["window"] = dom.window;
  const log: Step[] = [];
  try {
    const parent = dom.window.document.getElementById("bar");
    if (parent === null) return [];
    parent.innerHTML = "";
    const fired: string[] = [];
    const options: Record<string, unknown> = { hasClock: shape["hasClock"] };
    if (shape["play"]) options["playHandler"] = () => fired.push("play");
    if (shape["playPromise"])
      options["playPromiseHandler"] = () => {
        fired.push("playPromise");
        return Promise.resolve();
      };
    if (shape["loop"]) options["loopHandler"] = () => fired.push("loop");
    if (shape["restart"]) options["restartHandler"] = () => fired.push("restart");
    if (shape["progress"]) options["progressHandler"] = () => fired.push("progress");
    if (shape["warp"]) options["warpHandler"] = () => fired.push("warp");
    for (const key of ["playTitle", "repeatTitle", "bpm"])
      if (shape[key]) options[key] = shape[key];

    const control = new synth.CreateSynthControl(parent as never, options as never);
    const snap = (step: string): void => {
      log.push([step, parent.innerHTML, [...fired]]);
    };
    snap("built");
    control.pushPlay(true);
    snap("pushPlay true");
    control.pushLoop(true);
    snap("pushLoop true");
    control.setTempo(123.6);
    snap("setTempo");
    try {
      control.setWarp(90, 133.4);
      snap("setWarp");
    } catch {
      log.push(["setWarp threw", parent.innerHTML, [...fired]]);
    }
    control.setProgress(0.5, 61000);
    snap("setProgress");
    control.disable(true);
    snap("disable true");
    control.disable(false);
    snap("disable false");
    control.resetAll();
    snap("resetAll");
    for (const [selector, event] of [
      [".abcjs-midi-start", "click"],
      [".abcjs-midi-loop", "click"],
      [".abcjs-midi-reset", "click"],
      [".abcjs-midi-progress-background", "click"],
      [".abcjs-midi-tempo", "change"],
    ] as const) {
      const el = parent.querySelector(selector);
      if (el) el.dispatchEvent(new dom.window.Event(event));
      snap(`${event} ${selector}`);
    }
  } finally {
    for (const [k, v] of Object.entries(saved)) g[k] = v;
  }
  return log;
};

interface Row {
  readonly shape: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const rows = (): Row[] =>
  Object.entries(GOLDEN).map(([shape, want]) => {
    const got = drive(shape);
    let agree = 0;
    let first = "";
    for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
      if (JSON.stringify(want[i]) === JSON.stringify(got[i])) agree += 1;
      else if (first === "")
        first = `step ${i} (${want[i]?.[0] ?? got[i]?.[0]}): abcjs ${JSON.stringify(want[i]).slice(0, 160)} ours ${JSON.stringify(got[i]).slice(0, 160)}`;
    }
    return { shape, agree, total: want.length, first };
  });

describe("CreateSynthControl — the transport bar", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table.filter((r) => r.agree < r.total);
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-synth-control-ranked.txt",
      `${[
        `${off.length} of ${table.length} shapes differ; ${agree} of ${total} steps agree`,
        "",
        ...off.map((r) => `  ${r.shape.padEnd(12)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBe(6);
  });

  it("every shape agrees on every step, markup included", () => {
    const broken = table
      .filter((r) => r.agree < r.total)
      .map((r) => `${r.shape} ${r.agree}/${r.total} ${r.first}`);
    expect(broken).toEqual([]);
  });
});
