import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { synth } from "../src/compat/index.js";

/**
 * **`SynthSequence` — THE BUILDER, CALL BY CALL.**
 *
 * The oracle is `tests/corpus-synth-sequence/golden.json`, generated by RUNNING abcjs
 * 6.7.0 through the SAME nine steps (`scripts/harvest-abcjs-synth-sequence.mjs`). After
 * each call it records the whole `tracks` array, `totalDuration`, and the two per-track
 * clocks — so a sticky instrument, a per-track `start`, and the `cents` field's
 * TRUTHINESS (a 0 is absent, not zero) are each compared rather than assumed.
 *
 * This is the one of the seven `synth.*` that needs no audio at all, which is why it is
 * the one with a gate.
 */
type Step = [string, unknown[][], number, number[], number[]];

const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-synth-sequence", "golden.json"),
    "utf-8",
  ),
) as Step[];

const ours = (): Step[] => {
  const seq = new synth.SynthSequence();
  const log: Step[] = [];
  const snap = (label: string): void => {
    log.push([
      label,
      JSON.parse(JSON.stringify(seq.tracks)) as unknown[][],
      seq.totalDuration,
      [...seq.starts],
      [...seq.currentInstrument],
    ]);
  };
  // ── THE NINE STEPS, verbatim from the harvester ──────────────────────────
  snap("empty");
  const a = seq.addTrack();
  snap(`addTrack -> ${a}`);
  seq.setInstrument(a, 40);
  snap("setInstrument 40");
  seq.appendNote(a, 60, 0.25, 105);
  snap("appendNote 60");
  seq.appendNote(a, 62, 0.125, 90, 50);
  snap("appendNote 62 with cents");
  seq.appendNote(a, 64, 1 / 64, 80, 0);
  snap("appendNote 64 with cents 0");
  const b = seq.addTrack();
  snap(`addTrack -> ${b}`);
  seq.appendNote(b, 48, 0.5, 70);
  snap("appendNote on the untouched track");
  seq.setInstrument(b, 0);
  seq.appendNote(b, 50, 0.75, 60);
  snap("second track past the first");
  return log;
};

describe("SynthSequence — the builder behind playEvent", () => {
  it("builds what abcjs builds, step for step", () => {
    expect(JSON.parse(JSON.stringify(ours()))).toEqual(GOLDEN);
  });
});
