import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc, TimingCallbacks } from "../src/compat/index.js";
import type { NoteTiming } from "../src/audio/timing.js";

/**
 * **`TimingCallbacks` — THE CURSOR'S EVENT STREAM, DRIVEN AT 16ms.**
 *
 * The oracle is `tests/corpus-timing-callbacks/golden.json`, generated by RUNNING abcjs
 * 6.7.0 with its clock replaced (`scripts/harvest-abcjs-timing-callbacks.mjs`).
 *
 * **abcjs's OWN TESTS FOR THIS ARE UNPORTABLE AND THE CLASS IS NOT.** They drive a real
 * timer and `sleep()`, which the 2026-08-09 audit classified as host playback; but
 * `doTiming(timestamp)` takes the time as an ARGUMENT, and the only other host calls are
 * `requestAnimationFrame`, `setTimeout` and `performance.now()`. Stub those three and the
 * whole 436 lines are a pure function of a timestamp sequence — so both sides are driven
 * from 0 in 16ms steps to one frame past the last moment, and every callback is recorded
 * with its arguments.
 *
 * Four shapes per fixture: the defaults, `beatSubdivisions: 2`, `qpm: 120` (the host's own
 * tempo, which WARPS the tune's rather than replacing it), and a `lineEndCallback` with a
 * 100ms anticipation — the only one that reads the GEOMETRY, since `getLineEndTimings`
 * groups by `timing.top`.
 */
type Callback = unknown[];

const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-timing-callbacks", "golden.json"),
    "utf-8",
  ),
) as Record<string, Callback[] | { throws: string }>;

const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

const SHAPES: Record<string, Record<string, number>> = {
  default: {},
  "subdivisions-2": { beatSubdivisions: 2 },
  "qpm-120": { qpm: 120 },
  "line-end": { lineEndAnticipation: 100 },
};

/** The same reduction the harvester makes — a timing row as a cursor uses it. */
const ev = (e: NoteTiming | null | undefined): unknown =>
  e === null || e === undefined
    ? null
    : [e.type, e.milliseconds, e.startChar ?? null, e.left ?? null, e.top ?? null];

const near = (a: unknown, b: unknown): boolean => {
  if (typeof a === "number" && typeof b === "number")
    return Math.abs(a - b) < 0.0005;
  if (Array.isArray(a) && Array.isArray(b))
    return a.length === b.length && a.every((v, i) => near(v, b[i]));
  return (a ?? null) === (b ?? null);
};

const drive = (key: string): Callback[] => {
  const [file = "", label = ""] = key.split("#");
  const abc = readFileSync(join(IN_REPO, `${file}.abc`), "utf-8");
  const tune = renderAbc(["*"], abc, {})[0];
  if (tune === undefined) return [];
  const log: Callback[] = [];
  const params = SHAPES[label] ?? {};
  const options: Record<string, unknown> = {
    ...params,
    eventCallback: (e: NoteTiming | null) => {
      log.push(["event", ev(e)]);
      return undefined;
    },
    beatCallback: (
      beat: number,
      total: number,
      lastMoment: number,
      position: { left?: number; top?: number; height?: number },
    ) => {
      log.push([
        "beat",
        beat,
        total,
        lastMoment,
        position
          ? [position.left ?? null, position.top ?? null, position.height ?? null]
          : null,
      ]);
    },
  };
  if (label === "line-end")
    options["lineEndCallback"] = (
      info: { measureNumber?: number; milliseconds: number; top?: number; bottom?: number } | undefined,
      leftEvent: NoteTiming | undefined,
      extra: { line: number },
    ) => {
      log.push([
        "lineEnd",
        info
          ? [info.measureNumber ?? null, info.milliseconds, info.top ?? null, info.bottom ?? null]
          : null,
        ev(leftEvent),
        extra ? extra.line : null,
      ]);
    };

  // **THE CLOCK IS OURS HERE**, exactly as it is in the harvester: `performance.now()`
  // answers the last driven timestamp and the two schedulers are no-ops, because this
  // calls `doTiming` itself.
  const g = globalThis as {
    performance?: { now: () => number };
    requestAnimationFrame?: unknown;
    setTimeout?: unknown;
    clearTimeout?: unknown;
  };
  const savedPerformance = g.performance as { now: () => number };
  const savedRaf = g.requestAnimationFrame;
  const savedTimeout = g.setTimeout;
  const savedClear = g.clearTimeout;
  let clock = 0;
  g.performance = { now: () => clock };
  g.requestAnimationFrame = () => 0;
  g.setTimeout = () => 0;
  g.clearTimeout = () => {};
  try {
    const timing = new TimingCallbacks(tune, options);
    timing.start();
    const until = Math.min(timing.lastMoment + 32, 60000);
    for (let t = 0; t <= until; t += 16) {
      clock = t;
      timing.doTiming(t);
    }
  } finally {
    g.performance = savedPerformance;
    g.requestAnimationFrame = savedRaf;
    g.setTimeout = savedTimeout;
    g.clearTimeout = savedClear;
  }
  return log;
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const rows = (): Row[] => {
  const out: Row[] = [];
  for (const [key, want] of Object.entries(GOLDEN)) {
    if (!Array.isArray(want)) continue;
    const got = drive(key);
    let agree = 0;
    let first = "";
    for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
      if (near(want[i], got[i])) agree += 1;
      else if (first === "")
        first = `#${i}: abcjs ${JSON.stringify(want[i])} ours ${JSON.stringify(got[i])}`;
    }
    out.push({ slug: key, agree, total: want.length, first });
  }
  return out;
};

describe("TimingCallbacks — the cursor's event stream", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table
      .filter((r) => r.agree < r.total)
      .sort((a, b) => a.total - a.agree - (b.total - b.agree));
    const agree = table.reduce((t, r) => t + r.agree, 0);
    const total = table.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-timing-callbacks-ranked.txt",
      `${[
        `${off.length} of ${table.length} cases differ; ${agree} of ${total} callbacks agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(64)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(100);
  });

  /**
   * **THE FOUR OPEN CASES ARE ONE FIXTURE AND ONE KNOWN ROW.** `synth-timing-10-stretchlast-1`
   * reports its first system's HEIGHT as 57.248 against abcjs's 60.932 — the same system
   * bottom pitch the `setupEvents` gate has open (−1.0493 against −2), reached here through
   * `position.height`. Both engines PLACE the systems identically; it is what the extent is
   * reported as. A floor, not a target.
   */
  it("the whole corpus agrees on at least the callbacks it did", () => {
    const agree = table.reduce((t, r) => t + r.agree, 0);
    expect(agree).toBeGreaterThanOrEqual(4674);
  });

  it("no case differs for any other reason", () => {
    const broken = table
      .filter((r) => r.agree < r.total)
      .filter((r) => !r.slug.startsWith("abcjs-synth-timing-10-stretchlast-1"))
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken.slice(0, 20)).toEqual([]);
  });
});
