import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";
import { renderAll } from "./render-all.js";

/**
 * **`tune.topText` AND `tune.bottomText` — abcjs's INTERMEDIATE ROW LIST, OVER 312 TUNES
 * AND 1,023 ROWS.**
 *
 * `TopText`/`BottomText` build a `rows` array interleaving `{move: n}` with text rows and,
 * in the bottom block, a group's open and close; `nonMusic` walks it spending each `move`
 * on the page's own cursor (`creation/elements/top-text.js`, `bottom-text.js`,
 * `draw/non-music.js`). `engraver-controller.js:222` and `:236` hang both on the tune, so
 * this is a PUBLIC surface and not an implementation detail — which is why it is projected
 * from the layout rather than being what the layout is built on.
 *
 * The oracle is `tests/corpus-toptext/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-toptext.mjs`) at the goldens' own `{staffwidth: 670}`. abcjs's own
 * suite asserts none of it.
 *
 * **THE COMPARISON IS THE SERIALISED ROW, KEY ORDER INCLUDED**, because a host can
 * `JSON.stringify` it and abcjs's order is deterministic: `addTextIf` builds
 * `{left, text, font, anchor, startChar, endChar, 'dominant-baseline'}` as a literal and
 * then adds `absElemType`, `klass` and `name` in that sequence (`add-text-if.js:10-19`).
 *
 * Four rules came out of it, none of them visible from any other surface:
 *
 *   - **`left` IS `params.marginLeft`, BEFORE ANY BOX MOVED IT.** `renderText` adjusts
 *     `hash.attr.x` by the padding only when it DRAWS (`draw/text.js:57`), so a boxed row's
 *     `left` is still 15 while its text sits at 16.2. Eleven rows were that one fact, and
 *     the margin TRAVELS rather than being recovered — subtracting the padding back is not
 *     the same double.
 *   - **A ROW'S TEXT IS THE WHOLE JOIN, AND THE JOIN BEFORE `renderText`'s REWRITE.**
 *     `addTextIf` is handed one string with its newlines in it and `Svg.text` splits it into
 *     a `<tspan>` per line; ours carries a first line and `extraLines`, and the pre-rewrite
 *     join is already on the `extraText` selectable.
 *   - **A ROW THAT CLOSES A GROUP IS NOT ITSELF SELECTABLE.** `closeGroup` stamps the
 *     `endGroup`'s `abcelem` onto the last row so the emitter can find it, but abcjs's row
 *     there is an ordinary `richText` one with `addTextIf`'s `{-2, -2}` — the `-1`s belong
 *     to the `endGroup` row alone (`bottom-text.js:57`, `:61`).
 *   - **A ROW THAT MOVES NOTHING IS STILL A ROW.** `spacing.words` and `spacing.info` both
 *     default to zero (`write/renderer.js:99`, `:114`), so they are absent from `advances` —
 *     where a zero add is a no-op the page walk must not be handed twice — and present here.
 *
 * The list STOPS where abcjs's does, at the part order: a `%%text` or `%%center` before the
 * music is a nonMusic LINE and not top text (`draw/draw.js:12-58`).
 */
interface Golden {
  readonly topText: Record<string, unknown>[] | null;
  readonly bottomText: Record<string, unknown>[] | null;
}

const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-toptext", "golden.json"),
    "utf-8",
  ),
) as Record<string, Golden>;

const SIBLING = join(
  import.meta.dirname,
  "..",
  "..",
  "abcMusicKit",
  "Tools",
  "abcjs-debug",
  "fixtures",
);
const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/** Excluded, and NOT ours — see `metatextinfo.test.ts`. */
const STALE = ["sib/S7-voices", "sib/multi-voice-rest-placement"];

interface Row {
  readonly slug: string;
  readonly which: "topText" | "bottomText";
  readonly index: number;
  readonly want: string | undefined;
  readonly got: string | undefined;
}

const rows = (): Row[] => {
  const out: Row[] = [];
  for (const [slug, want] of Object.entries(GOLDEN)) {
    if (STALE.some((s) => slug.startsWith(s))) continue;
    const corpus = slug.slice(0, slug.indexOf("/"));
    const rest = slug.slice(slug.indexOf("/") + 1);
    const at = rest.lastIndexOf("-tune");
    const index = Number(rest.slice(at + 5));
    const abc = readFileSync(
      join(corpus === "sib" ? SIBLING : IN_REPO, `${rest.slice(0, at)}.abc`),
      "utf-8",
    );
    // THE GOLDENS' OWN WIDTH — abcjs's screen default is 740, not this.
    const slots: string[] = [];
    for (let k = 0; k <= index; k++) slots.push("*");
    const tune = renderAbc(slots, abc, { staffwidth: 670 })[index];
    for (const which of ["topText", "bottomText"] as const) {
      const wantRows = want[which] ?? [];
      const gotRows = (tune?.[which]?.rows ?? []) as Record<string, unknown>[];
      for (let i = 0; i < Math.max(wantRows.length, gotRows.length); i++)
        out.push({
          slug,
          which,
          index: i,
          want: wantRows[i] === undefined ? undefined : JSON.stringify(wantRows[i]),
          got: gotRows[i] === undefined ? undefined : JSON.stringify(gotRows[i]),
        });
    }
  }
  return out;
};

describe("topText / bottomText — abcjs's own row list", () => {
  const all = rows();

  it("writes every row abcjs writes", () => {
    expect(
      all
        .filter((r) => r.want !== undefined && r.got === undefined)
        .map((r) => `${r.slug} ${r.which}[${r.index}] ${r.want}`),
    ).toEqual([]);
  });

  it("writes no row abcjs does not", () => {
    expect(
      all
        .filter((r) => r.want === undefined)
        .map((r) => `${r.slug} ${r.which}[${r.index}] ${r.got}`),
    ).toEqual([]);
  });

  it("serialises every row exactly as abcjs does", () => {
    expect(
      all
        .filter((r) => r.want !== r.got)
        .map(
          (r) =>
            `${r.slug} ${r.which}[${r.index}]\n  abcjs ${r.want}\n  ours  ${r.got}`,
        ),
    ).toEqual([]);
  });
});

/**
 * **A `%%text` BLOCK BEFORE THE MUSIC IS A LINE, SO A BODY `T:` AFTER IT COMES AFTER IT.**
 *
 * `addSubtitle` is a bare `pushLine(tune, {subtitle})` (`tune-builder.js:298-300`) — it
 * APPENDS, so a subtitle's position is only ever "after whatever lines exist". A `%%text`
 * standing before the music has already pushed one. Sending the subtitle to the TOP BLOCK
 * instead puts it above every nonMusic line whatever the source order said.
 *
 * ⚠️ **NO GOLDEN COVERS THIS AND THE FIX PROVED IT** — `svg-bytes` stayed at 0 of 685 and
 * 0 of 356, and the extended ratchet did not move: every corpus `%%text` has music before
 * it, which is the case that already worked. **A gate's reach is a property of its
 * enumeration**, so this shape needs a test of its own or it has none.
 *
 * Measured through abcjs 6.7.0, one variable per rung — only the first moved:
 *
 *     %%text then T:, no music before   ours 260.05  abcjs 257.32   ← 2.73px, WebKit
 *     %%text then T:, MUSIC before      same
 *     T: then %%text, no music before   same
 *     T: alone / %%text alone           same
 *
 * ⭐ **THE REVERSED-SOURCE RUNG IS WHAT NAMED IT**: `T:` then `%%text` gave 260.05 in BOTH
 * engines, so our wrong answer for the forward order was exactly our right answer for the
 * reversed one — which says we emitted one FIXED order rather than the source's. Asserting
 * that the two orders still differ is therefore half the test: a fix that merely swapped
 * the constant would pass the first assertion and fail this one.
 */
describe("a pre-music %%text block and a body T: keep their source order", () => {
  /**
   * ⚠️ **`topText.rows` IS THE WRONG INSTRUMENT AND ANSWERS -1.** The list stops at the part
   * order: a `%%text` or `%%center` before the music is a nonMusic LINE and NOT top text
   * (`draw/draw.js:12-58`), so the row this is about is not in it at all. The order has to
   * be read off the drawn SVG, which is where both rows actually land.
   */
  const rowsOf = (abc: string): string[] =>
    [...(renderAll(abc, { staffwidth: 670 })[0]?.svg ?? "").matchAll(/<text[^>]*>([\s\S]*?)<\/text>/g)]
      .map((m) => m[1]?.replace(/<[^>]*>/g, "").trim() ?? "")
      .filter((t) => t !== "");
  const textFirst = "T:t\nK:C\n%%text extra\nT:Sub\n|GGGG|]\n";
  const titleFirst = "T:t\nK:C\nT:Sub\n%%text extra\n|GGGG|]\n";

  it("puts the subtitle after a %%text that precedes it", () => {
    const rows = rowsOf(textFirst);
    expect(rows.indexOf("extra")).toBeGreaterThanOrEqual(0);
    expect(rows.indexOf("Sub")).toBeGreaterThan(rows.indexOf("extra"));
  });

  it("puts the subtitle before a %%text that follows it", () => {
    const rows = rowsOf(titleFirst);
    expect(rows.indexOf("Sub")).toBeGreaterThanOrEqual(0);
    expect(rows.indexOf("extra")).toBeGreaterThan(rows.indexOf("Sub"));
  });

  /** …and the two orders must not collapse onto one another, which a swapped constant would. */
  it("renders the two orders differently", () => {
    expect(rowsOf(textFirst)).not.toEqual(rowsOf(titleFirst));
  });
});
