import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { parse } from "../src/parser/parser.js";
import { strTranspose } from "../src/str/transpose.js";

/**
 * **`strTranspose` — ABC TEXT IN, ABC TEXT OUT, against 59 of abcjs's own cases.**
 *
 * The oracle is `tests/corpus-transpose/golden.json`: the inputs and step counts are
 * harvested out of `tests/visual/transpose-output.test.js` by EVALUATING it with
 * `describe`/`it`/`outputTest` replaced — the same trick the flattener oracle used — and
 * every expected string is then generated by **RUNNING abcjs 6.7.0**, not copied from the
 * test file.
 *
 * **THAT DISTINCTION EARNED ITSELF IMMEDIATELY.** On `output-miss-accidental` abcjs's own
 * suite expects `=B, _B,|_B, |` and abcjs produces `=B, B,|_B, |`; the test is named for
 * the bug it documents. Our target is what abcjs DOES, so the golden carries abcjs's
 * output and records the test file's claim beside it in `testFileSays`.
 */
interface Case {
  readonly slug: string;
  readonly abc: string;
  readonly steps: number;
  readonly expected: string;
  readonly testFileSays?: string;
}

const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-transpose", "golden.json"),
    "utf-8",
  ),
) as Case[];

/**
 * **CLOSED, AND IT WAS ONE LINE.** `output-unusual` writes `""_A-_A"D"|B>c|`, a chord
 * symbol standing between the last note of a measure and its barline. abcjs attaches a
 * pending chord to the BAR element and `transposeVoice` tests `el.chord` before it looks
 * at `el_type` (`output.js:127-138`).
 *
 * The first note here said our parser dropped it, on the strength of
 * `Measure.openingBarlineChord` being `undefined` — and the model has
 * `closingBarlineChord` sitting right beside it for exactly this case, which the element
 * walk was not reading. **Two fields, one checked.** The list is empty.
 */
const MEASURED_NOT_PORTED: readonly string[] = [];

describe("strTranspose", () => {
  const run = (c: Case): string => {
    const p = parse(c.abc, { mode: "abcjs-strict" });
    return p.ok ? strTranspose(c.abc, p.scores, c.steps) : "";
  };

  it("has every harvested case", () => {
    expect(GOLDEN.length).toBe(59);
  });

  for (const c of GOLDEN) {
    if (MEASURED_NOT_PORTED.includes(c.slug)) continue;
    it(`matches abcjs — ${c.slug}`, () => {
      expect(run(c)).toBe(c.expected);
    });
  }

  it("nothing on the measured-not-ported list has quietly started matching", () => {
    const fixed = GOLDEN.filter((c) =>
      MEASURED_NOT_PORTED.includes(c.slug),
    ).filter((c) => run(c) === c.expected);
    expect(
      fixed.map((c) => c.slug),
      "delete these from MEASURED_NOT_PORTED — the gate holds them now",
    ).toEqual([]);
  });

  /**
   * abcjs's own suite disagrees with abcjs on exactly one case, and the golden records it
   * rather than hiding it. If this count moves, the harvest has drifted.
   */
  it("records where abcjs's own test disagrees with abcjs", () => {
    expect(
      GOLDEN.filter((c) => c.testFileSays !== undefined).map((c) => c.slug),
    ).toEqual(["output-miss-accidental-down2"]);
  });
});
