import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { tuneMetrics } from "../src/compat/index.js";

/**
 * **`tuneMetrics` — EACH MEASURE'S MINIMUM WIDTH.**
 *
 * The oracle is `tests/corpus-tune-metrics/golden.json`, generated by RUNNING abcjs 6.7.0
 * over every fixture of both corpora (`scripts/harvest-abcjs-tune-metrics.mjs`). Every
 * number is compared: each section's `left`, its `measureWidths` and its `total`.
 *
 * The numbers come from a layout at width **0**, where every spring has collapsed and the
 * rods are all that is left — see `tune-metrics.ts` for why that needed no new layout mode,
 * only the staff-width-to-page conversion `renderAbc` already makes.
 *
 * ⚠️ **ONE SLOT, SO ONE TUNE PER FILE**: `tuneMetrics` passes the string `"*"`, which is a
 * single output slot, so a book reports its FIRST tune and nothing else.
 */
type Section = { left: number; measureWidths: number[]; total: number };

const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-tune-metrics", "golden.json"), "utf-8"),
) as Record<string, Section[]>;

const config = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "abcts.config.json"), "utf-8"),
) as { corpus: string };

const DIRS: Record<string, string> = {
  repo: join(import.meta.dirname, "corpus-abcjs", "fixtures"),
  sib: join(import.meta.dirname, "..", config.corpus),
};

const ours = (key: string): Section[] => {
  const [corpus = "", rest = ""] = key.split("/");
  const file = rest.substring(0, rest.lastIndexOf("-tune"));
  const abc = readFileSync(join(DIRS[corpus] ?? "", `${file}.abc`), "utf-8");
  return tuneMetrics(abc, {})[0]?.sections ?? [];
};

interface Row {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const table = (): Row[] =>
  Object.entries(GOLDEN).map(([slug, want]) => {
    const got = ours(slug);
    let agree = 0;
    let first = "";
    for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
      if (JSON.stringify(want[i]) === JSON.stringify(got[i])) agree += 1;
      else if (first === "")
        first = `section ${i}: abcjs ${JSON.stringify(want[i])?.slice(0, 150)} ours ${JSON.stringify(got[i])?.slice(0, 150)}`;
    }
    return { slug, agree, total: want.length, first };
  });

/** Tunes whose every section agrees. Grows, never shrinks. */
const PASSING: readonly string[] = [
  "repo/abcts-ledger-gaps-tune0",
  "repo/abcts-model-gaps-tune0",
  "repo/abcts-slur-shapes-tune0",
  "sib/inline-key-per-voice-tune0",
  "sib/ragtime-nightingale-tune0",
  "repo/abcjs-parse-book_parser-01-example-tune0",
  "repo/abcjs-parse-book_parser-02-tune-tune0",
  "repo/abcjs-parse-book_parser-03-a-tune0",
  "repo/abcjs-parse-book_parser-04-wed-tune0",
  "repo/abcjs-parse-book_parser-05-a-tune0",
  "repo/abcjs-parse-book_parser-06-a-tune0",
  "repo/abcjs-parse-book_parser-07-a-tune0",
  "repo/abcjs-parse-note-01-c0-d1-eg-0-fa-1-tune0",
  "repo/abcjs-parse-note-id-01-v-v1-c-d-e-f-tune0",
  "repo/abcjs-parse-tie-slur-01-staffwidth-200-tune0",
  "repo/abcjs-parse-tie-slur-02-staffwidth-200-tune0",
  "repo/abcjs-parse-tie-slur-03-staffwidth-200-tune0",
  "repo/abcjs-parse-tie-slur-04-stretchlast-1-tune0",
  "repo/abcjs-synth-flattener-01-crescendo-efga-gab-crescendo-c-diminuend-tune0",
  "repo/abcjs-synth-flattener-02-p-c-def-gabc-d2-b2-g2-f2-f-e-fga-bcde-p--tune0",
  "repo/abcjs-synth-flattener-03-pppp-cdef-gabc-y-ffff-bcba-gfed-y-pppp-c-tune0",
  "repo/abcjs-synth-flattener-04-g-gab-cde-d7-fga-def-tune0",
  "repo/abcjs-synth-flattener-05-c-cde-def-c2e-d2f-c-c2-d-d-g-d2-e-e-tune0",
  "repo/abcjs-synth-flattener-06-cde-d7-f2-d2-e2-f2-1-g-g4-fedc-c-e4z4-tune0",
  "repo/abcjs-synth-flattener-07-metronome-tune0",
  "repo/abcjs-synth-flattener-08-em-egab-tune0",
  "repo/abcjs-synth-flattener-09-d-defg-q-1-2-90-defg-tune0",
  "repo/abcjs-synth-flattener-10-q-1-4-129-0476605-cdef-q-1-4-127-gabc-q--tune0",
  "repo/abcjs-synth-flattener-11-midi-program-3-tune0",
  "repo/abcjs-synth-flattener-12-chords-meter-change-tune0",
  "repo/abcjs-synth-flattener-13-e7-bcde-a-f-break-efe-e7-bc-ignore-de-tune0",
  "repo/abcjs-synth-flattener-14-eb7-zg2ga2a2-a2ab-b4-ab-z-break-c2cd2d2--tune0",
  "repo/abcjs-synth-flattener-15-c-c4-c-tune0",
  "repo/abcjs-synth-flattener-16-gm-gfdf-gfdf-gf-d2-f-c4-tune0",
  "repo/abcjs-synth-flattener-17-midi-grace-notes-tune0",
  "repo/abcjs-synth-flattener-18-midi-program-40-tune0",
  "repo/abcjs-synth-flattener-19-cdef-z4-fedc-tune0",
  "repo/abcjs-synth-flattener-20-k-treble-8-b-a4-ce-f-4-k-treble-8-g8-g-2-tune0",
  "repo/abcjs-synth-flattener-21-c4-d4-tune0",
  "repo/abcjs-synth-flattener-22-b-c4-d4-tune0",
  "repo/abcjs-synth-flattener-23-percmap-d-pedal-hi-hat-x-tune0",
  "repo/abcjs-synth-flattener-24-percmap-c-high-tom-x-tune0",
  "repo/abcjs-synth-flattener-25-cd-d2-d2-dz-tune0",
  "repo/abcjs-synth-flattener-26-gbcd-d4-zcdc-dc3-tune0",
  "repo/abcjs-synth-flattener-27-triplets-and-chord-rhythm-tune0",
  "repo/abcjs-synth-flattener-28-midi-channel-10-tune0",
  "repo/abcjs-synth-flattener-29-midi-drum-dddd-76-77-77-77-50-50-50-50-tune0",
  "repo/abcjs-synth-flattener-30-am-a2e-e2d-g-bab-d2b-am-a2e-e2d-g-b2a-ga-tune0",
  "repo/abcjs-synth-flattener-31-tempo-change-three-voices-tune0",
  "repo/abcjs-synth-flattener-32-quarter-tone2-tune0",
  "repo/abcjs-synth-flattener-33-tempo-override-tune0",
  "repo/abcjs-synth-flattener-34-score-s-a-t-b-tune0",
  "repo/abcjs-synth-flattener-35-midi-bassprog-10-tune0",
  "repo/abcjs-synth-flattener-36-midi-gchord-fhihfhih-tune0",
  "repo/abcjs-synth-flattener-37-midi-gchord-bzczbzcz-tune0",
  "repo/abcjs-synth-flattener-38-c-zz-d-z-e-z-tune0",
  "repo/abcjs-synth-flattener-39-midi-gchord-bzczbzcz-tune0",
  "repo/abcjs-synth-flattener-40-c5-z4-tune0",
  "repo/abcjs-synth-flattener-41-midi-bassprog-10-octave-1-tune0",
  "repo/abcjs-synth-flattener-42-midi-gchord-ffffffff-tune0",
  "repo/abcjs-synth-flattener-43-gm-zzz-cm-zzz-tune0",
  "repo/abcjs-synth-flattener-44-cd-pppp-c-ffff-d-ffff-c-pppp-d-cd-tune0",
  "repo/abcjs-synth-flattener-45-segno-f-d2-tune0",
  "repo/abcjs-synth-flattener-46-c8-1-d8-2-e8-3-f8-tune0",
  "repo/abcjs-synth-midi-01-midi-options-tune0",
  "repo/abcjs-synth-midi-02-staccato-tune0",
  "repo/abcjs-synth-midi-03-percmap-tune0",
  "repo/abcjs-synth-timing-01-cde-fg-ab-1-bcd-2-efg-tune0",
  "repo/abcjs-synth-timing-02-score-1-2-tune0",
  "repo/abcjs-synth-timing-03-cd-e-f-3gab-ac-tune0",
  "repo/abcjs-synth-timing-04-cd-e-f-3gab-ac-tune0",
  "repo/abcjs-synth-timing-05-subtitle-crash-tune0",
  "repo/abcjs-synth-timing-06-repeat-at-start-of-line-crash-tune0",
  "repo/abcjs-synth-timing-07-skip-ties-crash-tune0",
  "repo/abcjs-synth-timing-08-tie-repeat-crash-tune0",
  "repo/abcjs-synth-timing-09-f-c-2d-2-e-4-g-6-a-2-g-4-e-4-tune0",
  "repo/abcjs-synth-timing-10-stretchlast-1-tune0",
  "repo/abcjs-synth-timing-11-stretchlast-1-tune0",
  "repo/abcjs-synth-timing-12-stretchlast-1-tune0",
  "repo/abcjs-visual-decorations-01-score-s-a-b-tune0",
  "repo/abcjs-visual-directives-01-incipit-test-tune0",
  "repo/abcjs-visual-layout-01-barlabelfont-times-bold-18-box-tune0",
  "repo/abcjs-visual-layout-02-barlabelfont-times-bold-18-box-tune0",
  "repo/abcjs-visual-layout-03-cdef-cdef-tune0",
  "repo/abcjs-visual-layout-04-score-s-a-tune0",
  "repo/abcjs-visual-layout-05-c3-abc-cf-3-abc-c3-fa-bc-tune0",
  "repo/abcjs-visual-layout-06-staves-1-2-3-4-tune0",
  "repo/abcjs-visual-layout-07-v-1-b2-a2-tune0",
  "repo/abcjs-visual-layout-08-staffwidth-100-tune0",
  "repo/abcjs-visual-layout-09-endings-tune0",
  "repo/abcjs-visual-misc-01-barnumbers-1-tune0",
  "repo/abcjs-visual-misc-02-title-tune0",
  "repo/abcjs-visual-misc-03-jazzchords-tune0",
  "repo/abcjs-visual-misc-04-stretchlast-tune0",
  "repo/abcjs-visual-misc-05-cccc-d-c-alcoda-dddd-d-c-alfine-eeee-d-s-tune0",
  "repo/abcjs-visual-misc-06-title-1bold-0-100-reg-the-tune0",
  "repo/abcjs-visual-misc-07-ab-ef-g-d-df-f-d-a-4-c-4-tune0",
  "repo/abcjs-visual-misc-08-a2-c2-t-a2t-c2-tune0",
  "repo/abcjs-visual-misc-09-begintext-tune0",
  "repo/abcjs-visual-misc-10-begintext-tune0",
  "repo/abcjs-visual-misc-11-begintext-tune0",
  "repo/abcjs-visual-misc-12-b-beambr1-b-bb-tune0",
  "repo/abcjs-visual-misc-13-ceg-t-gce-d-f-b-3-dm7-d-te-tune0",
  "repo/abcjs-visual-misc-14-tune-tune0",
  "repo/abcjs-visual-mouse-click-01-selection-test-tune0",
  "repo/abcjs-visual-multi-voice-01-score-top-bottom-tune0",
  "repo/abcjs-visual-multi-voice-02-p-c-2b2-z4-f2a2-f4-tune0",
  "repo/abcjs-visual-options-01-fonts-tune0",
  "repo/abcjs-visual-parsing-01-azzz-e2-tune0",
  "repo/abcjs-visual-parsing-02-sx-tune0",
  "repo/abcjs-visual-parsing-03-v-1-f-tune0",
  "repo/abcjs-visual-parsing-04-v-t-c-tune0",
  "repo/abcjs-visual-parsing-05-v-t-c-v-b-a-v-t-d-tune0",
  "repo/abcjs-visual-parsing-06-score-t-b-tune0",
  "repo/abcjs-visual-parsing-07-score-t-b-tune0",
  "repo/abcjs-visual-parsing-08-score-t-b-tune0",
  "repo/abcjs-visual-parsing-09-score-t-b-tune0",
  "repo/abcjs-visual-parsing-10-song-tune0",
  "repo/abcjs-visual-selection-01-selection-test-tune0",
  "repo/abcjs-visual-selection-02-g4-q-left-1-4-170-right-a4-tune0",
  "repo/abcjs-visual-selection-03-c4-tune0",
  "repo/abcjs-visual-slurs-01-score-s-a-tune0",
  "repo/abcjs-visual-slurs-02-score-s-a-t-b-tune0",
  "repo/abcjs-visual-svg-01-staffwidth-5-tune0",
  "repo/abcjs-visual-svg-02-staffwidth-12-tune0",
  "repo/abcjs-visual-svg-03-a4-tune0",
  "repo/abcjs-visual-svg-per-line-01-selection-test-tune0",
  "repo/abcjs-visual-svg-per-line-02-scaled-tune0",
  "repo/abcjs-visual-tablature-01-gr-tune0",
  "repo/abcjs-visual-tablature-02-g-fg-a-g2-a-very-very-long-chord-d2-cd-f-tune0",
  "repo/abcjs-visual-tablature-03-staves-rh-lh-tune0",
  "repo/abcjs-visual-tablature-04-barnumbers-1-tune0",
  "repo/abcjs-visual-tablature-05-a7-a-tune0",
  "repo/abcjs-visual-tablature-06-a7-a-tune0",
  "repo/abcjs-visual-tablature-07-staves-rh-lh-tune0",
  "repo/abcjs-visual-tablature-08-first-tune0",
  "repo/abcjs-visual-tablature-09-f-g-tune0",
  "repo/abcjs-visual-tablature-10-f3-a-y-tune0",
  "repo/abcjs-visual-tablature-11-f-f-tune0",
  "repo/abcjs-visual-tablature-12-b-tune0",
  "repo/abcjs-visual-tablature-13-g8-c4-d4-e4-f4-tune0",
  "repo/abcjs-visual-tablature-14-c-tune0",
  "repo/abcjs-visual-tablature-15-all-element-types-tune0",
  "repo/abcjs-visual-tablature-16-g-g-g-g-tune0",
  "repo/abcjs-visual-tablature-17-stretchlast-tune0",
  "repo/abcjs-visual-tablature-18-a-b-tune0",
  "repo/abcjs-visual-tablature-19-d-a-d-g-b-e-tune0",
  "repo/abcjs-visual-tablature-20-score-1-2-tune0",
  "repo/abcjs-visual-tablature-21-a2-a-a-f-f-f-f-f-e-ee-g-gg-g-k-eb-a2-a2-tune0",
  "repo/abcjs-visual-tablature-22-g-cegda-tune0",
  "repo/abcjs-visual-tablature-23-gab-tune0",
  "repo/abcjs-visual-tablature-24-stretchlast-tune0",
  "repo/abcjs-visual-title-01-not-transformed-tune0",
  "repo/abcjs-visual-title-02-transformed-the-tune0",
  "repo/abcjs-visual-title-03-transformed-the-tune0",
  "repo/abcjs-visual-title-04-transformed-a-tune0",
  "repo/abcjs-visual-title-05-transformed-an-tune0",
  "repo/abcjs-visual-title-06-transformed-a-tune0",
  "repo/abcjs-visual-title-07-24-number-transform-the-tune0",
  "repo/abcjs-visual-title-08-24-number-transform-a-tune0",
  "repo/abcjs-visual-title-09-mal-the-formed-tune0",
  "repo/abcjs-visual-title-10-20-subtitles-the-tune0",
  "repo/abcjs-visual-transpose-01-f2-f-f-f-f-f2-e2-e-e-e-e-e2-k-ab-f2-f-f--tune0",
  "repo/abcjs-visual-transpose-02-cdef-gabc-c-d-e-f-g-a-b-c-c-d-e-f-g-a-b--tune0",
  "repo/abcjs-visual-transpose-03-cdef-gabc-c-d-e-f-g-a-b-c-c-d-e-f-g-a-b--tune0",
  "repo/abcjs-visual-transpose-04-transpose-annotations-tune0",
  "repo/abcjs-visual-transpose-05-n-c-ab-c-c-c-c-d-d-d-d-e-e-f-f-f-f-g-g-g-tune0",
  "repo/abcjs-visual-transpose-06-c-d-e-f-g-a-b-c-cdef-gabc-c-d-e-f-g-a-b--tune0",
  "repo/abcjs-visual-transpose-output-01-transpose-output-tune0",
  "repo/abcjs-visual-transpose-output-02-transpose-output-tune0",
  "repo/abcjs-visual-transpose-output-03-transpose-output-tune0",
  "repo/abcjs-visual-transpose-output-04-transpose-output-tune0",
  "repo/abcjs-visual-transpose-output-05-g-tune0",
  "repo/abcjs-visual-transpose-output-06-f-tune0",
  "repo/abcjs-visual-wrap-01-b-4-c2d2-e3f-gabc-d-e-f-g-marcato-d-e-f--tune0",
  "repo/abcjs-visual-wrap-02-stretchlast-1-tune0",
  "repo/abcjs-visual-wrap-03-piano-wrap-tune0",
  "repo/abcjs-visual-wrap-04-wrap-quartet-tune0",
  "repo/abcjs-visual-wrap-05-score-1-2-3-4-tune0",
  "repo/abcts-keywarn-tune0",
  "repo/abcts-visualtranspose-tune0",
  "repo/abcts-vskip-tune0",
  "sib/S1-decorations-tune0",
  "sib/S2-fields-tune0",
  "sib/S3-note-syntax-tune0",
  "sib/S4-bars-repeats-tune0",
  "sib/S5-directives-tune0",
  "sib/S6-keys-tune0",
  "sib/S7-voices-tune0",
  "sib/S8-layout-tune0",
  "sib/ave-verum-corpus-tune0",
  "sib/brother-john-inline-voices-tune0",
  "sib/center-text-tune0",
  "sib/chord-grid-tune0",
  "sib/clefs-tune0",
  "sib/courtesy-key-before-subtitle-tune0",
  "sib/curves-tune0",
  "sib/escaped-percent-tune0",
  "sib/extra-class-tune0",
  "sib/frere-jacques-tune0",
  "sib/full-song-template-tune0",
  "sib/grandstaff-inline-meter-tune0",
  "sib/happy-birthday-tune0",
  "sib/little swallow-tune0",
  "sib/missing-decorations-tune0",
  "sib/multi-voice-lyrics-two-voices-tune0",
  "sib/multi-voice-rest-collision-tune0",
  "sib/multi-voice-rest-placement-tune0",
  "sib/multi-voice-triplet-brackets-tune0",
  "sib/program-127-test-tune0",
  "sib/ragtime-mini-tune0",
  "sib/score-reorder-shared-tune0",
  "sib/score-reorder-tune0",
  "sib/simple-c-tune0",
  "sib/stacked-annotations-tune0",
  "sib/tunebook-3-tune0",
  "sib/twinkle-tune0",
  "sib/two-voice-invention-tune0",
  "sib/voice-middle-after-clef-tune0",
  "sib/voice-octave-shift-tune0",
  "sib/vree-compound-meter-tune0",
  "sib/vree-grace-notes-tune0",
  "sib/vree-sharps-tune0",
  "sib/vree-slurs-and-triplets-tune0",
  "sib/vree-ties-across-bars-tune0",
  "sib/zocharti-loch-tune0",
];

describe("tuneMetrics — each measure's minimum width", () => {
  const rows = table();

  it("writes the ranked table", () => {
    const off = rows.filter((r) => r.agree < r.total);
    const agree = rows.reduce((t, r) => t + r.agree, 0);
    const total = rows.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-tune-metrics-ranked.txt",
      `${[
        `${off.length} of ${rows.length} tunes differ; ${agree} of ${total} sections agree`,
        "",
        ...off.map((r) => `  ${r.slug.padEnd(54)} ${r.agree}/${r.total}  ${r.first}`),
      ].join("\n")}\n`,
    );
    expect(rows.length).toBeGreaterThan(200);
  });

  it("every ratcheted tune agrees on every section", () => {
    const broken = rows
      .filter((r) => PASSING.includes(r.slug) && r.agree < r.total)
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken.slice(0, 10)).toEqual([]);
  });

  it("nothing outside the ratchet has quietly started agreeing", () => {
    const arrived = rows
      .filter((r) => !PASSING.includes(r.slug) && r.agree === r.total)
      .map((r) => r.slug);
    expect(arrived.length, `${arrived.length} tunes agree — re-ratchet`).toBe(0);
  });
});
