/**
 * **`TuneBook` AND `numberOfTunes` — THE METADATA A HOST READS BEFORE IT PARSES ANYTHING.**
 *
 * The oracle is `tests/corpus-tunebook/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-tunebook.mjs`) — never copied out of its suite, which asserts
 * none of this. Its version is written into the file and CHECKED, because `CLAUDE.md`
 * records a harvester silently rebaselining a byte gate against 6.6.3.
 *
 * ── WHY IT REPLACES A HAND-WRITTEN TEST ─────────────────────────────────────
 * `tunebook.test.ts` beside this one covers the same class in FIVE cases written from a
 * reading of `abc_parse_book.js`. **A test can encode an inference as firmly as a comment
 * can, and is harder to notice**, because a green test reads as a checked fact — three
 * tests in this repo have already had to be rewritten for exactly that. That file is kept
 * for its prose, which says what the quirks ARE; this one is the oracle that says they are
 * abcjs's.
 *
 * ── WHY THE CONTROLS CARRY IT AND THE CORPUS CANNOT ─────────────────────────
 * **`TuneBook` IS STRING SURGERY, NOT PARSING** — a split on `"\nX:"`, a truncation at the
 * first blank line, and more splits to read the title back. So what exercises it is not
 * music: it is blank lines, CRLF, a file header, an `X:` inside a comment, a book with no
 * `X:` at all. Measured before this gate was written: **all 231 fixtures already agreed**,
 * which says the corpus cannot SEE this surface rather than that the surface is right.
 * The 22 control shapes are the ladder. **A GATE IS ONLY AS BROAD AS ITS INPUTS.**
 *
 * ── WHAT IT COMPARES ────────────────────────────────────────────────────────
 * The whole published shape, OFFSETS INCLUDED. `startPos` is what a caller slices with, so
 * a book whose ids and titles are right and whose offsets are one out is still broken, and
 * only a comparison carrying them can say so.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { numberOfTunes, TuneBook } from "../src/compat/tunebook.js";

const golden = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-tunebook", "golden.json"), "utf-8"),
) as {
  abcjs: string;
  cases: Record<string, { abc?: string } | undefined>;
};

const fixtures = join(import.meta.dirname, "corpus-abcjs", "fixtures");

/** The same projection the harvester takes off abcjs, so the two cannot drift. */
const shapeOf = (abc: string): unknown => {
  const book = new TuneBook(abc);
  return JSON.parse(
    JSON.stringify({
      header: book.header,
      numberOfTunes: numberOfTunes(abc),
      tunes: book.tunes.map((t) => ({
        id: t.id,
        title: t.title,
        startPos: t.startPos,
        endPos: (t as { endPos?: number }).endPos,
        abc: t.abc,
        pure: t.pure,
      })),
    }),
  );
};

describe("TuneBook against abcjs", () => {
  it("was harvested from the pinned abcjs", () => {
    expect(golden.abcjs).toBe("6.7.0");
  });

  const controls = Object.keys(golden.cases).filter((k) => k.startsWith("control/"));
  const fixtureCases = Object.keys(golden.cases).filter((k) => k.startsWith("fixture/"));

  it("has the ladder and the corpus in it", () => {
    expect(controls.length).toBe(22);
    expect(fixtureCases.length).toBeGreaterThan(200);
  });

  it.each(controls)("%s", (key) => {
    // A control carries its own input, so this file holds no copy of the ladder to drift.
    const abc = golden.cases[key]?.abc as string;
    expect(typeof abc).toBe("string");
    expect({ abc, ...(shapeOf(abc) as object) }).toEqual(golden.cases[key]);
  });

  /**
   * One assertion for all 231 rather than 231 cases: they were exact before this gate
   * existed and are here to STAY exact, so what matters is the list of any that stop
   * being — which a single diff of names reports better than 231 green lines hide.
   */
  it("matches abcjs on every corpus fixture", () => {
    const differ: string[] = [];
    for (const key of fixtureCases) {
      const abc = readFileSync(join(fixtures, `${key.slice("fixture/".length)}.abc`), "utf-8");
      if (JSON.stringify(shapeOf(abc)) !== JSON.stringify(golden.cases[key])) differ.push(key);
    }
    expect(differ).toEqual([]);
  });
});
