import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";

/**
 * **`tune.makeVoicesArray()` — abcjs's LAYOUT ELEMENTS, COLUMN BY COLUMN.**
 *
 * The oracle is `tests/corpus-voices-array/golden.json`, generated by RUNNING abcjs 6.7.0
 * over EVERY in-repo fixture (`scripts/harvest-abcjs-voices-array.mjs`). Each row is the
 * four the walk itself produces — `top`, `height`, `line`, `measureNumber` — and the six
 * fields of the element that `addElementToEvents` then reads: `type`, `x`, `w`,
 * `duration`, and the `abcelem`'s two characters.
 *
 * **THE ROWS ARE COMPARED IN ORDER AND THE ORDER IS THE DRAWING'S**, so a missing element
 * misaligns everything after it and the gate says where. `elemset` is not compared:
 * abcjs's entries are SVG nodes and ours are the `abcelem` itself, which is stated in
 * `voices-array.ts` — the compat layer emits markup as a string and keeps no nodes.
 */
type Row = [
  number,
  number,
  number,
  number,
  number,
  string,
  number,
  number,
  number | null,
  number | null,
  number | null,
];

const GOLDEN = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "corpus-voices-array", "golden.json"),
    "utf-8",
  ),
) as Record<string, Row[]>;

const IN_REPO = join(import.meta.dirname, "corpus-abcjs", "fixtures");

const ours = (slug: string): Row[] => {
  const abc = readFileSync(join(IN_REPO, `${slug}.abc`), "utf-8");
  const tune = renderAbc(["*"], abc, {})[0];
  if (tune === undefined) return [];
  const rows: Row[] = [];
  tune.makeVoicesArray().forEach((voice, v) => {
    for (const row of voice) {
      const el = row.elem;
      const bag = el.abcelem as Record<string, unknown>;
      rows.push([
        v,
        row.top,
        row.height,
        row.line,
        row.measureNumber,
        el.type,
        el.x,
        el.w,
        el.duration,
        (bag["startChar"] as number | undefined) ?? null,
        (bag["endChar"] as number | undefined) ?? null,
      ]);
    }
  });
  return rows;
};

interface Case {
  readonly slug: string;
  readonly agree: number;
  readonly total: number;
  readonly first: string;
}

const table = (): Case[] =>
  Object.entries(GOLDEN).map(([slug, want]) => {
    const got = ours(slug);
    let agree = 0;
    let first = "";
    for (let i = 0; i < Math.max(want.length, got.length); i += 1) {
      if (JSON.stringify(want[i]) === JSON.stringify(got[i])) agree += 1;
      else if (first === "")
        first = `row ${i}: abcjs ${JSON.stringify(want[i])} ours ${JSON.stringify(got[i])}`;
    }
    return { slug, agree, total: want.length, first };
  });

/** The cases that agree on EVERY row. Shrinks never — see `tests/lines.test.ts`. */
const PASSING: readonly string[] = [
  "abcjs-parse-book_parser-01-example",
  "abcjs-parse-book_parser-02-tune",
  "abcjs-parse-book_parser-03-a",
  "abcjs-parse-book_parser-04-wed",
  "abcjs-parse-book_parser-05-a",
  "abcjs-parse-book_parser-06-a",
  "abcjs-parse-book_parser-07-a",
  "abcjs-parse-note-01-c0-d1-eg-0-fa-1",
  "abcjs-parse-note-id-01-v-v1-c-d-e-f",
  "abcjs-parse-tie-slur-01-staffwidth-200",
  "abcjs-parse-tie-slur-02-staffwidth-200",
  "abcjs-parse-tie-slur-03-staffwidth-200",
  "abcjs-parse-tie-slur-04-stretchlast-1",
  "abcjs-synth-flattener-01-crescendo-efga-gab-crescendo-c-diminuend",
  "abcjs-synth-flattener-02-p-c-def-gabc-d2-b2-g2-f2-f-e-fga-bcde-p-",
  "abcjs-synth-flattener-03-pppp-cdef-gabc-y-ffff-bcba-gfed-y-pppp-c",
  "abcjs-synth-flattener-04-g-gab-cde-d7-fga-def",
  "abcjs-synth-flattener-05-c-cde-def-c2e-d2f-c-c2-d-d-g-d2-e-e",
  "abcjs-synth-flattener-06-cde-d7-f2-d2-e2-f2-1-g-g4-fedc-c-e4z4",
  "abcjs-synth-flattener-07-metronome",
  "abcjs-synth-flattener-08-em-egab",
  "abcjs-synth-flattener-09-d-defg-q-1-2-90-defg",
  "abcjs-synth-flattener-10-q-1-4-129-0476605-cdef-q-1-4-127-gabc-q-",
  "abcjs-synth-flattener-11-midi-program-3",
  "abcjs-synth-flattener-12-chords-meter-change",
  "abcjs-synth-flattener-13-e7-bcde-a-f-break-efe-e7-bc-ignore-de",
  "abcjs-synth-flattener-14-eb7-zg2ga2a2-a2ab-b4-ab-z-break-c2cd2d2-",
  "abcjs-synth-flattener-15-c-c4-c",
  "abcjs-synth-flattener-16-gm-gfdf-gfdf-gf-d2-f-c4",
  "abcjs-synth-flattener-17-midi-grace-notes",
  "abcjs-synth-flattener-18-midi-program-40",
  "abcjs-synth-flattener-19-cdef-z4-fedc",
  "abcjs-synth-flattener-20-k-treble-8-b-a4-ce-f-4-k-treble-8-g8-g-2",
  "abcjs-synth-flattener-21-c4-d4",
  "abcjs-synth-flattener-22-b-c4-d4",
  "abcjs-synth-flattener-23-percmap-d-pedal-hi-hat-x",
  "abcjs-synth-flattener-24-percmap-c-high-tom-x",
  "abcjs-synth-flattener-25-cd-d2-d2-dz",
  "abcjs-synth-flattener-26-gbcd-d4-zcdc-dc3",
  "abcjs-synth-flattener-28-midi-channel-10",
  "abcjs-synth-flattener-29-midi-drum-dddd-76-77-77-77-50-50-50-50",
  "abcjs-synth-flattener-30-am-a2e-e2d-g-bab-d2b-am-a2e-e2d-g-b2a-ga",
  "abcjs-synth-flattener-31-tempo-change-three-voices",
  "abcjs-synth-flattener-32-quarter-tone2",
  "abcjs-synth-flattener-33-tempo-override",
  "abcjs-synth-flattener-34-score-s-a-t-b",
  "abcjs-synth-flattener-35-midi-bassprog-10",
  "abcjs-synth-flattener-36-midi-gchord-fhihfhih",
  "abcjs-synth-flattener-37-midi-gchord-bzczbzcz",
  "abcjs-synth-flattener-38-c-zz-d-z-e-z",
  "abcjs-synth-flattener-39-midi-gchord-bzczbzcz",
  "abcjs-synth-flattener-40-c5-z4",
  "abcjs-synth-flattener-41-midi-bassprog-10-octave-1",
  "abcjs-synth-flattener-42-midi-gchord-ffffffff",
  "abcjs-synth-flattener-43-gm-zzz-cm-zzz",
  "abcjs-synth-flattener-44-cd-pppp-c-ffff-d-ffff-c-pppp-d-cd",
  "abcjs-synth-flattener-45-segno-f-d2",
  "abcjs-synth-flattener-46-c8-1-d8-2-e8-3-f8",
  "abcjs-synth-midi-01-midi-options",
  "abcjs-synth-midi-02-staccato",
  "abcjs-synth-midi-03-percmap",
  "abcjs-synth-timing-01-cde-fg-ab-1-bcd-2-efg",
  "abcjs-synth-timing-02-score-1-2",
  "abcjs-synth-timing-03-cd-e-f-3gab-ac",
  "abcjs-synth-timing-04-cd-e-f-3gab-ac",
  "abcjs-synth-timing-05-subtitle-crash",
  "abcjs-synth-timing-06-repeat-at-start-of-line-crash",
  "abcjs-synth-timing-07-skip-ties-crash",
  "abcjs-synth-timing-08-tie-repeat-crash",
  "abcjs-synth-timing-09-f-c-2d-2-e-4-g-6-a-2-g-4-e-4",
  "abcjs-synth-timing-10-stretchlast-1",
  "abcjs-synth-timing-11-stretchlast-1",
  "abcjs-synth-timing-12-stretchlast-1",
  "abcjs-visual-decorations-01-score-s-a-b",
  "abcjs-visual-directives-01-incipit-test",
  "abcjs-visual-layout-01-barlabelfont-times-bold-18-box",
  "abcjs-visual-layout-02-barlabelfont-times-bold-18-box",
  "abcjs-visual-layout-03-cdef-cdef",
  "abcjs-visual-layout-05-c3-abc-cf-3-abc-c3-fa-bc",
  "abcjs-visual-layout-06-staves-1-2-3-4",
  "abcjs-visual-layout-07-v-1-b2-a2",
  "abcjs-visual-layout-08-staffwidth-100",
  "abcjs-visual-layout-09-endings",
  "abcjs-visual-misc-01-barnumbers-1",
  "abcjs-visual-misc-02-title",
  "abcjs-visual-misc-03-jazzchords",
  "abcjs-visual-misc-04-stretchlast",
  "abcjs-visual-misc-05-cccc-d-c-alcoda-dddd-d-c-alfine-eeee-d-s",
  "abcjs-visual-misc-06-title-1bold-0-100-reg-the",
  "abcjs-visual-misc-07-ab-ef-g-d-df-f-d-a-4-c-4",
  "abcjs-visual-misc-08-a2-c2-t-a2t-c2",
  "abcjs-visual-misc-09-begintext",
  "abcjs-visual-misc-10-begintext",
  "abcjs-visual-misc-11-begintext",
  "abcjs-visual-misc-12-b-beambr1-b-bb",
  "abcjs-visual-misc-13-ceg-t-gce-d-f-b-3-dm7-d-te",
  "abcjs-visual-misc-14-tune",
  "abcjs-visual-mouse-click-01-selection-test",
  "abcjs-visual-multi-voice-01-score-top-bottom",
  "abcjs-visual-multi-voice-02-p-c-2b2-z4-f2a2-f4",
  "abcjs-visual-options-01-fonts",
  "abcjs-visual-parsing-01-azzz-e2",
  "abcjs-visual-parsing-02-sx",
  "abcjs-visual-parsing-03-v-1-f",
  "abcjs-visual-parsing-04-v-t-c",
  "abcjs-visual-parsing-05-v-t-c-v-b-a-v-t-d",
  "abcjs-visual-parsing-06-score-t-b",
  "abcjs-visual-parsing-07-score-t-b",
  "abcjs-visual-parsing-08-score-t-b",
  "abcjs-visual-parsing-09-score-t-b",
  "abcjs-visual-parsing-10-song",
  "abcjs-visual-selection-01-selection-test",
  "abcjs-visual-selection-02-g4-q-left-1-4-170-right-a4",
  "abcjs-visual-selection-03-c4",
  "abcjs-visual-slurs-01-score-s-a",
  "abcjs-visual-slurs-02-score-s-a-t-b",
  "abcjs-visual-svg-01-staffwidth-5",
  "abcjs-visual-svg-02-staffwidth-12",
  "abcjs-visual-svg-03-a4",
  "abcjs-visual-svg-per-line-01-selection-test",
  "abcjs-visual-svg-per-line-02-scaled",
  "abcjs-visual-tablature-01-gr",
  "abcjs-visual-tablature-02-g-fg-a-g2-a-very-very-long-chord-d2-cd-f",
  "abcjs-visual-tablature-03-staves-rh-lh",
  "abcjs-visual-tablature-04-barnumbers-1",
  "abcjs-visual-tablature-05-a7-a",
  "abcjs-visual-tablature-06-a7-a",
  "abcjs-visual-tablature-07-staves-rh-lh",
  "abcjs-visual-tablature-08-first",
  "abcjs-visual-tablature-09-f-g",
  "abcjs-visual-tablature-10-f3-a-y",
  "abcjs-visual-tablature-11-f-f",
  "abcjs-visual-tablature-12-b",
  "abcjs-visual-tablature-13-g8-c4-d4-e4-f4",
  "abcjs-visual-tablature-14-c",
  "abcjs-visual-tablature-15-all-element-types",
  "abcjs-visual-tablature-16-g-g-g-g",
  "abcjs-visual-tablature-17-stretchlast",
  "abcjs-visual-tablature-18-a-b",
  "abcjs-visual-tablature-19-d-a-d-g-b-e",
  "abcjs-visual-tablature-20-score-1-2",
  "abcjs-visual-tablature-21-a2-a-a-f-f-f-f-f-e-ee-g-gg-g-k-eb-a2-a2",
  "abcjs-visual-tablature-22-g-cegda",
  "abcjs-visual-tablature-23-gab",
  "abcjs-visual-tablature-24-stretchlast",
  "abcjs-visual-title-01-not-transformed",
  "abcjs-visual-title-02-transformed-the",
  "abcjs-visual-title-03-transformed-the",
  "abcjs-visual-title-04-transformed-a",
  "abcjs-visual-title-05-transformed-an",
  "abcjs-visual-title-06-transformed-a",
  "abcjs-visual-title-07-24-number-transform-the",
  "abcjs-visual-title-08-24-number-transform-a",
  "abcjs-visual-title-09-mal-the-formed",
  "abcjs-visual-title-10-20-subtitles-the",
  "abcjs-visual-transpose-01-f2-f-f-f-f-f2-e2-e-e-e-e-e2-k-ab-f2-f-f-",
  "abcjs-visual-transpose-02-cdef-gabc-c-d-e-f-g-a-b-c-c-d-e-f-g-a-b-",
  "abcjs-visual-transpose-03-cdef-gabc-c-d-e-f-g-a-b-c-c-d-e-f-g-a-b-",
  "abcjs-visual-transpose-04-transpose-annotations",
  "abcjs-visual-transpose-05-n-c-ab-c-c-c-c-d-d-d-d-e-e-f-f-f-f-g-g-g",
  "abcjs-visual-transpose-06-c-d-e-f-g-a-b-c-cdef-gabc-c-d-e-f-g-a-b-",
  "abcjs-visual-transpose-output-01-transpose-output",
  "abcjs-visual-transpose-output-02-transpose-output",
  "abcjs-visual-transpose-output-03-transpose-output",
  "abcjs-visual-transpose-output-04-transpose-output",
  "abcjs-visual-transpose-output-05-g",
  "abcjs-visual-transpose-output-06-f",
  "abcjs-visual-wrap-01-b-4-c2d2-e3f-gabc-d-e-f-g-marcato-d-e-f-",
  "abcjs-visual-wrap-02-stretchlast-1",
  "abcjs-visual-wrap-03-piano-wrap",
  "abcjs-visual-wrap-04-wrap-quartet",
  "abcjs-visual-wrap-05-score-1-2-3-4",
  "abcts-keywarn",
  "abcts-visualtranspose",
  "abcts-vskip",
];

describe("makeVoicesArray — the layout elements a host is handed", () => {
  const rows = table();

  it("writes the ranked table", () => {
    const off = rows.filter((r) => r.agree < r.total);
    const agree = rows.reduce((t, r) => t + r.agree, 0);
    const total = rows.reduce((t, r) => t + r.total, 0);
    writeFileSync(
      "/tmp/abcts-voices-array-ranked.txt",
      `${[
        `${off.length} of ${rows.length} tunes differ; ${agree} of ${total} rows agree`,
        "",
        ...off.map(
          (r) => `  ${r.slug.padEnd(52)} ${r.agree}/${r.total}  ${r.first}`,
        ),
      ].join("\n")}\n`,
    );
    expect(rows.length).toBeGreaterThan(150);
  });

  it("every ratcheted tune agrees on every row", () => {
    const broken = rows
      .filter((r) => PASSING.includes(r.slug) && r.agree < r.total)
      .map((r) => `${r.slug} ${r.agree}/${r.total} ${r.first}`);
    expect(broken.slice(0, 10)).toEqual([]);
  });

  it("nothing outside the ratchet has quietly started passing", () => {
    const arrived = rows
      .filter((r) => !PASSING.includes(r.slug) && r.agree === r.total)
      .map((r) => r.slug);
    expect(arrived.length, `${arrived.length} tunes now agree — re-ratchet`).toBe(
      0,
    );
  });
});
