import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { parseOnly } from "../src/compat/index.js";

/**
 * **`tune.warnings` — THE STRINGS A HOST SHOWS, TUNE BY TUNE.**
 *
 * The oracle is `tests/corpus-warnings/golden.json`, generated by RUNNING abcjs 6.7.0's
 * PARSER over every fixture of both corpora (`scripts/harvest-abcjs-warnings.mjs`). Each
 * entry is the array verbatim, or `null` where abcjs hangs no `warnings` field at all —
 * and that difference is the point: `Editor` shows "No errors" for an absent field, so an
 * empty array would be a different answer.
 *
 * **THE FORMAT IS AS MUCH OF THE CONTRACT AS THE WORDING** — see `warnings.ts`. The whole
 * string is compared, `<span>` and all.
 *
 * ⚠️ **OUR PARSER RAISES ALMOST NONE OF THESE YET.** Measured over both corpora: 68 abcjs
 * warnings of about a dozen kinds, against ONE diagnostic code of ours (`unknown-directive`,
 * 5 occurrences). So this gate opens WIDE and closes a kind at a time — each is a parser
 * site plus one line of `AS_ABCJS`, and each is independently visible here.
 */
const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-warnings", "golden.json"), "utf-8"),
) as Record<string, string[] | null>;

const config = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "abcts.config.json"), "utf-8"),
) as { corpus: string };

const DIRS: Record<string, string> = {
  repo: join(import.meta.dirname, "corpus-abcjs", "fixtures"),
  sib: join(import.meta.dirname, "..", config.corpus),
};

/** Parsed once per FILE — the key is `<corpus>/<file>-tune<N>`. */
const cache = new Map<string, (string[] | undefined)[]>();
const ours = (key: string): string[] | null => {
  const [corpus = "", rest = ""] = key.split("/");
  const at = rest.lastIndexOf("-tune");
  const file = rest.substring(0, at);
  const index = Number(rest.substring(at + 5));
  const path = join(DIRS[corpus] ?? "", `${file}.abc`);
  let all = cache.get(path);
  if (all === undefined) {
    const abc = readFileSync(path, "utf-8");
    all = parseOnly(abc).map(
      (tune) => (tune as { warnings?: readonly string[] }).warnings as string[] | undefined,
    );
    cache.set(path, all);
  }
  return all[index] ?? null;
};

interface Row {
  readonly slug: string;
  readonly want: string[] | null;
  readonly got: string[] | null;
}

const rows = (): Row[] =>
  Object.entries(GOLDEN).map(([slug, want]) => ({ slug, want, got: ours(slug) }));

/** Tunes whose warnings agree exactly — the field's PRESENCE included. Grows, never shrinks. */
const PASSING: readonly string[] = [
  "repo/abcjs-parse-book_parser-04-wed-tune0",
  "repo/abcjs-parse-book_parser-05-a-tune0",
  "repo/abcjs-parse-book_parser-05-a-tune1",
  "repo/abcjs-parse-book_parser-06-a-tune0",
  "repo/abcjs-synth-flattener-42-midi-gchord-ffffffff-tune0",
  "repo/abcjs-visual-options-01-fonts-tune0",
  "repo/abcts-keywarn-tune2",
];

describe("tune.warnings — what a host shows", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table.filter(
      (r) => JSON.stringify(r.want) !== JSON.stringify(r.got),
    );
    const warned = table.filter((r) => r.want !== null);
    writeFileSync(
      "/tmp/abcts-warnings-ranked.txt",
      `${[
        `${off.length} of ${table.length} tunes differ; ${warned.length} tunes warn in abcjs, ` +
          `${warned.reduce((n, r) => n + (r.want?.length ?? 0), 0)} warnings`,
        "",
        ...off.map(
          (r) =>
            `  ${r.slug}\n      abcjs ${JSON.stringify(r.want)?.slice(0, 200)}\n      ours  ${JSON.stringify(r.got)?.slice(0, 200)}`,
        ),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(300);
  });

  it("a tune with no abcjs warnings has no field on ours either", () => {
    const wrong = table
      .filter((r) => r.want === null && r.got !== null)
      .map((r) => `${r.slug}: ours ${JSON.stringify(r.got)}`);
    expect(wrong).toEqual([]);
  });

  it("every ratcheted tune agrees exactly", () => {
    const broken = table
      .filter((r) => PASSING.includes(r.slug))
      .filter((r) => JSON.stringify(r.want) !== JSON.stringify(r.got))
      .map((r) => r.slug);
    expect(broken).toEqual([]);
  });

  it("nothing outside the ratchet has quietly started agreeing", () => {
    const arrived = table
      .filter((r) => !PASSING.includes(r.slug) && r.want !== null)
      .filter((r) => JSON.stringify(r.want) === JSON.stringify(r.got))
      .map((r) => r.slug);
    expect(
      arrived,
      "these agree — add them to PASSING so the ratchet holds them",
    ).toEqual([]);
  });
});
