import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { parseOnly } from "../src/compat/index.js";

/**
 * **`tune.warnings` — THE STRINGS A HOST SHOWS, TUNE BY TUNE.**
 *
 * The oracle is `tests/corpus-warnings/golden.json`, generated by RUNNING abcjs 6.7.0's
 * PARSER over every fixture of both corpora (`scripts/harvest-abcjs-warnings.mjs`). Each
 * entry is the array verbatim, or `null` where abcjs hangs no `warnings` field at all —
 * and that difference is the point: `Editor` shows "No errors" for an absent field, so an
 * empty array would be a different answer.
 *
 * **THE FORMAT IS AS MUCH OF THE CONTRACT AS THE WORDING** — see `warnings.ts`. The whole
 * string is compared, `<span>` and all.
 *
 * ⚠️ **OUR PARSER RAISES ALMOST NONE OF THESE YET.** Measured over both corpora: 68 abcjs
 * warnings of about a dozen kinds, against ONE diagnostic code of ours (`unknown-directive`,
 * 5 occurrences). So this gate opens WIDE and closes a kind at a time — each is a parser
 * site plus one line of `AS_ABCJS`, and each is independently visible here.
 */
const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-warnings", "golden.json"), "utf-8"),
) as Record<string, string[] | null>;

const config = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "abcts.config.json"), "utf-8"),
) as { corpus: string };

const DIRS: Record<string, string> = {
  repo: join(import.meta.dirname, "corpus-abcjs", "fixtures"),
  sib: join(import.meta.dirname, "..", config.corpus),
};

/** Parsed once per FILE — the key is `<corpus>/<file>-tune<N>`. */
const cache = new Map<string, (string[] | undefined)[]>();
const ours = (key: string): string[] | null => {
  const [corpus = "", rest = ""] = key.split("/");
  const at = rest.lastIndexOf("-tune");
  const file = rest.substring(0, at);
  const index = Number(rest.substring(at + 5));
  const path = join(DIRS[corpus] ?? "", `${file}.abc`);
  let all = cache.get(path);
  if (all === undefined) {
    const abc = readFileSync(path, "utf-8");
    all = parseOnly(abc).map(
      (tune) => (tune as { warnings?: readonly string[] }).warnings as string[] | undefined,
    );
    cache.set(path, all);
  }
  return all[index] ?? null;
};

interface Row {
  readonly slug: string;
  readonly want: string[] | null;
  readonly got: string[] | null;
}

const rows = (): Row[] =>
  Object.entries(GOLDEN).map(([slug, want]) => ({ slug, want, got: ours(slug) }));

/** Tunes whose warnings agree exactly — the field's PRESENCE included. Grows, never shrinks. */
const PASSING: readonly string[] = [
  // …and the third-tone microtone of `abcts-ledger-gaps-4`, whose four characters abcjs
  // warns about one at a time.
  /**
   * `[V:1]P:A` — a `P:` written on a music line rather than as a field. `getBarLine`'s
   * `case ':'` returns `{len: 1, warn: "Unknown bar symbol"}` for anything that is not `:`
   * or `|` after it, and the caller then finds an empty type and warns AGAIN at the same
   * column: TWO warnings on one character where this engine had `Unknown character
   * ignored` once.
   */
  "repo/abcts-tempo-rung-tune0",
  "repo/abcts-tempo-rung-tune1",
  "repo/abcts-tempo-rung-tune2",
  "repo/abcts-tempo-rung-tune3",
  /**
   * `[C"Am"E]` — an unparseable token ends the chord where it stands, and abcjs WARNS as it
   * stops: `warn("Expected ']' to end the chords", line, index)` (`abc_parse_music.js:487`).
   * The GEOMETRY has agreed since that rule landed on 2026-08-21 and only the diagnostic
   * was missing, which is what this row has read ever since.
   */
  "repo/abcts-ledger-gaps-tune2",
  "repo/abcts-ledger-gaps-4-tune2",
  "repo/abcjs-parse-book_parser-04-wed-tune0",
  "repo/abcjs-parse-book_parser-05-a-tune0",
  "repo/abcjs-parse-book_parser-05-a-tune1",
  "repo/abcjs-parse-book_parser-06-a-tune0",
  "repo/abcjs-synth-flattener-42-midi-gchord-ffffffff-tune0",
  "repo/abcjs-synth-midi-02-staccato-tune0",
  "repo/abcjs-visual-options-01-fonts-tune0",
  "repo/abcjs-visual-parsing-01-azzz-e2-tune0",
  "repo/abcjs-visual-tablature-01-gr-tune0",
  "repo/abcts-keywarn-tune2",
  /**
   * `K:C clef=alto =f` — the `=f` stands AFTER a modifier, so it is past
   * `getKeyAccidentals2` and reaches the modifier switch's `default` arm as TWO tokens:
   * `Unknown parameter: =` at column 12 and `Unknown parameter: f` at 13, on ADJACENT
   * characters. Neither is findable by its text — `indexOf('=')` takes the one inside
   * `clef=` — so the column travels with the diagnostic; see `Diagnostic.column`.
   */
  "repo/abcts-key-modifiers-tune9",
  /**
   * **EVERY `abcts-*` FIXTURE'S AGREEING ROW.** These are the rows where our parser already
   * says exactly what abcjs says, and most of them have agreed for weeks: each fixture opens
   * with an `%%abcts` header comment, which abcjs answers with `Unknown directive: abcts`,
   * and nothing had ever ratcheted them.
   *
   * ⚠️ **A GATE'S RATCHET IS ONLY AS BROAD AS WHAT SOMEBODY ADDED TO IT.** The list held
   * fourteen rows while thirty-nine agreed, so twenty-five could have regressed in silence
   * — the same shape as the byte gate holding 4% of what was green. The gate itself was
   * built to say so and its message says so ("these agree — add them to PASSING"); it just
   * had to be read.
   */
  /**
   * `abcts-void-notes-and-stray-ties.abc` — the ladder that closed this gate's last row,
   * and the two GEOMETRY defects it found on the way: a note whose length is followed by a
   * digit is VOID, and a tie split across a system takes the 20px stub rather than the
   * prefix.
   */
  "repo/abcts-void-notes-and-stray-ties-tune0",
  "repo/abcts-void-notes-and-stray-ties-tune2",
  "repo/abcts-void-notes-and-stray-ties-tune3",
  "repo/abcts-void-notes-and-stray-ties-tune7",
  /**
   * `abcts-text-udef-parts-overlays.abc` — the third sweep. Two of its rows were warnings
   * and nothing else: a `U:` naming a decoration abcjs does not know warns "Unknown macro"
   * and expands to NOTHING (`U:T=!nil!` is the idiom for defining a shorthand away), and a
   * bare `%%center` is a centred EMPTY line rather than an unknown directive.
   */
  "repo/abcts-text-udef-parts-overlays-tune18",
  "repo/abcts-text-udef-parts-overlays-tune19",
  "repo/abcts-text-udef-parts-overlays-tune43",
  "repo/abcts-text-udef-parts-overlays-tune44",
  /**
   * `abcts-staffnonote-and-directives.abc` — abcjs's DIRECTIVE SWITCH enumerated against our
   * parser. **Five of these rows were us warning `Unknown directive` where abcjs knows the
   * directive and says nothing** (`%%papersize` and the four `%%-` info fields): "never
   * mentioned in our parser" is not "not implemented by abcjs". And `%%staffnonote 2` echoes
   * the value back in its message, which is why `directive-message` exists beside
   * `directive-parameter` — the latter REWRITES its sentence and cannot produce both.
   *
   * ⚠️ **`%%beginps` IS NOT HERE AND IS A RULED DIVERGENCE.** abcjs warns `Postscript
   * ignored` at the line AFTER the block, because `iChar` has advanced while the context
   * string has not — a byproduct of the same loop that makes a NON-empty `%%beginps` spin
   * forever. See `Docs/ABCJS-DIFFERENCES.md`; we decline to reproduce the hang, and this
   * row is its shadow on the one shape that terminates.
   */
  "repo/abcts-staffnonote-and-directives-tune13",
  "repo/abcts-staffnonote-and-directives-tune14",
  "repo/abcts-staffnonote-and-directives-tune15",
  "repo/abcts-staffnonote-and-directives-tune6",
  "repo/abcts-bars-graces-and-groups-tune0",
  "repo/abcts-bars-graces-and-groups-tune40",
  "repo/abcts-bars-graces-and-groups-tune6",
  "repo/abcts-inline-fields-and-blocks-tune9",
  "repo/abcts-rests-and-bars-tune15",
  "repo/abcts-stafflines-and-modifiers-tune10",
  "repo/abcts-stafflines-and-modifiers-tune11",
  "repo/abcts-stafflines-and-modifiers-tune12",
  /**
   * `C2|[-1 D2|]` — the last row this gate ever held open. The chord fails on the `-`,
   * abcjs warns "Expected ']' to end the chords", and then TWICE more: `getCoreNote`'s `-`
   * arm ties back to the previous note and leaves the state at `startSlur`, so the DIGIT
   * after it reaches an arm it has none for and returns null, and every character of the
   * failed attempt warns in turn. The tie is KEPT — `addTieToLastNote` has already run.
   */
  "repo/abcts-endings-tune5",
  "repo/abcts-endings-tune0",
  "repo/abcts-endings-tune1",
  "repo/abcts-endings-tune2",
  "repo/abcts-endings-tune3",
  "repo/abcts-endings-tune4",
  "repo/abcts-endings-tune6",
  "repo/abcts-endings-tune7",
  "repo/abcts-grace-tie-tune0",
  "repo/abcts-grace-tie-tune1",
  "repo/abcts-grace-tie-tune2",
  "repo/abcts-grace-tie-tune3",
  "repo/abcts-grace-tie-tune4",
  "repo/abcts-grace-tie-tune5",
  "repo/abcts-grace-tie-tune6",
  "repo/abcts-grace-tie-tune7",
  "repo/abcts-pitch-style-tune0",
  "repo/abcts-pitch-style-tune1",
  "repo/abcts-pitch-style-tune2",
  "repo/abcts-pitch-style-tune3",
  "repo/abcts-pitch-style-tune4",
  "repo/abcts-pitch-style-tune5",
  "repo/abcts-pitch-style-tune6",
  "repo/abcts-pitch-style-tune7",
  "repo/abcts-rests-and-bars-tune0",
  "repo/abcts-rests-and-bars-tune1",
  "repo/abcts-rests-and-bars-tune10",
  "repo/abcts-rests-and-bars-tune11",
  "repo/abcts-rests-and-bars-tune12",
  "repo/abcts-rests-and-bars-tune13",
  "repo/abcts-rests-and-bars-tune14",
  "repo/abcts-rests-and-bars-tune2",
  "repo/abcts-rests-and-bars-tune3",
  "repo/abcts-rests-and-bars-tune4",
  "repo/abcts-rests-and-bars-tune5",
  "repo/abcts-rests-and-bars-tune6",
  "repo/abcts-rests-and-bars-tune7",
  "repo/abcts-rests-and-bars-tune8",
  "repo/abcts-rests-and-bars-tune9",
  "repo/abcts-stafflines-and-modifiers-tune23",
  "repo/abcts-stafflines-and-modifiers-tune25",
  "repo/abcts-stafflines-and-modifiers-tune6",
  "repo/abcts-stafflines-and-modifiers-tune7",
  "repo/abcts-stafflines-and-modifiers-tune8",
  "sib/S1-decorations-tune0",
  "sib/S3-note-syntax-tune1",
  "sib/S3-note-syntax-tune6",
  "sib/S3-note-syntax-tune8",
  "sib/frere-jacques-tune0",
  "sib/vree-sharps-tune0",
];

/**
 * ✅ **THIS GATE IS AT ZERO — 0 of 688.** It opened at 68 abcjs warnings of a dozen kinds
 * against ONE diagnostic code of ours, and the note below it still describes that day.
 *
 * ⚠️ **SO IT CAN NAME NOTHING, AND THAT IS THE NORMAL CONDITION HERE.** What it caught last
 * came from FIXTURES written for the byte gate: two byte-exact sweeps moved it the moment
 * they were pages. Widen it by widening the corpus, not by staring at it.
 */
describe("tune.warnings — what a host shows", () => {
  const table = rows();

  it("writes the ranked table", () => {
    const off = table.filter(
      (r) => JSON.stringify(r.want) !== JSON.stringify(r.got),
    );
    const warned = table.filter((r) => r.want !== null);
    writeFileSync(
      "/tmp/abcts-warnings-ranked.txt",
      `${[
        `${off.length} of ${table.length} tunes differ; ${warned.length} tunes warn in abcjs, ` +
          `${warned.reduce((n, r) => n + (r.want?.length ?? 0), 0)} warnings`,
        "",
        ...off.map(
          (r) =>
            `  ${r.slug}\n      abcjs ${JSON.stringify(r.want)?.slice(0, 200)}\n      ours  ${JSON.stringify(r.got)?.slice(0, 200)}`,
        ),
      ].join("\n")}\n`,
    );
    expect(table.length).toBeGreaterThan(300);
  });

  it("a tune with no abcjs warnings has no field on ours either", () => {
    const wrong = table
      .filter((r) => r.want === null && r.got !== null)
      .map((r) => `${r.slug}: ours ${JSON.stringify(r.got)}`);
    expect(wrong).toEqual([]);
  });

  it("every ratcheted tune agrees exactly", () => {
    const broken = table
      .filter((r) => PASSING.includes(r.slug))
      .filter((r) => JSON.stringify(r.want) !== JSON.stringify(r.got))
      .map((r) => r.slug);
    expect(broken).toEqual([]);
  });

  it("nothing outside the ratchet has quietly started agreeing", () => {
    const arrived = table
      .filter((r) => !PASSING.includes(r.slug) && r.want !== null)
      .filter((r) => JSON.stringify(r.want) === JSON.stringify(r.got))
      .map((r) => r.slug);
    expect(
      arrived,
      "these agree — add them to PASSING so the ratchet holds them",
    ).toEqual([]);
  });
});
