import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";

/**
 * **`renderAbc(…, {wrap})` — THE TWO THINGS IT HANDS BACK.**
 *
 * `tune.explanation` is the wrap search's own reasoning, one row per ORIGINAL line: the
 * measured `widths` (the prefix `left`, every `measureWidths`, and their `total`), the
 * `lineBreakPoint` it aimed at, the `minLineSize` it would not go under, the `staffWidth`
 * it was given and the `minWidth` it settled on. `tune.lineBreaks` is the ANSWER — one row
 * per drawn line, saying which original line it came from (`ogLine`) and which slice of
 * that voice it holds (`start`, `end`).
 *
 * ── THE ORACLE ──────────────────────────────────────────────────────────────
 * `tests/corpus-wrap/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-wrap.ts`) over its OWN wrap inputs — the six `var abc…`
 * declarations in `tests/visual/wrap.test.js`, pulled out by evaluating that file.
 *
 * ⚠️ **THE INPUTS ARE COPIED AND THE EXPECTATIONS ARE NOT.** abcjs's suite carries expected
 * literals beside each input; every number here comes from running the engine instead. The
 * distinction earned itself on `strTranspose`, where abcjs's own test expects something
 * abcjs does not produce.
 *
 * ⚠️ **AND THREE OF THE ELEVEN CASES ARE OURS.** abcjs renders each input at ONE width, and
 * a wrap measured at one width is a control that cannot move; `piano-300`, `quartet-740`
 * and `split-by-text-300` are the same tunes at a width its suite never tries.
 *
 * ⚠️ **AND THE ROUNDING IS THE TEST'S, NOT abcjs's.** `doWrapTest` rounds `lineBreakPoint`,
 * `minLineSize` and every width to ONE DECIMAL before comparing (`wrap.test.js:296-311`).
 * The golden records the RAW doubles and this rounds on the way in, so the tolerance is
 * visible here rather than baked into the oracle.
 */
const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-wrap", "golden.json"), "utf-8"),
) as Record<
  string,
  {
    abc: string;
    staffwidth: number;
    explanation: Record<string, unknown>[];
    lineBreaks: Record<string, unknown>[] | null;
    svg: string;
  }
>;

/** `doWrapTest`'s own options — the only ones abcjs's suite ever passes. */
const WRAP = { minSpacing: 1.8, maxSpacing: 2.8, preferredMeasuresPerLine: 4 };

const round1 = (n: number): number => Math.round(n * 10) / 10;

/** `wrap.test.js:296-311`, exactly — and it rounds only what it names. */
const rounded = (rows: readonly Record<string, unknown>[]): unknown[] =>
  rows.map((row) => {
    const out: Record<string, unknown> = { ...row };
    delete out.attempts;
    if (typeof out.lineBreakPoint === "number")
      out.lineBreakPoint = round1(out.lineBreakPoint);
    if (typeof out.minLineSize === "number") out.minLineSize = round1(out.minLineSize);
    const w = out.widths as
      | { left?: number; total?: number; measureWidths?: number[] }
      | undefined;
    if (w !== undefined)
      out.widths = {
        ...w,
        ...(typeof w.left === "number" ? { left: round1(w.left) } : {}),
        ...(typeof w.total === "number" ? { total: round1(w.total) } : {}),
        ...(w.measureWidths === undefined
          ? {}
          : { measureWidths: w.measureWidths.map(round1) }),
      };
    return out;
  });

interface Row {
  readonly slug: string;
  readonly wantExplanation: unknown[];
  readonly gotExplanation: unknown[];
  readonly wantBreaks: unknown;
  readonly gotBreaks: unknown;
  /**
   * ⚠️ **AND THE DRAWING IS THE THIRD SURFACE, BECAUSE THE FIRST TWO CAN BE EXACT WHILE THE
   * MUSIC IS NOT RE-LINED AT ALL.** That is what this engine did until `applyLineBreaks`
   * landed: `explanation` and `lineBreaks` byte-perfect on all eleven cases, and ONE system
   * drawn where abcjs draws four. A surface that reports the right answer and does not act
   * on it passes every gate built to read the report.
   */
  readonly svgMatches: boolean;
}

const ours = (
  slug: string,
): { explanation: unknown[]; lineBreaks: unknown; svg: string } => {
  const c = GOLDEN[slug];
  if (c === undefined) return { explanation: [], lineBreaks: null, svg: "" };
  /**
   * ⚠️ **A HEADLESS RENDER NEVER WRAPS, AND THAT IS abcjs's OWN GUARD.**
   * `if (div === "*") removeDiv = true` and then `if (!removeDiv && params.wrap &&
   * params.staffwidth)` (`api/abc_tunebook_svg.js:112-120`) — so `renderAbc('*', abc,
   * {wrap})` comes back with NO `explanation` and NO `lineBreaks` at all, silently. The
   * harvester hit it first and read eleven empty cases as a result rather than an error.
   */
  // …and the target is an ELEMENT, not the string `"paper"`: a selector needs a `document`
  // to resolve against and there is none here, so a string would silently be no target at
  // all — the same absence `'*'` gives, arrived at a different way.
  const tune = renderAbc({ innerHTML: "" }, c.abc, {
    staffwidth: c.staffwidth,
    wrap: WRAP,
  })[0] as unknown as {
    explanation?: Record<string, unknown>[];
    lineBreaks?: unknown;
    svg?: string;
  };
  return {
    explanation: rounded(tune.explanation ?? []),
    lineBreaks: tune.lineBreaks ?? null,
    svg: tune.svg ?? "",
  };
};

const rows = (): Row[] =>
  Object.entries(GOLDEN).map(([slug, c]) => {
    const got = ours(slug);
    return {
      slug,
      wantExplanation: rounded(c.explanation),
      gotExplanation: got.explanation,
      wantBreaks: c.lineBreaks,
      gotBreaks: got.lineBreaks,
      svgMatches: got.svg === c.svg,
    };
  });

/**
 * Cases that agree on BOTH surfaces. Grows, never shrinks.
 *
 * **ALL ELEVEN ON THE FIRST RUN**, which is what the measurement half being already built
 * bought: `getMeasureWidths` lays out at width ZERO whatever `staffwidth` says
 * (`engraver-controller.js:139`), so it is the very call `tuneMetrics` makes — already
 * ported and already gated at 0 of 261. Checked before a line of the search was written:
 * our `widths` are bit-for-bit abcjs's on this oracle, long tails and all
 * (`115.94789193789369`, `20.435498264067185`). What was left was pure arithmetic.
 */
const PASSING: readonly string[] = [
  "short-measures-740",
  "single-line-400",
  "single-line-500",
  "single-line-600",
  "split-by-text-500",
  "piano-500",
  "quartet-500",
  "share-staff-300",
  // …and the three widths abcjs's own suite never renders — a wrap measured at one width
  // is a control that cannot move.
  "piano-300",
  "quartet-740",
  "split-by-text-300",
];

describe("renderAbc({wrap}) — the explanation and the line breaks", () => {
  const table = rows();

  it("measured something real", () => {
    expect(table.length).toBe(11);
    // Every case must have an oracle with rows in it, or the gate is measuring silence —
    // which is exactly what `'*'` gave the harvester before it rendered into a target.
    expect(table.filter((r) => r.wantExplanation.length === 0)).toEqual([]);
  });

  it("every ratcheted case agrees on all three surfaces", () => {
    const broken = table
      .filter((r) => PASSING.includes(r.slug))
      .filter(
        (r) =>
          JSON.stringify(r.wantExplanation) !== JSON.stringify(r.gotExplanation) ||
          JSON.stringify(r.wantBreaks) !== JSON.stringify(r.gotBreaks) ||
          !r.svgMatches,
      )
      .map((r) => r.slug);
    expect(broken).toEqual([]);
  });

  it("nothing outside the ratchet has quietly started agreeing", () => {
    const arrived = table
      .filter((r) => !PASSING.includes(r.slug))
      .filter(
        (r) =>
          JSON.stringify(r.wantExplanation) === JSON.stringify(r.gotExplanation) &&
          JSON.stringify(r.wantBreaks) === JSON.stringify(r.gotBreaks) &&
          r.svgMatches,
      )
      .map((r) => r.slug);
    expect(
      arrived,
      `${arrived.length} agree — add them to PASSING so the ratchet holds them`,
    ).toEqual([]);
  });
});

/**
 * **`wrapLines` REWRITES `tune.lines`, AND NO SVG GATE CAN SEE THAT.**
 * `tune.lines = addLineBreaks(lines, linesBreakElements, barNumbers)`
 * (`parse/wrap_lines.js:13`) — a host that asked for a wrap and then reads `tune.lines`
 * gets the RE-LINED structure. Measured against abcjs: an eight-bar tune under
 * `{wrap, staffwidth: 400}` DRAWS three lines in both engines while `tune.lines` reported
 * three in abcjs and ONE here. The drawing was already right, which is why every byte and
 * pixel gate was quiet, and `tune.lines`'s own corpus is at 100% because nothing in it
 * wraps.
 *
 * The invariant asserted here is abcjs's own: every `line` a `lineBreaks` row names is a
 * staff line of `tune.lines`.
 */
describe("renderAbc({wrap}) — tune.lines is the RE-LINED structure", () => {
  // ⚠️ **NOT `"*"`** — that is a HEADLESS slot and abcjs's guard is
  // `if (!removeDiv && params.wrap && params.staffwidth)` (`api/abc_tunebook_svg.js:119`),
  // so a wrap does NOTHING there and the row list comes back empty. A stub target with an
  // `innerHTML` is what the rest of this file uses, for the same reason.
  const wrapped = (abc: string) =>
    renderAbc({ innerHTML: "" }, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    })[0];

  it("reports one staff line per line the wrap decided", () => {
    const tune = wrapped("X:1\nL:1/4\nK:C\nCDEF|GABc|cdef|gabc'|CDEF|GABc|cdef|gabc'|\n");
    const breaks = tune?.lineBreaks ?? [];
    expect(breaks.length).toBeGreaterThan(1);
    const targets = new Set(breaks.map((b) => b.line));
    const staffLines = (tune?.lines ?? []).filter(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    );
    expect(staffLines.length).toBe(targets.size);
  });

  it("leaves an unwrapped tune's lines exactly as they were", () => {
    // The negative control: `drawnScore()` IS the parsed score when no wrap applies, so
    // this path must be untouched — which is what makes the change above safe.
    const tune = wrapped("X:1\nL:1/4\nK:C\nCDEF|\n");
    const staffLines = (tune?.lines ?? []).filter(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    );
    expect(staffLines.length).toBe(1);
  });
});

/**
 * **A BREAK INDEXES BAR ELEMENTS, NOT MEASURES.**
 *
 * `getMeasureWidths` reports one width per BAR ELEMENT (`engraver-controller.js:167-180`)
 * and `findLineBreaks` counts the same elements (`wrap_lines.js:132-141`), so a measure
 * that OPENS with a barline — a leading `|:`, an ending's invisible bar — contributes TWO
 * where an ordinary measure contributes one. Translating a break index straight onto a
 * measure index under-split every such tune.
 *
 * ⚠️ **AND WHICH MEASURE A BREAK OPENS DEPENDS ON WHICH OF THE TWO IT LANDS ON**: a break
 * at a CLOSING bar opens the next measure, one at an OPENING bar opens that measure.
 *
 * Measured against abcjs on the corpus: eleven fixtures drew a different NUMBER OF LINES
 * and now none does. `tune.lineBreaks` was byte-identical to abcjs's throughout — the
 * wrap's DECISION was never the defect, only this translation back onto the score.
 */
describe("renderAbc({wrap}) — a break is a BAR index, not a measure index", () => {
  /**
   * ⚠️ **COUNT `tune.lines`, NOT `tune.lineBreaks`.** The breaks are the wrap's DECISION,
   * built from the score as PARSED, and they were identical to abcjs's throughout — a
   * count of them passes with the defect in place and proves nothing. `tune.lines` is the
   * RE-LINED structure `applyLineBreaks` produced, which is what this is about. Caught by
   * restoring the old mapping and watching the first form stay green.
   */
  const linesOf = (abc: string): number => {
    const tune = renderAbc({ innerHTML: "" }, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    })[0];
    return (tune?.lines ?? []).filter(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    ).length;
  };

  it("splits a tune that OPENS with a repeat barline", () => {
    // `|:CDEF|1GABc:|3cdef|]` — three measures, FOUR bar elements, and abcjs answers
    // `lineBreaks: [[2]]`. Read as a measure index that found nothing and drew one line.
    expect(linesOf("X:2\nL:1/4\nK:C\n|:CDEF|1GABc:|3cdef|]\n")).toBe(2);
  });

  it("leaves a tune with no opening barlines exactly where it was", () => {
    // The negative control: eight ordinary measures, eight bar elements, no offset to get
    // wrong — this is the shape that passed before the fix and must still.
    expect(linesOf("X:1\nL:1/4\nK:C\nCDEF|GABc|cdef|gabc'|CDEF|GABc|cdef|gabc'|\n")).toBe(3);
  });
});

/**
 * **A WRAP DROPS THE METER FROM THE WHOLE TUNE WHEN A NON-MUSIC ROW COMES FIRST.**
 *
 *     if (keys[k] === "meter" && action.line !== 0) skip = true;      // wrap_lines.js:43
 *
 * ⚠️ **`action.line` IS THE OUTPUT LINE INDEX OVER THE WHOLE TUNE AND IT COUNTS THE
 * NON-MUSIC ROWS.** `findLineBreaks` advances one `outputLine` for a subtitle, a `%%text`,
 * a `%%sep` or a `%%newpage` exactly as it does for a staff line (`wrap_lines.js:150-153`),
 * so a tune opening with a subtitle has its music on line 1 and loses the meter on EVERY
 * system — the first included. The option's name reads as though only the REPRINTS go.
 *
 * Measured over the corpus under `{wrap, staffwidth: 400}`: 41 of 685 fixtures put the
 * music off line 0, and abcjs's `staff.meter` is absent on all 41. `zzopts`'s
 * `wrap + staffwidth` row 59 -> 53.
 */
describe("renderAbc({wrap}) — the meter goes with a non-music first row", () => {
  const meterOnFirstStaff = (abc: string): string => {
    const tune = renderAbc({ innerHTML: "" }, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    })[0];
    const line = (tune?.lines ?? []).find(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    ) as { staff: { meter?: { type?: string } }[] } | undefined;
    return line?.staff[0]?.meter?.type ?? "NONE";
  };

  it("drops it when a SUBTITLE takes output line 0", () => {
    expect(meterOnFirstStaff("X:1\nT:T\nT:Sub\nM:4/4\nL:1/4\nA4|\nB4|\n")).toBe("NONE");
  });

  it("drops it when a %%text takes output line 0", () => {
    expect(meterOnFirstStaff("X:1\nT:T\nM:4/4\nL:1/4\n%%text hi\nA4|\nB4|\n")).toBe("NONE");
  });

  it("drops it when a %%newpage takes output line 0", () => {
    // ⚠️ `Score.newPage` is a NUMBER here, not a flag — `%%newpage 1` reads back as `1`,
    // and a `=== true` test misses this fixture alone out of the corpus's 41.
    expect(meterOnFirstStaff("X:1\nT:T\n%%newpage 1\nM:4/4\nL:1/4\nA4|\nB4|\n")).toBe("NONE");
  });

  it("KEEPS it when the music really is output line 0", () => {
    // The negative control, and the half that was already right: with nothing before the
    // music abcjs's `action.line` IS 0 and the meter survives. A test that only asserted
    // "NONE" would pass with the meter deleted outright.
    expect(meterOnFirstStaff("X:1\nT:T\nM:4/4\nL:1/4\nA4|\nB4|\n")).toBe("specified");
  });

  it("KEEPS it with a subtitle when NO wrap runs", () => {
    // The second control: the suppression belongs to `wrapLines` and nothing else. abcjs
    // never calls it without `wrap`, and `svg-bytes` stays 0 of 691 because of this row.
    const tune = renderAbc({ innerHTML: "" }, "X:1\nT:T\nT:Sub\nM:4/4\nL:1/4\nA4|\nB4|\n", {
      staffwidth: 400,
    })[0];
    const line = (tune?.lines ?? []).find(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    ) as { staff: { meter?: { type?: string } }[] } | undefined;
    expect(line?.staff[0]?.meter?.type ?? "NONE").toBe("specified");
  });
});

/**
 * **AN ENDING DECLARED ON THE BARLINE THAT *ENDS* A SYSTEM OPENS ON THAT SYSTEM.**
 *
 * abcjs opens the `EndingElem` where it processes the BAR: `elem.startEnding` is read in
 * `createABCBar` and `voice.addOther(this.partstartelem)` puts it on the voice of the line
 * being built (`abstract-engraver.js:1034-1042`). A break at that bar leaves it the LAST
 * element of the line it CLOSES — `findLineBreaks` pushes `{start, end: e}` with `e` the
 * bar itself (`wrap_lines.js:132-141`) — so the ending opens there, as a hook at the
 * line's right edge WITH its number, and the next line gets a fresh
 * `EndingElem("", null, null)` from `createABCVoice`'s `if (this.partstartelem)`
 * (`:230-233`): no hook, no number.
 *
 * Ours drew ONE bracket, numbered, on the wrong system. `zzopts`'s `wrap + staffwidth`
 * row 53 -> 48.
 */
describe("renderAbc({wrap}) — an ending opens on the system holding its barline", () => {
  /** Every drawn ending bracket, as `x-of-first-hook/label`, in document order. */
  const endingsOf = (abc: string): string[] => {
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(host, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    });
    return [...host.innerHTML.matchAll(/<g[^>]*data-name="ending"[^>]*>(.*?)<\/g>/g)].map(
      (m) => {
        const x = /M ([0-9.]+) /.exec(m[1] ?? "")?.[1] ?? "?";
        const label = /<tspan[^>]*>([^<]*)<\/tspan>/.exec(m[1] ?? "")?.[1] ?? "";
        return `${x}/${label}`;
      },
    );
  };

  // `|:CDEF|1GABc:|3cdef|]` — three measures, FOUR bar elements, `lineBreaks: [[2]]`, and
  // the break lands on the `:|` that DECLARES the `3`. abcjs draws THREE brackets: the
  // `1` closing at the line end, the `3` opening AT it, and its bare continuation.
  it("opens the 3 at the line's right edge and continues it unnumbered", () => {
    expect(endingsOf("X:2\nT:E\nL:1/4\nK:C\n|:CDEF|1GABc:|3cdef|]\n")).toEqual([
      "226.78/1",
      "415/3",
      "222.76/",
    ]);
  });

  it("leaves an ending that fits on one system exactly where it was", () => {
    // The negative control: no break falls on the `:|`, so nothing is carried and both
    // brackets are ordinary numbered ones. This is the shape that passed before the fix.
    // Both numbers read off abcjs, not off our own output.
    expect(endingsOf("X:2\nT:E\nL:1/4\nK:C\n|:CD|1GA:|2ce|]\n")).toEqual([
      "165.9/1",
      "293.26/2",
    ]);
  });
});

/**
 * **A DISSOLVED LINE BREAK RE-EMITS THE LINE'S STAFF KEY / METER / CLEF.**
 *
 * `deline` runs BEFORE `findLineBreaks`, and merging a line turns that line's STAFF
 * property into a voice element it `unshift`s onto the front of the voice with
 * `startChar: -1` (`data/deline-tune.js:23-39`, `addKeyToVoices` and its two siblings at
 * `:126-151`). The wrap then dissolves the source break and BOTH survive: the previous
 * line's WARNING, which carries the source range, and this injected copy, which carries
 * none. abcjs's shape is `keySignature@26 keySignature@-1`.
 *
 * ⚠️ **THE GUARD IS `objEqual` AGAINST THE PREVIOUS LINE'S HEAD, NOT "THIS MEASURE HAS A
 * CHANGE"** — and the two rungs that settle it fall opposite ways. `zzopts`'s
 * `wrap + staffwidth` row 48 -> 42.
 */
describe("renderAbc({wrap}) — a dissolved break re-emits the staff property", () => {
  /** The line's voice as `el_type@startChar`, which is where `-1` is the whole point. */
  const voiceOf = (abc: string): string => {
    const tune = renderAbc({ innerHTML: "" }, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    })[0];
    const line = (tune?.lines ?? []).find(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    ) as { staff: { voices: { el_type: string; startChar?: number }[][] }[] } | undefined;
    return (line?.staff[0]?.voices[0] ?? [])
      .map((e) => (/key|meter|clef|Sign/i.test(e.el_type) ? `${e.el_type}@${e.startChar}` : e.el_type))
      .join(" ");
  };

  it("re-emits a KEY, after the warning that carries the range", () => {
    expect(voiceOf("X:1\nL:1/4\nM:4/4\nK:C\nCDEF|\nK:G\nGAB^c|\n")).toBe(
      "note note note note bar keySignature@26 keySignature@-1 note note note note bar",
    );
  });

  it("re-emits a METER, and there is no meter warning to precede it", () => {
    expect(voiceOf("X:1\nL:1/4\nM:4/4\nK:C\nCDEF|\nM:3/4\nGAB|\n")).toBe(
      "note note note note bar timeSignature@-1 note note note bar",
    );
  });

  it("re-emits a CLEF, after both warnings", () => {
    expect(voiceOf("X:1\nL:1/4\nM:4/4\nK:C\nCDEF|\nK:C clef=bass\nGABc|\n")).toBe(
      "note note note note bar clef@26 keySignature@26 clef@-1 note note note note bar",
    );
  });

  it("re-emits after an INLINE [K:] on the line before, which changes no measure", () => {
    // ⚠️ The case that disproves "this measure has a change": the second line carries no
    // `K:` at all. `currentKey` tracks the STAFF key alone, so an inline `[K:]` never
    // advances it and the following line's head differs from it.
    expect(voiceOf("X:1\nL:1/4\nM:4/4\nK:C\nCD[K:G]EF|\nGABc|\n")).toBe(
      "note note keySignature@22 note note bar keySignature@-1 note note note note bar",
    );
  });

  it("re-emits NOTHING for a RESTATED key", () => {
    // The control, and it is the other half of `objEqual`: a `K:C` under `K:C` is a change
    // this measure carries and abcjs injects nothing for. A rule keyed on "has a change"
    // passes every row above and fails this one.
    expect(voiceOf("X:1\nL:1/4\nM:4/4\nK:C\nCDEF|\nK:C\nGABc|\n")).toBe(
      "note note note note bar keySignature@26 note note note note bar",
    );
  });

  it("re-emits NOTHING for a RESTATED meter", () => {
    expect(voiceOf("X:1\nL:1/4\nM:4/4\nK:C\nCDEF|\nM:4/4\nGABc|\n")).toBe(
      "note note note note bar note note note note bar",
    );
  });
});

/**
 * **THE TUNE'S TEMPO MARK IS NOT PART OF THE METER RULE.**
 *
 * `prefix`'s `withMeter` flag hangs THREE things off "this is the first system": the
 * clef/key prefix, the header meter, and the tune's TEMPO MARK
 * (`createABCLine(staff, !hasPrintedTempo ? abcTune.metaText.tempo : null, i)`,
 * `engraver-controller.js:232`). Narrowing that flag for `Score.wrapDroppedMeter` silently
 * took the tempo off every wrapped tune with a subtitle.
 *
 * ⚠️ **NO GATE CAUGHT IT.** The six fixtures that show it were already differing on other
 * causes, so `zzopts`'s count never moved, and no golden renders `{wrap}` at all. A rung
 * caught it — the same shape as the `strict` flag that gated two unrelated behaviours.
 * The meter is narrowed at its own use site now, and this is the row that says so.
 */
describe("renderAbc({wrap}) — the meter rule does not take the tempo with it", () => {
  const tempoMarks = (abc: string, wrap: boolean): number => {
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(host, abc, {
      staffwidth: 400,
      ...(wrap
        ? { wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 } }
        : {}),
    });
    return [...host.innerHTML.matchAll(/data-name="tempo"/g)].length;
  };
  const WITH_SUB = "X:1\nT:T\nT:Sub\nQ:1/4=120\nM:4/4\nL:1/4\nK:C\nCDEF|GABc|cdef|gabc|CDEF|\n";
  const PLAIN = "X:1\nT:T\nQ:1/4=120\nM:4/4\nL:1/4\nK:C\nCDEF|GABc|cdef|gabc|CDEF|\n";

  // The row that was broken: a subtitle puts the music off output line 0, which is exactly
  // when `wrapDroppedMeter` fires — and the tempo must survive it.
  it("draws the tempo under {wrap} WITH a subtitle", () => {
    expect(tempoMarks(WITH_SUB, true)).toBe(1);
  });
  // The three controls, each of which stayed green while the row above was broken, which
  // is what says the defect was the FLAG rather than the tempo.
  it("draws it under {wrap} without a subtitle", () => {
    expect(tempoMarks(PLAIN, true)).toBe(1);
  });
  it("draws it with a subtitle and no wrap", () => {
    expect(tempoMarks(WITH_SUB, false)).toBe(1);
  });
  it("draws it with neither", () => {
    expect(tempoMarks(PLAIN, false)).toBe(1);
  });
});

/**
 * **A WRAP RENUMBERS EVERY BAR FROM 1, LOSING BOTH `%%setbarnb` AND THE FREQUENCY.**
 *
 *     if (barNumbers !== undefined && action.staff === 0 && action.line > 0)
 *       outputLines[action.line].staff[action.staff].barNumber = currentBarNumber;
 *     …
 *     if (barNumbers !== undefined && action.staff === 0 && action.voice === 0)
 *       for (kk = 0; kk < currVoice.length; kk++)
 *         if (currVoice[kk].el_type === 'bar') {
 *           currentBarNumber++
 *           if (kk === currVoice.length-1) delete currVoice[kk].barNumber
 *           else currVoice[kk].barNumber = currentBarNumber
 *         }
 *
 * (`wrap_lines.js:37-39`, `:78-88`.) `currentBarNumber` opens at 1 and counts BAR
 * ELEMENTS, and the assignment is unconditional — no `% barNumbers` test survives it.
 *
 * ⚠️ **AND THE GATE IS THAT THE DIRECTIVE APPEARED, NOT THAT IT DREW ANYTHING** — see
 * `Score.barNumbersDirective`. `zzopts`'s `wrap + staffwidth` row 41 -> 34.
 */
describe("renderAbc({wrap}) — bar numbers are renumbered from 1", () => {
  const MUSIC = "CDEF|GABc|cdef|gabc|CDEF|GABc|cdef|gabc|\n";
  const nums = (head: string, wrap = true): string => {
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(host, `X:1\nT:T\n${head}M:4/4\nL:1/4\nK:C\n${MUSIC}`, {
      staffwidth: 400,
      ...(wrap
        ? { wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 } }
        : {}),
    });
    return [...host.innerHTML.matchAll(/data-name="bar-number"[^>]*>(?:<tspan[^>]*>)?([^<]*)/g)]
      .map((m) => m[1])
      .join(" ");
  };

  // ⭐ The headline: `%%barnumbers 5` draws every FIFTH bar and `%%setbarnb 24` starts the
  // count at 24, so unwrapped this tune is `25 30`. A wrap throws both away.
  it("discards %%setbarnb AND the frequency", () => {
    expect(nums("%%barnumbers 5\n%%setbarnb 24\n", false)).toBe("25 30");
    expect(nums("%%barnumbers 5\n%%setbarnb 24\n")).toBe("2 3 4 5 6 7 8");
  });

  // `%%barnumbers 50` fires on no bar of an eight-bar tune, and `%%barnumbers 0` numbers
  // the CLEF rather than a barline — both draw nothing unwrapped and every bar wrapped,
  // which is why "some measure carries a number" is not a usable proxy for the directive.
  it("renumbers even when the directive itself would draw nothing", () => {
    expect(nums("%%barnumbers 50\n", false)).toBe("");
    expect(nums("%%barnumbers 50\n")).toBe("2 3 4 5 6 7 8");
  });

  // The head number is `action.line > 0` — the output line index that counts the non-music
  // rows — so a subtitle, which puts the music on line 1, earns the first system one.
  it("numbers the FIRST system's head when a subtitle precedes the music", () => {
    expect(nums("T:Sub\n%%barnumbers 1\n")).toBe("1 2 3 4 5 6 7 8");
  });

  it("does NOT number it when the music really is on output line 0", () => {
    // The control for the row above, and it is the same output-line index the meter rule
    // turns on — the first system's head number and the header meter come and go together.
    expect(nums("%%barnumbers 1\n")).toBe("2 3 4 5 6 7 8");
  });

  it("renumbers NOTHING when the directive never appeared", () => {
    // The control for the whole rule: no `%%barnumbers` is `barNumbers === undefined`, and
    // abcjs's two blocks are both skipped. A rule that renumbered unconditionally would
    // put a number on every bar of every wrapped tune in the corpus.
    expect(nums("")).toBe("");
  });
});

/**
 * **AN ENDING DRAWS ONE SEGMENT PER SYSTEM IT CROSSES, NOT TWO IN TOTAL.**
 *
 * abcjs re-creates a fresh `EndingElem("", null, null)` at the head of EVERY line on which
 * `partstartelem` is still open (`createABCVoice`, `abstract-engraver.js:230-233`), so a
 * bracket stretched over four systems is drawn in four pieces plus its numbered head.
 *
 * ⚠️ **OURS SPENT THE CARRY ON THE FIRST CONTINUATION.** `closeVolta` nulled `voltaCarried`
 * on every continued close — and the end-of-system close is one, running right after the
 * carry has been set — so the bracket stopped after two systems however far it ran.
 * `hooked` is exactly "the ending really ends here", and is what spends it now.
 *
 * Measured under `{wrap, staffwidth: 400}`: abcjs's continuations sit at y163, y256, y348
 * and y440 as the span grows, and ours drew only the first.
 */
describe("renderAbc({wrap}) — an ending carries across every system it crosses", () => {
  const B = "CDEF|";
  const segments = (bars: number): number => {
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(
      host,
      `X:1\nT:E\nL:1/4\nM:4/4\nK:C\n${B}${B}|1 ${B.repeat(bars)}:|2 ${B}|]\n`,
      {
        staffwidth: 400,
        wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
      },
    );
    return [...host.innerHTML.matchAll(/data-name="ending"/g)].length;
  };

  // One system: the `1`, the `2`'s carried opening, and the `2` itself. Unchanged by the
  // fix — the control, and the shape that passed while the rows below were broken.
  it("draws three brackets when nothing spans a break", () => {
    expect(segments(1)).toBe(3);
  });
  // Two systems: one continuation. ⚠️ The comment first written here said this row passed
  // with the defect "because the first carry always worked". Restoring the defect reddens
  // it too — 3 against 4 — so the carry was already being spent one segment early, not
  // merely failing to repeat. Corrected from the break rather than left as reasoned.
  it("draws four when the ending spans two systems", () => {
    expect(segments(4)).toBe(4);
  });
  // ⭐ Three systems: TWO continuations, and this is the row that was red. Every count here
  // was read off abcjs, not off our own output.
  it("draws five when it spans three", () => {
    expect(segments(8)).toBe(5);
  });
});

/**
 * **A WRAPPED SYSTEM'S HEAD KEY IS THE ONE abcjs CARRIED, NOT THE ONE IN FORCE.**
 *
 *     if (lastKeySig[action.staff])
 *       outputLines[action.line].staff[action.staff].key = lastKeySig[action.staff];
 *     …
 *     lastKeySig[action.staff] = { root, acc, mode,
 *       accidentals: accidentals.filter(a => a.acc !== 'natural') }
 *
 * (`wrap_lines.js:49-50`, `:60-70`.) Two consequences, and each has its own row: an inline
 * `[K:]` the wrap lands at a line head is NOT that line's key — the head prints what was in
 * force and the change draws in the STREAM after it — and a carried head key prints NO
 * cancelling naturals, because the filter removed them.
 *
 * `zzopts`'s `wrap + staffwidth` row 34 -> 32. It also closes the last live hypothesis on
 * that row: `synth-flattener-17`'s accidentals were predicted to be the delined-key defect
 * and did not close with it, which was right — this is a different rule.
 */
describe("renderAbc({wrap}) — a wrapped head key is carried, not in force", () => {
  const accidentals = (abc: string, wrap = true): string => {
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(host, abc, {
      staffwidth: 400,
      ...(wrap
        ? { wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 } }
        : {}),
    });
    return [...host.innerHTML.matchAll(/data-name="accidentals\.([a-z]+)"/g)]
      .map((m) => m[1])
      .join(" ");
  };
  const HEAD = "X:1\nT:T\nL:1/4\nM:4/4\nK:A\nabca|abca|abca|abca|[K:Bb]abca|abca|\n";
  const MID = "X:1\nT:T\nL:1/4\nM:4/4\nK:A\nabca|abca|abca|ab[K:Bb]ca|abca|abca|\n";

  // ⭐ The head prints A's three sharps and the `[K:Bb]` draws AFTER it, on the same system.
  // Ours made the Bb the head key and printed no sharps at all.
  it("prints the carried key at the head and the inline change after it", () => {
    expect(accidentals(HEAD)).toBe(
      "sharp sharp sharp sharp sharp sharp sharp sharp sharp nat nat nat flat flat",
    );
  });

  // ⭐ A carried head key has its naturals FILTERED, so the third system shows two flats
  // and nothing else. Ours drew two flats and three naturals.
  it("prints a carried head key with no cancelling naturals", () => {
    expect(accidentals(MID)).toBe(
      "sharp sharp sharp sharp sharp sharp nat nat nat flat flat flat flat",
    );
  });

  // The control: both rules belong to the WRAP. `lastKeySig` exists only inside
  // `wrapLines`, and abcjs never calls it otherwise — which is why `svg-bytes` is
  // untouched by either row above. Read off abcjs, not off our own output.
  it("leaves an unwrapped tune's keys exactly as they were", () => {
    expect(accidentals(HEAD, false)).toBe("sharp sharp sharp nat nat nat flat flat");
  });
});

/**
 * **A WRAPPED SYSTEM'S HEAD NUMBER COMES FROM THE DELINED LINE, NOT THE SOURCE LINE.**
 *
 * `addLineBreaks` runs over `tune.deline({lineBreaks: false})`, so its `ogLine` is a
 * DELINED line: contiguous music merges into one and only a non-music row starts another.
 * Its keys-copy loop then overwrites the wrap's running counter with that line's own
 * `barNumber` — the parser's, moved there by `tune-builder.js:139-144` when a line ends on
 * a numbered barline — for every output line cut from it.
 *
 * ⚠️ **THE SOURCE-LINE READING OF THIS IS WRONG, AND WAS MEASURED WRONG.** Instrumented on
 * both sides: `piano-300`'s source lines each carry a head (4, 6, 8, 10, 12) and its
 * wrapped heads still follow the COUNTER, because deline merges them into one line whose
 * `barNumber` is the first line's — absent. A `%%text` blocks that merge, and then the
 * head does carry. The two rows below are exactly that pair.
 */
describe("renderAbc({wrap}) — the head number is the DELINED line's", () => {
  const heads = (abc: string, staffwidth = 400): string => {
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(host, abc, {
      staffwidth,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    });
    return [...host.innerHTML.matchAll(/data-name="bar-number"[^>]*>(?:<tspan[^>]*>)?([^<]*)/g)]
      .map((m) => m[1])
      .join(" ");
  };

  // Contiguous music: deline merges it, the merged line carries no number, and the heads
  // are the wrap's own counter.
  // ⚠️ This short case is NOT what catches the source-line reading — restoring that port
  // leaves this row green and reddens the `piano-300` RATCHET above instead, which is
  // longer and has five systems cut from one delined line. Said here because a reader
  // would otherwise take this row for the guard against it.
  it("uses the counter when the music is contiguous", () => {
    const abc =
      "X:1\nT:t\nM:4/4\nL:1/16\n%%staves {(RH) (LH)}\n%%barnumbers -1\n" +
      "V:RH clef=treble\nV:LH clef=bass\nK:C\n" +
      "[V: RH]c4 f4 e8| fede g8 e4|g16|\n[V: LH] E,12 F,4| z4 G,F,A,G, z4 G,F,A,G, | G,16| \n";
    expect(heads(abc, 300)).toBe("2 3");
  });

  // ⭐ A `%%text` between the music blocks the merge, so the second delined line keeps the
  // number the parser hung on it and BOTH output lines cut from it repeat it.
  it("uses the delined line's own number when a %%text splits the music", () => {
    const abc =
      "X:1\nT:t\n%%measurenb 1\nM:4/4\nL:1/4\nK:C\n" +
      "abca|abca|\n%%text between\nabca|abca|abca|abca|\n";
    // ⭐ The repeated `3` is the point — it is the delined line's own head, taken by the
    // keys-copy loop, where the counter would have said 5. Read off abcjs.
    expect(heads(abc)).toBe("2 3 4 3 6");
  });
});

/**
 * **A WRAP-BROKEN OPENING BARLINE BELONGS TO THE SYSTEM BEFORE IT, AND SO DOES THE ENDING
 * IT DECLARES.**
 *
 * `findLineBreaks` pushes `{start, end: e}` with `e` the BAR ITSELF, so a break-bar is the
 * last element of the line it CLOSES (`wrap_lines.js:132-141`) — and an opening `|:`,
 * `[|]` or `[1` is a bar element like any other. Measured through `tune.lines`: abcjs's
 * line ends `… bar(bar_thin) bar(bar_invisible:E1)` where ours OPENED the next line with
 * that invisible bar.
 *
 * ⚠️ **AND IT IS A WRAP RULE ONLY.** Without a wrap abcjs's lines ARE the source lines, so
 * an `[1` opening one genuinely belongs to it. An earlier attempt anchored these endings at
 * the system's right edge for EVERY system break and reddened eight suites; reading the
 * TRAILING BAR is what keeps it to the wrap, because nothing else produces one.
 *
 * `layout-09-endings` 136 -> 138 elements against abcjs's 138, `tablature-20` 128 -> 130,
 * and `tablature-17` loses its four missing brackets.
 */
describe("renderAbc({wrap}) — a wrap-broken opening bar trails, with its ending", () => {
  /** Each bracket as `y/label` — the x is left out on purpose, see the note below. */
  const brackets = (abc: string): string[] => {
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(host, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    });
    return [...host.innerHTML.matchAll(/<g[^>]*data-name="ending"[^>]*>(.*?)<\/g>/g)].map(
      (m) => {
        const y = /M [0-9.]+ ([0-9.]+)/.exec(m[1] ?? "")?.[1] ?? "?";
        const label = /<tspan[^>]*>([^<]*)<\/tspan>/.exec(m[1] ?? "")?.[1] ?? "";
        return `${y}/${label}`;
      },
    );
  };

  // ⭐ FOUR brackets, and the numbered `1` is on the FIRST system (y 138.71) where ours
  // used to open it on the second. The systems and labels are read off abcjs.
  //
  // ⚠️ The x is deliberately not asserted: ours is 416 where abcjs is 415, and the middle
  // continuation closes at 382.5 against 395. Those two offsets are a KNOWN residual — the
  // structure is what this rule is about, and asserting an x we do not yet match would
  // make this row a snapshot of our own output instead of a statement about abcjs.
  it("opens the ending on the system that holds its barline", () => {
    expect(
      brackets("X:3\nT:E\nL:1/4\nM:4/4\nK:C\nCDEF|GABc|cdef|gabc|\n[|]1 CDEF:|\n[|]2 GABc|]\n"),
    ).toEqual(["138.71/1", "232.28/", "232.28/2", "324.61/"]);
  });

  // The control: an ending whose bar is NOT a break-bar is untouched, which is the shape
  // every unwrapped tune has and the reason `svg-bytes` stays at 0 of 691.
  it("leaves an ending inside a system exactly where it was", () => {
    expect(brackets("X:2\nT:E\nL:1/4\nK:C\n|:CD|1GA:|2ce|]\n")).toEqual([
      "70.87/1",
      "70.87/2",
    ]);
  });
});

/**
 * **A WRAP LOSES A MUSIC LINE'S OWN `%%vskip`.**
 *
 * `addLineBreaks` builds a FRESH line — `outputLines[action.line] = {staff: []}`
 * (`wrap_lines.js:33-35`) — and then copies only the STAFF's keys onto it. `vskip` is a
 * property of the LINE, so nothing carries it across. A NON-music line keeps its own,
 * because that arm assigns the original object whole (`:89`).
 *
 * Measured: `%%text before` / `%%vskip 20` / `CDEF|` puts abcjs's staff 20px HIGHER than
 * ours under wrap and the two agree once it is dropped. `zzopts`'s `wrap + staffwidth` row
 * 31 -> 28, which is this fixture, its sibling, and `abcts-vskip-tune1` at 25.
 */
describe("renderAbc({wrap}) — a music line's %%vskip does not survive", () => {
  const staffTop = (abc: string, wrap: boolean): string => {
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(host, abc, {
      staffwidth: 400,
      ...(wrap
        ? { wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 } }
        : {}),
    });
    // The class comes AFTER `d` in the emitted markup, so match the path whole.
    return /<path d="M [0-9.]+ ([0-9.]+)[^>]*class="abcjs-top-line"/.exec(host.innerHTML)?.[1] ?? "?";
  };
  const WITH = "X:9\nT:Text Then Vskip\nL:1/4\nK:C\n%%text before\n%%vskip 20\nCDEF|\n";
  const WITHOUT = "X:9\nT:Text Then Vskip\nL:1/4\nK:C\n%%text before\nCDEF|\n";

  // ⭐ Under wrap the `%%vskip 20` is gone, so the staff sits where it would with no
  // directive at all. Both numbers read off abcjs.
  it("drops it, putting the staff where a tune with no vskip has it", () => {
    expect(staffTop(WITH, true)).toBe(staffTop(WITHOUT, true));
  });

  // The control: WITHOUT a wrap the vskip is spent, and the two tunes differ by exactly
  // the 20 it asks for. A rule that dropped it unconditionally would pass the row above
  // and fail this one.
  it("spends it when no wrap runs", () => {
    expect(Number(staffTop(WITH, false)) - Number(staffTop(WITHOUT, false))).toBe(20);
  });
});

/**
 * **A CARRIED ENDING IS ADDED AT THE HEAD OF ITS LINE'S VOICE, SO IT DRAWS FIRST.**
 *
 * `createABCVoice` makes the continuation before it walks a single element —
 * `if (this.partstartelem) { this.partstartelem = new EndingElem("", null, null);
 * voice.addOther(…) }` (`abstract-engraver.js:230-233`) — so it precedes every note on
 * that line and therefore every note's decoration.
 *
 * ⚠️ **OURS KEYED IT ON `lines[0].x1`, WHICH IS ITS CLOSING HOOK.** The OPENING hook is
 * skipped for a `continued` bracket, so the first line pushed is the right-hand one, and
 * the bracket sorted after everything. The numbered bracket a few lines above already used
 * the MIN of its lines; this is the same key.
 *
 * Measured on `visual-selection-01`: four elements of 690, same coordinates, pure order —
 * abcjs writes the ending and THEN the dynamics at 113.82. `zzopts` 28 -> 26.
 *
 * ⚠️ The fixture is used rather than a made-up tune because two synthetic shapes did NOT
 * reproduce it, with the defect deliberately restored. Asserting one of those would have
 * been a row that passes either way.
 */
describe("renderAbc({wrap}) — a carried ending draws before the line's decorations", () => {
  it("puts the ending group ahead of the dynamics on the line it resumes", () => {
    const abc = readFileSync(
      join(
        import.meta.dirname,
        "corpus-abcjs",
        "fixtures",
        "abcjs-visual-selection-01-selection-test.abc",
      ),
      "utf-8",
    );
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(host, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    });
    // The run of interest: the LAST ending group and the dynamics beside it.
    const order = [...host.innerHTML.matchAll(/data-name="(ending|dynamics)"/g)].map(
      (m) => m[1],
    );
    const lastEnding = order.lastIndexOf("ending");
    const lastDynamics = order.lastIndexOf("dynamics");
    expect(lastDynamics).toBeGreaterThan(-1);
    expect(lastEnding).toBeLessThan(lastDynamics);
  });
});

/**
 * **A WRAP CARRIES A VOICE'S STEM DIRECTION FORWARD, SO A VOICE WHOSE COMPANION HAS RUN OUT
 * KEEPS ITS FORCED `up`.**
 *
 *     if (lastStem[action.staff*10+action.voice])
 *       …voices[action.voice].unshift({el_type: "stem", direction: lastStem[…].direction})
 *     …
 *     for (kk = currVoice.length-1; kk >= 0; kk--)
 *       if (currVoice[kk].el_type === "stem") lastStem[…] = { direction: … }
 *
 * (`wrap_lines.js:59-60`, `:73-80`) — the same shape as `lastKeySig`, re-asserting the
 * direction at the head of EVERY later output line.
 *
 * ⭐ **THE STEMS WERE NOT THE DISCRIMINATOR THEY LOOKED LIKE.** What this MOVES is a TUPLET
 * NUMBER: the beam's own `stemsUp` is what `isAbove` reads (`layout/triplet.js:84-86`), and
 * an above-tuplet reserves a lane worth 20.36px of page. Every sampled stem pointed up in
 * both engines while the tuplet sat on opposite sides.
 *
 * `visual-mouse-click-01` and `visual-tablature-15` went from 108 of 265 elements moved to
 * 1 — found by differencing x/y POSITIONS, which the element-kind sweep cannot see.
 */
describe("renderAbc({wrap}) — a voice keeps its forced stem after its companion ends", () => {
  const M = "CDEF|";
  const T = "b^f_df (3B2d2c2 B4|";
  const tupletVsStaff = (secondVoice: string): string => {
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(
      host,
      `X:1\nT:t\nM:4/4\nL:1/16\n%%staves (V1 V2)\nV:V1\nV:V2\nK:C\n` +
        `[V:V1]${M.repeat(5)}${T}${M.repeat(2)}\n[V:V2]${secondVoice}\n`,
      {
        staffwidth: 400,
        wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
      },
    );
    const y = /data-name="triplet"[^>]*>[\s\S]*?<text[^>]*y="([0-9.]+)"/.exec(host.innerHTML)?.[1];
    const tops = [...host.innerHTML.matchAll(/<path d="M [0-9.]+ ([0-9.]+)[^>]*class="abcjs-top-line"/g)].map((m) => m[1]);
    // ABOVE or BELOW its own staff is the whole question — the absolute y moves with it.
    return Number(y) < Number(tops[tops.length - 1]) ? "above" : "below";
  };

  // ⭐ V2 runs out after two measures; the tuplet is V1's sixth. abcjs keeps V1's forced
  // `up`, so the beam is above and the number rides it. Ours dropped the force and the
  // number went below, taking 20.36px of page with it.
  it("keeps the tuplet above when the second voice has ended", () => {
    expect(tupletVsStaff("C16|C16|")).toBe("above");
  });

  // The control: with the second voice present throughout, the force was never in doubt
  // and this row passed before the fix.
  it("keeps it above when the second voice runs the whole tune", () => {
    expect(tupletVsStaff("C16|".repeat(8))).toBe("above");
  });
});
