import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";

/**
 * **`renderAbc(…, {wrap})` — THE TWO THINGS IT HANDS BACK.**
 *
 * `tune.explanation` is the wrap search's own reasoning, one row per ORIGINAL line: the
 * measured `widths` (the prefix `left`, every `measureWidths`, and their `total`), the
 * `lineBreakPoint` it aimed at, the `minLineSize` it would not go under, the `staffWidth`
 * it was given and the `minWidth` it settled on. `tune.lineBreaks` is the ANSWER — one row
 * per drawn line, saying which original line it came from (`ogLine`) and which slice of
 * that voice it holds (`start`, `end`).
 *
 * ── THE ORACLE ──────────────────────────────────────────────────────────────
 * `tests/corpus-wrap/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-wrap.ts`) over its OWN wrap inputs — the six `var abc…`
 * declarations in `tests/visual/wrap.test.js`, pulled out by evaluating that file.
 *
 * ⚠️ **THE INPUTS ARE COPIED AND THE EXPECTATIONS ARE NOT.** abcjs's suite carries expected
 * literals beside each input; every number here comes from running the engine instead. The
 * distinction earned itself on `strTranspose`, where abcjs's own test expects something
 * abcjs does not produce.
 *
 * ⚠️ **AND THREE OF THE ELEVEN CASES ARE OURS.** abcjs renders each input at ONE width, and
 * a wrap measured at one width is a control that cannot move; `piano-300`, `quartet-740`
 * and `split-by-text-300` are the same tunes at a width its suite never tries.
 *
 * ⚠️ **AND THE ROUNDING IS THE TEST'S, NOT abcjs's.** `doWrapTest` rounds `lineBreakPoint`,
 * `minLineSize` and every width to ONE DECIMAL before comparing (`wrap.test.js:296-311`).
 * The golden records the RAW doubles and this rounds on the way in, so the tolerance is
 * visible here rather than baked into the oracle.
 */
const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-wrap", "golden.json"), "utf-8"),
) as Record<
  string,
  {
    abc: string;
    staffwidth: number;
    explanation: Record<string, unknown>[];
    lineBreaks: Record<string, unknown>[] | null;
    svg: string;
  }
>;

/** `doWrapTest`'s own options — the only ones abcjs's suite ever passes. */
const WRAP = { minSpacing: 1.8, maxSpacing: 2.8, preferredMeasuresPerLine: 4 };

const round1 = (n: number): number => Math.round(n * 10) / 10;

/** `wrap.test.js:296-311`, exactly — and it rounds only what it names. */
const rounded = (rows: readonly Record<string, unknown>[]): unknown[] =>
  rows.map((row) => {
    const out: Record<string, unknown> = { ...row };
    delete out.attempts;
    if (typeof out.lineBreakPoint === "number")
      out.lineBreakPoint = round1(out.lineBreakPoint);
    if (typeof out.minLineSize === "number") out.minLineSize = round1(out.minLineSize);
    const w = out.widths as
      | { left?: number; total?: number; measureWidths?: number[] }
      | undefined;
    if (w !== undefined)
      out.widths = {
        ...w,
        ...(typeof w.left === "number" ? { left: round1(w.left) } : {}),
        ...(typeof w.total === "number" ? { total: round1(w.total) } : {}),
        ...(w.measureWidths === undefined
          ? {}
          : { measureWidths: w.measureWidths.map(round1) }),
      };
    return out;
  });

interface Row {
  readonly slug: string;
  readonly wantExplanation: unknown[];
  readonly gotExplanation: unknown[];
  readonly wantBreaks: unknown;
  readonly gotBreaks: unknown;
  /**
   * ⚠️ **AND THE DRAWING IS THE THIRD SURFACE, BECAUSE THE FIRST TWO CAN BE EXACT WHILE THE
   * MUSIC IS NOT RE-LINED AT ALL.** That is what this engine did until `applyLineBreaks`
   * landed: `explanation` and `lineBreaks` byte-perfect on all eleven cases, and ONE system
   * drawn where abcjs draws four. A surface that reports the right answer and does not act
   * on it passes every gate built to read the report.
   */
  readonly svgMatches: boolean;
}

const ours = (
  slug: string,
): { explanation: unknown[]; lineBreaks: unknown; svg: string } => {
  const c = GOLDEN[slug];
  if (c === undefined) return { explanation: [], lineBreaks: null, svg: "" };
  /**
   * ⚠️ **A HEADLESS RENDER NEVER WRAPS, AND THAT IS abcjs's OWN GUARD.**
   * `if (div === "*") removeDiv = true` and then `if (!removeDiv && params.wrap &&
   * params.staffwidth)` (`api/abc_tunebook_svg.js:112-120`) — so `renderAbc('*', abc,
   * {wrap})` comes back with NO `explanation` and NO `lineBreaks` at all, silently. The
   * harvester hit it first and read eleven empty cases as a result rather than an error.
   */
  // …and the target is an ELEMENT, not the string `"paper"`: a selector needs a `document`
  // to resolve against and there is none here, so a string would silently be no target at
  // all — the same absence `'*'` gives, arrived at a different way.
  const tune = renderAbc({ innerHTML: "" }, c.abc, {
    staffwidth: c.staffwidth,
    wrap: WRAP,
  })[0] as unknown as {
    explanation?: Record<string, unknown>[];
    lineBreaks?: unknown;
    svg?: string;
  };
  return {
    explanation: rounded(tune.explanation ?? []),
    lineBreaks: tune.lineBreaks ?? null,
    svg: tune.svg ?? "",
  };
};

const rows = (): Row[] =>
  Object.entries(GOLDEN).map(([slug, c]) => {
    const got = ours(slug);
    return {
      slug,
      wantExplanation: rounded(c.explanation),
      gotExplanation: got.explanation,
      wantBreaks: c.lineBreaks,
      gotBreaks: got.lineBreaks,
      svgMatches: got.svg === c.svg,
    };
  });

/**
 * Cases that agree on BOTH surfaces. Grows, never shrinks.
 *
 * **ALL ELEVEN ON THE FIRST RUN**, which is what the measurement half being already built
 * bought: `getMeasureWidths` lays out at width ZERO whatever `staffwidth` says
 * (`engraver-controller.js:139`), so it is the very call `tuneMetrics` makes — already
 * ported and already gated at 0 of 261. Checked before a line of the search was written:
 * our `widths` are bit-for-bit abcjs's on this oracle, long tails and all
 * (`115.94789193789369`, `20.435498264067185`). What was left was pure arithmetic.
 */
const PASSING: readonly string[] = [
  "short-measures-740",
  "single-line-400",
  "single-line-500",
  "single-line-600",
  "split-by-text-500",
  "piano-500",
  "quartet-500",
  "share-staff-300",
  // …and the three widths abcjs's own suite never renders — a wrap measured at one width
  // is a control that cannot move.
  "piano-300",
  "quartet-740",
  "split-by-text-300",
];

describe("renderAbc({wrap}) — the explanation and the line breaks", () => {
  const table = rows();

  it("measured something real", () => {
    expect(table.length).toBe(11);
    // Every case must have an oracle with rows in it, or the gate is measuring silence —
    // which is exactly what `'*'` gave the harvester before it rendered into a target.
    expect(table.filter((r) => r.wantExplanation.length === 0)).toEqual([]);
  });

  it("every ratcheted case agrees on all three surfaces", () => {
    const broken = table
      .filter((r) => PASSING.includes(r.slug))
      .filter(
        (r) =>
          JSON.stringify(r.wantExplanation) !== JSON.stringify(r.gotExplanation) ||
          JSON.stringify(r.wantBreaks) !== JSON.stringify(r.gotBreaks) ||
          !r.svgMatches,
      )
      .map((r) => r.slug);
    expect(broken).toEqual([]);
  });

  it("nothing outside the ratchet has quietly started agreeing", () => {
    const arrived = table
      .filter((r) => !PASSING.includes(r.slug))
      .filter(
        (r) =>
          JSON.stringify(r.wantExplanation) === JSON.stringify(r.gotExplanation) &&
          JSON.stringify(r.wantBreaks) === JSON.stringify(r.gotBreaks) &&
          r.svgMatches,
      )
      .map((r) => r.slug);
    expect(
      arrived,
      `${arrived.length} agree — add them to PASSING so the ratchet holds them`,
    ).toEqual([]);
  });
});

/**
 * **`wrapLines` REWRITES `tune.lines`, AND NO SVG GATE CAN SEE THAT.**
 * `tune.lines = addLineBreaks(lines, linesBreakElements, barNumbers)`
 * (`parse/wrap_lines.js:13`) — a host that asked for a wrap and then reads `tune.lines`
 * gets the RE-LINED structure. Measured against abcjs: an eight-bar tune under
 * `{wrap, staffwidth: 400}` DRAWS three lines in both engines while `tune.lines` reported
 * three in abcjs and ONE here. The drawing was already right, which is why every byte and
 * pixel gate was quiet, and `tune.lines`'s own corpus is at 100% because nothing in it
 * wraps.
 *
 * The invariant asserted here is abcjs's own: every `line` a `lineBreaks` row names is a
 * staff line of `tune.lines`.
 */
describe("renderAbc({wrap}) — tune.lines is the RE-LINED structure", () => {
  // ⚠️ **NOT `"*"`** — that is a HEADLESS slot and abcjs's guard is
  // `if (!removeDiv && params.wrap && params.staffwidth)` (`api/abc_tunebook_svg.js:119`),
  // so a wrap does NOTHING there and the row list comes back empty. A stub target with an
  // `innerHTML` is what the rest of this file uses, for the same reason.
  const wrapped = (abc: string) =>
    renderAbc({ innerHTML: "" }, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    })[0];

  it("reports one staff line per line the wrap decided", () => {
    const tune = wrapped("X:1\nL:1/4\nK:C\nCDEF|GABc|cdef|gabc'|CDEF|GABc|cdef|gabc'|\n");
    const breaks = tune?.lineBreaks ?? [];
    expect(breaks.length).toBeGreaterThan(1);
    const targets = new Set(breaks.map((b) => b.line));
    const staffLines = (tune?.lines ?? []).filter(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    );
    expect(staffLines.length).toBe(targets.size);
  });

  it("leaves an unwrapped tune's lines exactly as they were", () => {
    // The negative control: `drawnScore()` IS the parsed score when no wrap applies, so
    // this path must be untouched — which is what makes the change above safe.
    const tune = wrapped("X:1\nL:1/4\nK:C\nCDEF|\n");
    const staffLines = (tune?.lines ?? []).filter(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    );
    expect(staffLines.length).toBe(1);
  });
});

/**
 * **A BREAK INDEXES BAR ELEMENTS, NOT MEASURES.**
 *
 * `getMeasureWidths` reports one width per BAR ELEMENT (`engraver-controller.js:167-180`)
 * and `findLineBreaks` counts the same elements (`wrap_lines.js:132-141`), so a measure
 * that OPENS with a barline — a leading `|:`, an ending's invisible bar — contributes TWO
 * where an ordinary measure contributes one. Translating a break index straight onto a
 * measure index under-split every such tune.
 *
 * ⚠️ **AND WHICH MEASURE A BREAK OPENS DEPENDS ON WHICH OF THE TWO IT LANDS ON**: a break
 * at a CLOSING bar opens the next measure, one at an OPENING bar opens that measure.
 *
 * Measured against abcjs on the corpus: eleven fixtures drew a different NUMBER OF LINES
 * and now none does. `tune.lineBreaks` was byte-identical to abcjs's throughout — the
 * wrap's DECISION was never the defect, only this translation back onto the score.
 */
describe("renderAbc({wrap}) — a break is a BAR index, not a measure index", () => {
  /**
   * ⚠️ **COUNT `tune.lines`, NOT `tune.lineBreaks`.** The breaks are the wrap's DECISION,
   * built from the score as PARSED, and they were identical to abcjs's throughout — a
   * count of them passes with the defect in place and proves nothing. `tune.lines` is the
   * RE-LINED structure `applyLineBreaks` produced, which is what this is about. Caught by
   * restoring the old mapping and watching the first form stay green.
   */
  const linesOf = (abc: string): number => {
    const tune = renderAbc({ innerHTML: "" }, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    })[0];
    return (tune?.lines ?? []).filter(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    ).length;
  };

  it("splits a tune that OPENS with a repeat barline", () => {
    // `|:CDEF|1GABc:|3cdef|]` — three measures, FOUR bar elements, and abcjs answers
    // `lineBreaks: [[2]]`. Read as a measure index that found nothing and drew one line.
    expect(linesOf("X:2\nL:1/4\nK:C\n|:CDEF|1GABc:|3cdef|]\n")).toBe(2);
  });

  it("leaves a tune with no opening barlines exactly where it was", () => {
    // The negative control: eight ordinary measures, eight bar elements, no offset to get
    // wrong — this is the shape that passed before the fix and must still.
    expect(linesOf("X:1\nL:1/4\nK:C\nCDEF|GABc|cdef|gabc'|CDEF|GABc|cdef|gabc'|\n")).toBe(3);
  });
});

/**
 * **A WRAP DROPS THE METER FROM THE WHOLE TUNE WHEN A NON-MUSIC ROW COMES FIRST.**
 *
 *     if (keys[k] === "meter" && action.line !== 0) skip = true;      // wrap_lines.js:43
 *
 * ⚠️ **`action.line` IS THE OUTPUT LINE INDEX OVER THE WHOLE TUNE AND IT COUNTS THE
 * NON-MUSIC ROWS.** `findLineBreaks` advances one `outputLine` for a subtitle, a `%%text`,
 * a `%%sep` or a `%%newpage` exactly as it does for a staff line (`wrap_lines.js:150-153`),
 * so a tune opening with a subtitle has its music on line 1 and loses the meter on EVERY
 * system — the first included. The option's name reads as though only the REPRINTS go.
 *
 * Measured over the corpus under `{wrap, staffwidth: 400}`: 41 of 685 fixtures put the
 * music off line 0, and abcjs's `staff.meter` is absent on all 41. `zzopts`'s
 * `wrap + staffwidth` row 59 -> 53.
 */
describe("renderAbc({wrap}) — the meter goes with a non-music first row", () => {
  const meterOnFirstStaff = (abc: string): string => {
    const tune = renderAbc({ innerHTML: "" }, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    })[0];
    const line = (tune?.lines ?? []).find(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    ) as { staff: { meter?: { type?: string } }[] } | undefined;
    return line?.staff[0]?.meter?.type ?? "NONE";
  };

  it("drops it when a SUBTITLE takes output line 0", () => {
    expect(meterOnFirstStaff("X:1\nT:T\nT:Sub\nM:4/4\nL:1/4\nA4|\nB4|\n")).toBe("NONE");
  });

  it("drops it when a %%text takes output line 0", () => {
    expect(meterOnFirstStaff("X:1\nT:T\nM:4/4\nL:1/4\n%%text hi\nA4|\nB4|\n")).toBe("NONE");
  });

  it("drops it when a %%newpage takes output line 0", () => {
    // ⚠️ `Score.newPage` is a NUMBER here, not a flag — `%%newpage 1` reads back as `1`,
    // and a `=== true` test misses this fixture alone out of the corpus's 41.
    expect(meterOnFirstStaff("X:1\nT:T\n%%newpage 1\nM:4/4\nL:1/4\nA4|\nB4|\n")).toBe("NONE");
  });

  it("KEEPS it when the music really is output line 0", () => {
    // The negative control, and the half that was already right: with nothing before the
    // music abcjs's `action.line` IS 0 and the meter survives. A test that only asserted
    // "NONE" would pass with the meter deleted outright.
    expect(meterOnFirstStaff("X:1\nT:T\nM:4/4\nL:1/4\nA4|\nB4|\n")).toBe("specified");
  });

  it("KEEPS it with a subtitle when NO wrap runs", () => {
    // The second control: the suppression belongs to `wrapLines` and nothing else. abcjs
    // never calls it without `wrap`, and `svg-bytes` stays 0 of 691 because of this row.
    const tune = renderAbc({ innerHTML: "" }, "X:1\nT:T\nT:Sub\nM:4/4\nL:1/4\nA4|\nB4|\n", {
      staffwidth: 400,
    })[0];
    const line = (tune?.lines ?? []).find(
      (l) => (l as { staff?: unknown }).staff !== undefined,
    ) as { staff: { meter?: { type?: string } }[] } | undefined;
    expect(line?.staff[0]?.meter?.type ?? "NONE").toBe("specified");
  });
});

/**
 * **AN ENDING DECLARED ON THE BARLINE THAT *ENDS* A SYSTEM OPENS ON THAT SYSTEM.**
 *
 * abcjs opens the `EndingElem` where it processes the BAR: `elem.startEnding` is read in
 * `createABCBar` and `voice.addOther(this.partstartelem)` puts it on the voice of the line
 * being built (`abstract-engraver.js:1034-1042`). A break at that bar leaves it the LAST
 * element of the line it CLOSES — `findLineBreaks` pushes `{start, end: e}` with `e` the
 * bar itself (`wrap_lines.js:132-141`) — so the ending opens there, as a hook at the
 * line's right edge WITH its number, and the next line gets a fresh
 * `EndingElem("", null, null)` from `createABCVoice`'s `if (this.partstartelem)`
 * (`:230-233`): no hook, no number.
 *
 * Ours drew ONE bracket, numbered, on the wrong system. `zzopts`'s `wrap + staffwidth`
 * row 53 -> 48.
 */
describe("renderAbc({wrap}) — an ending opens on the system holding its barline", () => {
  /** Every drawn ending bracket, as `x-of-first-hook/label`, in document order. */
  const endingsOf = (abc: string): string[] => {
    const host = { innerHTML: "" } as { innerHTML: string };
    renderAbc(host, abc, {
      staffwidth: 400,
      wrap: { minSpacing: 1.8, maxSpacing: 2.7, preferredMeasuresPerLine: 4 },
    });
    return [...host.innerHTML.matchAll(/<g[^>]*data-name="ending"[^>]*>(.*?)<\/g>/g)].map(
      (m) => {
        const x = /M ([0-9.]+) /.exec(m[1] ?? "")?.[1] ?? "?";
        const label = /<tspan[^>]*>([^<]*)<\/tspan>/.exec(m[1] ?? "")?.[1] ?? "";
        return `${x}/${label}`;
      },
    );
  };

  // `|:CDEF|1GABc:|3cdef|]` — three measures, FOUR bar elements, `lineBreaks: [[2]]`, and
  // the break lands on the `:|` that DECLARES the `3`. abcjs draws THREE brackets: the
  // `1` closing at the line end, the `3` opening AT it, and its bare continuation.
  it("opens the 3 at the line's right edge and continues it unnumbered", () => {
    expect(endingsOf("X:2\nT:E\nL:1/4\nK:C\n|:CDEF|1GABc:|3cdef|]\n")).toEqual([
      "226.78/1",
      "415/3",
      "222.76/",
    ]);
  });

  it("leaves an ending that fits on one system exactly where it was", () => {
    // The negative control: no break falls on the `:|`, so nothing is carried and both
    // brackets are ordinary numbered ones. This is the shape that passed before the fix.
    // Both numbers read off abcjs, not off our own output.
    expect(endingsOf("X:2\nT:E\nL:1/4\nK:C\n|:CD|1GA:|2ce|]\n")).toEqual([
      "165.9/1",
      "293.26/2",
    ]);
  });
});
