import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { renderAbc } from "../src/compat/index.js";

/**
 * **`renderAbc(…, {wrap})` — THE TWO THINGS IT HANDS BACK.**
 *
 * `tune.explanation` is the wrap search's own reasoning, one row per ORIGINAL line: the
 * measured `widths` (the prefix `left`, every `measureWidths`, and their `total`), the
 * `lineBreakPoint` it aimed at, the `minLineSize` it would not go under, the `staffWidth`
 * it was given and the `minWidth` it settled on. `tune.lineBreaks` is the ANSWER — one row
 * per drawn line, saying which original line it came from (`ogLine`) and which slice of
 * that voice it holds (`start`, `end`).
 *
 * ── THE ORACLE ──────────────────────────────────────────────────────────────
 * `tests/corpus-wrap/golden.json`, generated by RUNNING abcjs 6.7.0
 * (`scripts/harvest-abcjs-wrap.ts`) over its OWN wrap inputs — the six `var abc…`
 * declarations in `tests/visual/wrap.test.js`, pulled out by evaluating that file.
 *
 * ⚠️ **THE INPUTS ARE COPIED AND THE EXPECTATIONS ARE NOT.** abcjs's suite carries expected
 * literals beside each input; every number here comes from running the engine instead. The
 * distinction earned itself on `strTranspose`, where abcjs's own test expects something
 * abcjs does not produce.
 *
 * ⚠️ **AND THREE OF THE ELEVEN CASES ARE OURS.** abcjs renders each input at ONE width, and
 * a wrap measured at one width is a control that cannot move; `piano-300`, `quartet-740`
 * and `split-by-text-300` are the same tunes at a width its suite never tries.
 *
 * ⚠️ **AND THE ROUNDING IS THE TEST'S, NOT abcjs's.** `doWrapTest` rounds `lineBreakPoint`,
 * `minLineSize` and every width to ONE DECIMAL before comparing (`wrap.test.js:296-311`).
 * The golden records the RAW doubles and this rounds on the way in, so the tolerance is
 * visible here rather than baked into the oracle.
 */
const GOLDEN = JSON.parse(
  readFileSync(join(import.meta.dirname, "corpus-wrap", "golden.json"), "utf-8"),
) as Record<
  string,
  {
    abc: string;
    staffwidth: number;
    explanation: Record<string, unknown>[];
    lineBreaks: Record<string, unknown>[] | null;
    svg: string;
  }
>;

/** `doWrapTest`'s own options — the only ones abcjs's suite ever passes. */
const WRAP = { minSpacing: 1.8, maxSpacing: 2.8, preferredMeasuresPerLine: 4 };

const round1 = (n: number): number => Math.round(n * 10) / 10;

/** `wrap.test.js:296-311`, exactly — and it rounds only what it names. */
const rounded = (rows: readonly Record<string, unknown>[]): unknown[] =>
  rows.map((row) => {
    const out: Record<string, unknown> = { ...row };
    delete out.attempts;
    if (typeof out.lineBreakPoint === "number")
      out.lineBreakPoint = round1(out.lineBreakPoint);
    if (typeof out.minLineSize === "number") out.minLineSize = round1(out.minLineSize);
    const w = out.widths as
      | { left?: number; total?: number; measureWidths?: number[] }
      | undefined;
    if (w !== undefined)
      out.widths = {
        ...w,
        ...(typeof w.left === "number" ? { left: round1(w.left) } : {}),
        ...(typeof w.total === "number" ? { total: round1(w.total) } : {}),
        ...(w.measureWidths === undefined
          ? {}
          : { measureWidths: w.measureWidths.map(round1) }),
      };
    return out;
  });

interface Row {
  readonly slug: string;
  readonly wantExplanation: unknown[];
  readonly gotExplanation: unknown[];
  readonly wantBreaks: unknown;
  readonly gotBreaks: unknown;
  /**
   * ⚠️ **AND THE DRAWING IS THE THIRD SURFACE, BECAUSE THE FIRST TWO CAN BE EXACT WHILE THE
   * MUSIC IS NOT RE-LINED AT ALL.** That is what this engine did until `applyLineBreaks`
   * landed: `explanation` and `lineBreaks` byte-perfect on all eleven cases, and ONE system
   * drawn where abcjs draws four. A surface that reports the right answer and does not act
   * on it passes every gate built to read the report.
   */
  readonly svgMatches: boolean;
}

const ours = (
  slug: string,
): { explanation: unknown[]; lineBreaks: unknown; svg: string } => {
  const c = GOLDEN[slug];
  if (c === undefined) return { explanation: [], lineBreaks: null, svg: "" };
  /**
   * ⚠️ **A HEADLESS RENDER NEVER WRAPS, AND THAT IS abcjs's OWN GUARD.**
   * `if (div === "*") removeDiv = true` and then `if (!removeDiv && params.wrap &&
   * params.staffwidth)` (`api/abc_tunebook_svg.js:112-120`) — so `renderAbc('*', abc,
   * {wrap})` comes back with NO `explanation` and NO `lineBreaks` at all, silently. The
   * harvester hit it first and read eleven empty cases as a result rather than an error.
   */
  // …and the target is an ELEMENT, not the string `"paper"`: a selector needs a `document`
  // to resolve against and there is none here, so a string would silently be no target at
  // all — the same absence `'*'` gives, arrived at a different way.
  const tune = renderAbc({ innerHTML: "" }, c.abc, {
    staffwidth: c.staffwidth,
    wrap: WRAP,
  })[0] as unknown as {
    explanation?: Record<string, unknown>[];
    lineBreaks?: unknown;
    svg?: string;
  };
  return {
    explanation: rounded(tune.explanation ?? []),
    lineBreaks: tune.lineBreaks ?? null,
    svg: tune.svg ?? "",
  };
};

const rows = (): Row[] =>
  Object.entries(GOLDEN).map(([slug, c]) => {
    const got = ours(slug);
    return {
      slug,
      wantExplanation: rounded(c.explanation),
      gotExplanation: got.explanation,
      wantBreaks: c.lineBreaks,
      gotBreaks: got.lineBreaks,
      svgMatches: got.svg === c.svg,
    };
  });

/**
 * Cases that agree on BOTH surfaces. Grows, never shrinks.
 *
 * **ALL ELEVEN ON THE FIRST RUN**, which is what the measurement half being already built
 * bought: `getMeasureWidths` lays out at width ZERO whatever `staffwidth` says
 * (`engraver-controller.js:139`), so it is the very call `tuneMetrics` makes — already
 * ported and already gated at 0 of 261. Checked before a line of the search was written:
 * our `widths` are bit-for-bit abcjs's on this oracle, long tails and all
 * (`115.94789193789369`, `20.435498264067185`). What was left was pure arithmetic.
 */
const PASSING: readonly string[] = [
  "short-measures-740",
  "single-line-400",
  "single-line-500",
  "single-line-600",
  "split-by-text-500",
  "piano-500",
  "quartet-500",
  "share-staff-300",
  // …and the three widths abcjs's own suite never renders — a wrap measured at one width
  // is a control that cannot move.
  "piano-300",
  "quartet-740",
  "split-by-text-300",
];

describe("renderAbc({wrap}) — the explanation and the line breaks", () => {
  const table = rows();

  it("measured something real", () => {
    expect(table.length).toBe(11);
    // Every case must have an oracle with rows in it, or the gate is measuring silence —
    // which is exactly what `'*'` gave the harvester before it rendered into a target.
    expect(table.filter((r) => r.wantExplanation.length === 0)).toEqual([]);
  });

  it("every ratcheted case agrees on all three surfaces", () => {
    const broken = table
      .filter((r) => PASSING.includes(r.slug))
      .filter(
        (r) =>
          JSON.stringify(r.wantExplanation) !== JSON.stringify(r.gotExplanation) ||
          JSON.stringify(r.wantBreaks) !== JSON.stringify(r.gotBreaks) ||
          !r.svgMatches,
      )
      .map((r) => r.slug);
    expect(broken).toEqual([]);
  });

  it("nothing outside the ratchet has quietly started agreeing", () => {
    const arrived = table
      .filter((r) => !PASSING.includes(r.slug))
      .filter(
        (r) =>
          JSON.stringify(r.wantExplanation) === JSON.stringify(r.gotExplanation) &&
          JSON.stringify(r.wantBreaks) === JSON.stringify(r.gotBreaks) &&
          r.svgMatches,
      )
      .map((r) => r.slug);
    expect(
      arrived,
      `${arrived.length} agree — add them to PASSING so the ratchet holds them`,
    ).toEqual([]);
  });
});
